### ISSUE TITLE
Reports cannot be exported from the reports tab

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1011]
Cannot export reports - I get an error message: “Server error: Cannot read property 'fields' of undefined”

**Comment by garethbowen** [comment]
@sglangevin Which screen are you exporting reports from? Can you provide any more details? For example, I think the full error will be logged in the API logs which would be ideal if you can find it.

**Comment by garethbowen** [comment]
API log:

```2015-06-23T03:43:04.088Z - error: UNCAUGHT EXCEPTION!

2015-06-23T03:43:04.093Z - error: { [TypeError: Cannot read property 'fields' of undefined]
  domain:
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }

2015-06-23T03:43:04.100Z - error: Server error: TypeError: Cannot read property 'fields' of undefined
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/export-data.js:78:28
    at Array.forEach (native)
    at Object.exportTypes.forms.generate (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/export-data.js:73:12)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/export-data.js:577:23
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/fti.js:86:7
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/utils.js:34:5
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/db.js:48:7
    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/lib/nano.js:210:16)
    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/node_modules/request/request.js:197:22)
    at Request.emit (events.js:110:17)

2015-06-23T03:43:04.103Z - error: undefined```

**Comment by garethbowen** [comment]
It looks like you have at least one form in your export data that doesn't have a configuration. This could happen if...

1. You configure form code `X`
2. You submit a form with code `X`
3. You remove the configuration for form code `X`

I've modified the code so in this case you will get a tab for `X` without the columns specific to `X` because we can't guess them.
