### ISSUE TITLE
Can kill API process with a badly-formed request

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1102]
# Observed

## CLI

```$ curl -X POST http://admin:pass@localhost:5988/api/v1/records
Server error: Cannot read property 'writeHead' of undefined```

## Server logs

```
17:44:15 api.1    | ::1 - admin [28/Jul/2015:15:44:15 +0000] "POST /api/v1/records HTTP/1.1" - - "-" "curl/7.37.1"
17:44:15 couch.1  | [info] [<0.284.0>] 127.0.0.1 - - GET /_session 200
17:44:15 api.1    | Server error:
17:44:15 api.1    | undefined
17:44:15 api.1    |   detail: "Content type not supported."
17:44:15 api.1    | UNCAUGHT EXCEPTION!
17:44:15 api.1    | { [TypeError: Cannot read property 'writeHead' of undefined]
17:44:15 api.1    |   domain:
17:44:15 api.1    |    { domain: null,
17:44:15 api.1    |      _events: { error: [Function] },
17:44:15 api.1    |      _maxListeners: undefined,
17:44:15 api.1    |      members: [] },
17:44:15 api.1    |   domainThrown: true }
17:44:15 api.1    | Server error:
17:44:15 api.1    | /api/v1/records
17:44:15 api.1    |   detail: TypeError: Cannot read property 'writeHead' of undefined
17:44:15 api.1    |     at serverError (/Users/user/workspaces/medic/api/server.js:526:6)
17:44:15 api.1    |     at /Users/user/workspaces/medic/api/server.js:370:16
17:44:15 api.1    |     at Object.module.exports.create (/Users/user/workspaces/medic/api/controllers/records.js:64:14)
17:44:15 api.1    |     at /Users/user/workspaces/medic/api/server.js:368:13
17:44:15 api.1    |     at /Users/user/workspaces/medic/api/auth.js:159:16
17:44:15 api.1    |     at /Users/user/workspaces/medic/api/auth.js:136:9
17:44:15 api.1    |     at IncomingMessage.<anonymous> (/Users/user/workspaces/medic/api/auth.js:69:7)
17:44:15 api.1    |     at IncomingMessage.emit (events.js:129:20)
17:44:15 api.1    |     at _stream_readable.js:908:16
17:44:15 api.1    |     at process._tickDomainCallback (node.js:381:11)
17:44:15 api.1    | undefined
17:44:15 api.1    | make[1]: *** [api] Error 1
17:44:15 api.1    | exited with code 2
```

# Expected

API should not crash if given requests it doesn't understand.

**Comment by alxndrsn** [comment]
Likely related: when sending a POST with content-type `application/json` and valid JSON content:

```
7:49:11 api.1    | Server error:
17:49:11 api.1    | undefined
17:49:11 api.1    |   detail: "Missing required field: from"
17:49:11 api.1    | UNCAUGHT EXCEPTION!
17:49:11 api.1    | { [TypeError: Cannot read property 'writeHead' of undefined]
17:49:11 api.1    |   domain:
17:49:11 api.1    |    { domain: null,
17:49:11 api.1    |      _events: { error: [Function] },
17:49:11 api.1    |      _maxListeners: undefined,
17:49:11 api.1    |      members: [] },
17:49:11 api.1    |   domainThrown: true }
17:49:11 api.1    | Server error:
17:49:11 api.1    | /medic/_design/medic/_rewrite
17:49:11 api.1    |   detail: TypeError: Cannot read property 'writeHead' of undefined
17:49:11 api.1    |     at serverError (/Users/user/workspaces/medic/api/server.js:526:6)
17:49:11 api.1    |     at /Users/user/workspaces/medic/api/server.js:370:16
17:49:11 api.1    |     at createRecordByJSON (/Users/user/workspaces/medic/api/controllers/records.js:47:14)
17:49:11 api.1    |     at Object.module.exports.create (/Users/user/workspaces/medic/api/controllers/records.js:66:5)
17:49:11 api.1    |     at /Users/user/workspaces/medic/api/server.js:368:13
17:49:11 api.1    |     at /Users/user/workspaces/medic/api/auth.js:159:16
17:49:11 api.1    |     at /Users/user/workspaces/medic/api/auth.js:136:9
17:49:11 api.1    |     at IncomingMessage.<anonymous> (/Users/user/workspaces/medic/api/auth.js:69:7)
17:49:11 api.1    |     at IncomingMessage.emit (events.js:129:20)
17:49:11 api.1    |     at _stream_readable.js:908:16
17:49:11 api.1    | UNCAUGHT EXCEPTION!
17:49:11 api.1    | { [Error: Can't set headers after they are sent.]
17:49:11 api.1    |   domain:
17:49:11 api.1    |    { domain: null,
17:49:11 api.1    |      _events: { error: [Function] },
17:49:11 api.1    |      _maxListeners: undefined,
17:49:11 api.1    |      members: [] },
17:49:11 api.1    |   domainThrown: true }
17:49:11 api.1    | Server error:
17:49:11 api.1    | /medic/_design/medic/_rewrite
17:49:11 api.1    |   detail: Error: Can't set headers after they are sent.
17:49:11 api.1    |     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
17:49:11 api.1    |     at ServerResponse.res.writeHead (/Users/user/workspaces/medic/api/server.js:451:9)
17:49:11 api.1    |     at serverError (/Users/user/workspaces/medic/api/server.js:526:7)
17:49:11 api.1    |     at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:72:5)
17:49:11 api.1    |     at Domain.emit (events.js:107:17)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    | UNCAUGHT EXCEPTION!
17:49:11 api.1    | { [Error: Can't set headers after they are sent.]
17:49:11 api.1    |   domain:
17:49:11 api.1    |    { domain: null,
17:49:11 api.1    |      _events: { error: [Function] },
17:49:11 api.1    |      _maxListeners: undefined,
17:49:11 api.1    |      members: [] },
17:49:11 api.1    |   domainThrown: true }
17:49:11 api.1    | Server error:
17:49:11 api.1    | /medic/_design/medic/static/dist/dependencies.js
17:49:11 api.1    |   detail: Error: Can't set headers after they are sent.
17:49:11 api.1    |     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
17:49:11 api.1    |     at ServerResponse.res.writeHead (/Users/user/workspaces/medic/api/server.js:451:9)
17:49:11 api.1    |     at serverError (/Users/user/workspaces/medic/api/server.js:526:7)
17:49:11 api.1    |     at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:72:5)
17:49:11 api.1    |     at Domain.emit (events.js:107:17)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    | UNCAUGHT EXCEPTION!
17:49:11 api.1    | { [Error: Can't set headers after they are sent.]
17:49:11 api.1    |   domain:
17:49:11 api.1    |    { domain: null,
17:49:11 api.1    |      _events: { error: [Function] },
17:49:11 api.1    |      _maxListeners: undefined,
17:49:11 api.1    |      members: [] },
17:49:11 api.1    |   domainThrown: true }
17:49:11 api.1    | Server error:
17:49:11 api.1    | /medic/_design/medic/static/img/icon-chw.svg
17:49:11 api.1    |   detail: Error: Can't set headers after they are sent.
17:49:11 api.1    |     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
17:49:11 api.1    |     at ServerResponse.res.writeHead (/Users/user/workspaces/medic/api/server.js:451:9)
17:49:11 api.1    |     at serverError (/Users/user/workspaces/medic/api/server.js:526:7)
17:49:11 api.1    |     at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:72:5)
17:49:11 api.1    |     at Domain.emit (events.js:107:17)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    | UNCAUGHT EXCEPTION!
17:49:11 api.1    | { [Error: Can't set headers after they are sent.]
17:49:11 api.1    |   domain:
17:49:11 api.1    |    { domain: null,
17:49:11 api.1    |      _events: { error: [Function] },
17:49:11 api.1    |      _maxListeners: undefined,
17:49:11 api.1    |      members: [] },
17:49:11 api.1    |   domainThrown: true }
17:49:11 api.1    | Server error:
17:49:11 api.1    | /medic/_design/medic/static/img/icon-nurse.svg
17:49:11 api.1    |   detail: Error: Can't set headers after they are sent.
17:49:11 api.1    |     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
17:49:11 api.1    |     at ServerResponse.res.writeHead (/Users/user/workspaces/medic/api/server.js:451:9)
17:49:11 api.1    |     at serverError (/Users/user/workspaces/medic/api/server.js:526:7)
17:49:11 api.1    |     at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:72:5)
17:49:11 api.1    |     at Domain.emit (events.js:107:17)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    | UNCAUGHT EXCEPTION!
17:49:11 api.1    | { [Error: Can't set headers after they are sent.]
17:49:11 api.1    |   domain:
17:49:11 api.1    |    { domain: null,
17:49:11 api.1    |      _events: { error: [Function] },
17:49:11 api.1    |      _maxListeners: undefined,
17:49:11 api.1    |      members: [] },
17:49:11 api.1    |   domainThrown: true }
17:49:11 api.1    | Server error:
17:49:11 api.1    | /medic/_design/medic/static/fonts/fontawesome-webfont.woff
17:49:11 api.1    |   detail: Error: Can't set headers after they are sent.
17:49:11 api.1    |     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
17:49:11 api.1    |     at ServerResponse.res.writeHead (/Users/user/workspaces/medic/api/server.js:451:9)
17:49:11 api.1    |     at serverError (/Users/user/workspaces/medic/api/server.js:526:7)
17:49:11 api.1    |     at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:72:5)
17:49:11 api.1    |     at Domain.emit (events.js:107:17)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    | UNCAUGHT EXCEPTION!
17:49:11 api.1    | { [Error: Can't set headers after they are sent.]
17:49:11 api.1    |   domain:
17:49:11 api.1    |    { domain: null,
17:49:11 api.1    |      _events: { error: [Function] },
17:49:11 api.1    |      _maxListeners: undefined,
17:49:11 api.1    |      members: [] },
17:49:11 api.1    |   domainThrown: true }
17:49:11 api.1    | Server error:
17:49:11 api.1    | /medic/_design/medic/static/dist/root.js
17:49:11 api.1    |   detail: Error: Can't set headers after they are sent.
17:49:11 api.1    |     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
17:49:11 api.1    |     at ServerResponse.res.writeHead (/Users/user/workspaces/medic/api/server.js:451:9)
17:49:11 api.1    |     at serverError (/Users/user/workspaces/medic/api/server.js:526:7)
17:49:11 api.1    |     at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:72:5)
17:49:11 api.1    |     at Domain.emit (events.js:107:17)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    | UNCAUGHT EXCEPTION!
17:49:11 api.1    | { [Error: Can't set headers after they are sent.]
17:49:11 api.1    |   domain:
17:49:11 api.1    |    { domain: null,
17:49:11 api.1    |      _events: { error: [Function] },
17:49:11 api.1    |      _maxListeners: undefined,
17:49:11 api.1    |      members: [] },
17:49:11 api.1    |   domainThrown: true }
17:49:11 api.1    | Server error:
17:49:11 api.1    | /medic/_design/medic/static/fonts/fontawesome-webfont.woff2
17:49:11 api.1    |   detail: Error: Can't set headers after they are sent.
17:49:11 api.1    |     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
17:49:11 api.1    |     at ServerResponse.res.writeHead (/Users/user/workspaces/medic/api/server.js:451:9)
17:49:11 api.1    |     at serverError (/Users/user/workspaces/medic/api/server.js:526:7)
17:49:11 api.1    |     at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:72:5)
17:49:11 api.1    |     at Domain.emit (events.js:107:17)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    | UNCAUGHT EXCEPTION!
17:49:11 api.1    | { [Error: Can't set headers after they are sent.]
17:49:11 api.1    |   domain:
17:49:11 api.1    |    { domain: null,
17:49:11 api.1    |      _events: { error: [Function] },
17:49:11 api.1    |      _maxListeners: undefined,
17:49:11 api.1    |      members: [] },
17:49:11 api.1    |   domainThrown: true }
17:49:11 api.1    | Server error:
17:49:11 api.1    | /medic/_design/medic/static/img/ico/icon_16.ico
17:49:11 api.1    |   detail: Error: Can't set headers after they are sent.
17:49:11 api.1    |     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
17:49:11 api.1    |     at ServerResponse.res.writeHead (/Users/user/workspaces/medic/api/server.js:451:9)
17:49:11 api.1    |     at serverError (/Users/user/workspaces/medic/api/server.js:526:7)
17:49:11 api.1    |     at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:72:5)
17:49:11 api.1    |     at Domain.emit (events.js:107:17)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    | UNCAUGHT EXCEPTION!
17:49:11 api.1    | { [Error: Can't set headers after they are sent.]
17:49:11 api.1    |   domain:
17:49:11 api.1    |    { domain: null,
17:49:11 api.1    |      _events: { error: [Function] },
17:49:11 api.1    |      _maxListeners: undefined,
17:49:11 api.1    |      members: [] },
17:49:11 api.1    |   domainThrown: true }
17:49:11 api.1    | Server error:
17:49:11 api.1    | /medic/_design/medic/static/img/medic-logo-light.svg
17:49:11 api.1    |   detail: Error: Can't set headers after they are sent.
17:49:11 api.1    |     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
17:49:11 api.1    |     at ServerResponse.res.writeHead (/Users/user/workspaces/medic/api/server.js:451:9)
17:49:11 api.1    |     at serverError (/Users/user/workspaces/medic/api/server.js:526:7)
17:49:11 api.1    |     at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:72:5)
17:49:11 api.1    |     at Domain.emit (events.js:107:17)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11 api.1    | UNCAUGHT EXCEPTION!
17:49:11 api.1    | { [Error: Can't set headers after they are sent.]
17:49:11 api.1    |   domain:
17:49:11 api.1    |    { domain: null,
17:49:11 api.1    |      _events: { error: [Function] },
17:49:11 api.1    |      _maxListeners: undefined,
17:49:11 api.1    |      members: [] },
17:49:11 api.1    |   domainThrown: true }
17:49:11 api.1    | Server error:
17:49:11 api.1    | /medic/_design/medic/static/img/ico/icon_48.ico
17:49:11 api.1    |   detail: Error: Can't set headers after they are sent.
17:49:11 api.1    |     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
17:49:11 api.1    |     at ServerResponse.res.writeHead (/Users/user/workspaces/medic/api/server.js:451:9)
17:49:11 api.1    |     at serverError (/Users/user/workspaces/medic/api/server.js:526:7)
17:49:11 api.1    |     at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:72:5)
17:49:11 api.1    |     at Domain.emit (events.js:107:17)
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
17:49:11 api.1    |     at process._fatalException (node.js:233:33)
17:49:11 api.1    | exited with code 2
17:49:11 system   | sending SIGTERM to all processes
17:49:11 api.1    |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11          |     at process._fatalException (node.js:233:33)
17:49:11          |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11          | UNCAUGHT EXCEPTION!
17:49:11          | { [Error: Can't set headers after they are sent.]
17:49:11          |   domain:
17:49:11          |    { domain: null,
17:49:11          |      _events: { error: [Function] },
17:49:11          |      _maxListeners: undefined,
17:49:11          |      members: [] },
17:49:11          |   domainThrown: true }
17:49:11          | Server error:
17:49:11          | /medic/_design/medic/static/dist/manifest.appcache
17:49:11          |   detail: Error: Can't set headers after they are sent.
17:49:11          |     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
17:49:11          |     at ServerResponse.res.writeHead (/Users/user/workspaces/medic/api/server.js:451:9)
17:49:11 webapp.1 | make[1]: *** [webapp] Terminated: 15
17:49:11          |     at serverError (/Users/user/workspaces/medic/api/server.js:526:7)
17:49:11          |     at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:72:5)
17:49:11          |     at Domain.emit (events.js:107:17)
17:49:11          |     at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
17:49:11          |     at process._fatalException (node.js:233:33)
17:49:11          |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11          |     at process._fatalException (node.js:233:33)
17:49:11          |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11          | UNCAUGHT EXCEPTION!
17:49:11          | { [Error: Can't set headers after they are sent.]
17:49:11          |   domain:
17:49:11          |    { domain: null,
17:49:11          |      _events: { error: [Function] },
17:49:11          |      _maxListeners: undefined,
17:49:11          |      members: [] },
17:49:11          |   domainThrown: true }
17:49:11          | Server error:
17:49:11          | /medic/_design/medic/_rewrite
17:49:11          |   detail: Error: Can't set headers after they are sent.
17:49:11          |     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
17:49:11          |     at ServerResponse.res.writeHead (/Users/user/workspaces/medic/api/server.js:451:9)
17:49:11          |     at serverError (/Users/user/workspaces/medic/api/server.js:526:7)
17:49:11          |     at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:72:5)
17:49:11          |     at Domain.emit (events.js:107:17)
17:49:11          |     at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
17:49:11          |     at process._fatalException (node.js:233:33)
17:49:11          |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11          |     at process._fatalException (node.js:233:33)
17:49:11          |     at Domain.errorHandler [as _errorHandler] (domain.js:119:24)
17:49:11          | /Users/user/workspaces/medic/api/server.js:526
17:49:11          |   res.writeHead(500, {
17:49:11          |      ^
17:49:11          | TypeError: Cannot read property 'writeHead' of undefined
17:49:11          |     at serverError (/Users/user/workspaces/medic/api/server.js:526:6)
17:49:11          |     at /Users/user/workspaces/medic/api/server.js:370:16
17:49:11          |     at createRecordByJSON (/Users/user/workspaces/medic/api/controllers/records.js:47:14)
17:49:11          |     at Object.module.exports.create (/Users/user/workspaces/medic/api/controllers/records.js:66:5)
17:49:11          |     at /Users/user/workspaces/medic/api/server.js:368:13
17:49:11          |     at /Users/user/workspaces/medic/api/auth.js:159:16
17:49:11 couch.1  | make[1]: *** [couch] Terminated: 15
17:49:11          |     at /Users/user/workspaces/medic/api/auth.js:136:9
17:49:11          |     at IncomingMessage.<anonymous> (/Users/user/workspaces/medic/api/auth.js:69:7)
17:49:11          |     at IncomingMessage.emit (events.js:129:20)
17:49:11          |     at _stream_readable.js:908:16
17:49:11          | make[1]: *** [api] Error 1
```

**Comment by garethbowen** [comment]
Results after patch:

### First bug

`curl -X POST http://gareth:pass@localhost:5988/api/v1/records`
```
Server error: 
  detail: "Content type not supported."
```

### Second bug

`curl -X POST -H "Content-Type:application/json" --data '{"_meta":{"form":"V","reported_date":1438098551510},"fields":{"pregnancy_id":"11111"},"pregnancy_id":"11111"}' http://gareth:pass@localhost:5988/api/v1/records`
```
Server error: 
  detail: "Missing required field: from"
```
