### ISSUE TITLE
Cannot login from unbranded android app

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1237]
When I set the url to `http://x.x.x.x:5988/medic` I get a validation error in the UI and this in the log:

```
09-03 05:08:28.964  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ java.io.FileNotFoundException: http://x.x.x.x:5988/medic
09-03 05:08:28.965  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:186)
09-03 05:08:28.965  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ at org.medicmobile.webapp.mobile.SimpleJsonClient2.get(SimpleJsonClient2.java:32)
09-03 05:08:28.966  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ at org.medicmobile.webapp.mobile.SimpleJsonClient2.get(SimpleJsonClient2.java:21)
09-03 05:08:28.966  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ at org.medicmobile.webapp.mobile.AppUrlVerifier.verify(AppUrlVerifier.java:14)
09-03 05:08:28.966  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ at org.medicmobile.webapp.mobile.SettingsDialogActivity.verify(SettingsDialogActivity.java:49)
09-03 05:08:28.966  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ at org.medicmobile.webapp.mobile.SettingsDialogActivity.access$000(SettingsDialogActivity.java:12)
09-03 05:08:28.966  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ at org.medicmobile.webapp.mobile.SettingsDialogActivity$1.doInBackground(SettingsDialogActivity.java:34)
09-03 05:08:28.967  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ at org.medicmobile.webapp.mobile.SettingsDialogActivity$1.doInBackground(SettingsDialogActivity.java:31)
09-03 05:08:28.967  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:288)
09-03 05:08:28.967  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-03 05:08:28.967  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
09-03 05:08:28.967  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-03 05:08:28.967  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-03 05:08:28.967  23844-24013/org.medicmobile.webapp.mobile W/System.err﹕ at java.lang.Thread.run(Thread.java:848)
```

When I set the url to `http://x.x.x.x:5988/medic/login` I get a validation error in the UI and this in the log:

```
09-03 05:00:14.847  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ LOG | SimpleJsonClient.get()url=http://x.x.x.x:5988/medic/login;
09-03 05:00:14.850  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ LOG | SimpleJsonClient.get()url=http://x.x.x.x:5988/medic/login;
09-03 05:00:14.853  23844-24814/org.medicmobile.webapp.mobile I/System.out﹕ [CDS]rx timeout:0
09-03 05:00:14.871  23844-24814/org.medicmobile.webapp.mobile I/System.out﹕ [CDS]rx timeout:100
09-03 05:00:14.871  23844-24814/org.medicmobile.webapp.mobile I/System.out﹕ [CDS]rx timeout:0
09-03 05:00:14.884  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ LOG | SimpleJsonClient.get()Retrieved JSON: <!DOCTYPE html>
09-03 05:00:14.884  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <html>
09-03 05:00:14.884  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <head>
09-03 05:00:14.884  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <meta name="viewport" content="width=device-width, initial-scale=1">
09-03 05:00:14.884  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <title>Medic Mobile</title>
09-03 05:00:14.885  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <link href="/login/style.css" media="all" rel="stylesheet">
09-03 05:00:14.885  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <link rel="shortcut icon" href="/login/icon_48.ico">
09-03 05:00:14.885  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ </head>
09-03 05:00:14.885  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <body>
09-03 05:00:14.885  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <div class="center">
09-03 05:00:14.885  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <form id="form" action="/medic/login">
09-03 05:00:14.886  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <img class="logo" src="/login/medic-logo-light-full.svg" title="Medic Mobile">
09-03 05:00:14.886  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <input id="redirect" type="hidden" name="redirect" value="/medic/_design/medic/_rewrite/">
09-03 05:00:14.886  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <label for="user">User name</label>
09-03 05:00:14.886  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <input id="user" name="user" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"/>
09-03 05:00:14.886  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <label for="password">Password</label>
09-03 05:00:14.886  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <input id="password" name="password" type="password"/>
09-03 05:00:14.886  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <p class="error incorrect">Incorrect user name or password. Please try again.</p>
09-03 05:00:14.886  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <p class="error unknown">Unexpected error while logging in. Please try again.</p>
09-03 05:00:14.887  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <button id="login" class="btn">Login</button>
09-03 05:00:14.887  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <div class="loader"></div>
09-03 05:00:14.887  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ </form>
09-03 05:00:14.888  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ </div>
09-03 05:00:14.888  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ <script src="/login/script.js"></script>
09-03 05:00:14.888  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ </body>
09-03 05:00:14.888  23844-24814/org.medicmobile.webapp.mobile W/System.err﹕ </html>
```

I think `/medic` is the right path because that matches the string we're shipping and is working in the LG branded app. If you go to `/medic` in the browser you get a 403 which _might_ be interpreted as not found.

**Comment by garethbowen** [comment]
This doesn't solve my exact issue.

**Comment by alxndrsn** [comment]
Confident this should work now.  However, might be worth considering adding a proper endpoint to API for a more reliable check if we're looking at a medic instance - current check:

1. does base URL return valid JSON saying that access is not authorized?
2. does base URL + '/login' return 200?

**Comment by garethbowen** [comment]
It works!

**Comment by alxndrsn** [comment]
And this is good enough?  Or should we have a specific endpoint in API?

**Comment by garethbowen** [comment]
@alxndrsn You could use `/setup/poll` which returns:

```
{
    ready: true,
    handler: 'medic-api',
    version: '0.0.1',
    detail: 'All required services are running normally'
}
```

This would at least tell you you've hit a valid api install. It won't check if you're authorised or not but the login page checks for that when you load it.
