### ISSUE TITLE
Cannot edit non-enketo reports

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1272]
# Steps to reproduce

1. Open a non-Enketo report for editing
2. click `[Submit]`
3. observe that the modal dialog is not dismissed

# Stacktrace

```
TypeError: Cannot read property '_id' of undefined
    at Scope.125.inboxControllers.controller.$scope.updateFacility (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:37585:39)
    at Scope.116.angular.module.controller.$scope.saveReport (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:36597:18)
    at fn (eval at <anonymous> (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:13145:15), <anonymous>:4:221)
    at ngEventDirectives.(anonymous function).compile.element.on.callback (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:23298:17)
    at Scope.$get.Scope.$eval (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:15846:28)
    at Scope.$get.Scope.$apply (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:15945:23)
    at HTMLAnchorElement.<anonymous> (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:23303:23)
    at HTMLAnchorElement.eventHandler (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:3271:21)89.levels.forEach.console.(anonymous function) @ inbox.js:31160(anonymous function) @ dependencies.js:12330$get @ dependencies.js:9109$get.Scope.$apply @ dependencies.js:15947(anonymous function) @ dependencies.js:23303eventHandler @ dependencies.js:3271
```

# Cause

This appears to be because `$scope.selected` is no longer set when editing a non-enketo report.

**Comment by alxndrsn** [comment]
@garethbowen is `selected` still tracked in `$scope`, or should it be derived from `$state`?

**Comment by garethbowen** [comment]
`selected` is still in scope but the scope is now further down the controller hierarchy. I've fixed this by moving the actual update down into the `EditReportCtrl` and passing the doc id in.
