### ISSUE TITLE
[enketo] Cannot create new forms when on Contacts tab unless root node is `<data>`

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1297]
With e.g. [pregnancy form](https://github.com/alxndrsn/enketo-client-side-transformer/blob/master/xforms/pregnancy.xml), trying to _Submit report_ when on the _Contacts_ tab gives the following:

```log
Error: Different root nodes
    at require.9.FormModel.mergeXml (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:62035:19)
    at require.9.FormModel.init (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:61941:26)
    at Form.require.8.define.init (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:59904:51)
    at http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:42336:33
    at processQueue (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:14567:28)
    at http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:14583:27
    at Scope.$get.Scope.$eval (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:15846:28)
    at Scope.$get.Scope.$digest (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:15657:31)
    at http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:15885:26
    at completeOutstandingRequest (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:5394:10)```

**Comment by garethbowen** [comment]
@alxndrsn I can successfully submit a report with that form. I can then successfully edit the report. Do you have any more details?

My best guess at this point is Enketo is trying to merge report data into a form and failing because the data structure is different than expected. Is it possible that you were trying to edit a report with a modified form (or something similar)?

**Comment by alxndrsn** [comment]
Does indeed seem to have been a temporary issue - as you say, probably caused by weird stuff in my DB.

**Comment by alxndrsn** [comment]
This problem is specific to the _Contacts_ tab, and was caused by changes made in #1228

**Comment by alxndrsn** [comment]
This is fixed on the 1260 branch.  It may no longer be relevant on `develop`.

**Comment by garethbowen** [comment]
I think this will still be relevant but in a different place.

**Comment by alxndrsn** [comment]
Ah, I'd better fix it on `develop` later then.

**Comment by garethbowen** [comment]
I've used the code in [this commit](https://github.com/alxndrsn/medic-webapp/commit/109767eed96f3c929b6b18b6f73e381adc1964c8) and added it to the [enketo service](https://github.com/medic/medic-webapp/blob/d5ee001cbdde09cc703fdeff4c0c5f8a47a65215/static/js/services/enketo.js#L85-L92) in develop.
