### ISSUE TITLE
Uploading binary doc attachment fails

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1337]
Uploading an image as an attachment to a document leads to a corrupt image. There is an error in the medic-api log.

```
::ffff:127.0.0.1 - - [28/Sep/2015:02:40:59 +0000] "PUT /medic/doc-gareth-test HTTP/1.1" - - "http://localhost:5988/medic/_design/medic/_rewrite/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0"
Server error: 
  detail: "{\"message\":\"socket hang up\",\"stack\":\"Error: socket hang up\\n    at createHangUpError (_http_client.js:215:15)\\n    at Socket.socketOnEnd (_http_client.js:300:23)\\n    at Socket.emit (events.js:129:20)\\n    at _stream_readable.js:908:16\\n    at process._tickDomainCallback (node.js:381:11)\",\"code\":\"ECONNRESET\"}"

```

**Comment by garethbowen** [comment]
This can be tested by using the icon upload configuration page when #1252 is finished.
