### ISSUE TITLE
medic-api crashes when submitting default language choice

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1349]
Build medic-data using PRELOAD_APP_MARKET=beta then navigate and choose English as default language.

```
127.0.0.1 - - [29/Sep/2015:13:27:12 +0000] "PUT /medic/8a39737d3388a684ac8144e1fc01497a HTTP/1.1" - - "http://localhost:5988/medic/_design/medic/_rewrite/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
UNCAUGHT EXCEPTION!
{ [TypeError: Object #<Object> has no method 'withNano']
  domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [] },
  domainThrown: true }
Server error: 
/medic/8a39737d3388a684ac8144e1fc01497a
  detail: TypeError: Object #<Object> has no method 'withNano'
    at PassThroughExt.endFn [as _endFn] (/Users/mandric/dev/medic-api/audit-proxy.js:62:10)
    at PassThroughExt._flush (/Users/mandric/dev/medic-api/node_modules/pass-stream/lib/pass-stream.js:47:39)
    at PassThroughExt.<anonymous> (/Users/mandric/dev/medic-api/node_modules/pass-stream/node_modules/readable-stream/lib/_stream_transform.js:131:12)
    at PassThroughExt.g (events.js:180:16)
    at PassThroughExt.emit (events.js:117:20)
    at finishMaybe (/Users/mandric/dev/medic-api/node_modules/pass-stream/node_modules/readable-stream/lib/_stream_writable.js:332:12)
    at endWritable (/Users/mandric/dev/medic-api/node_modules/pass-stream/node_modules/readable-stream/lib/_stream_writable.js:339:3)
    at PassThroughExt.Writable.end (/Users/mandric/dev/medic-api/node_modules/pass-stream/node_modules/readable-stream/lib/_stream_writable.js:326:5)
    at IncomingMessage.onend (_stream_readable.js:485:10)
    at IncomingMessage.g (events.js:180:16)
```

**Comment by mandric** [comment]
actually this happens on develop too...

```
127.0.0.1 - - [29/Sep/2015:14:21:44 +0000] "PUT /medic/org.couchdb.user%3Aadmin HTTP/1.1" - - "http://localhost:5988/medic/_design/medic/_rewrite/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
UNCAUGHT EXCEPTION!
{ [TypeError: Object #<Object> has no method 'withNano']
  domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [] },
  domainThrown: true }
Server error: 
  detail: TypeError: Object #<Object> has no method 'withNano'
    at PassThroughExt.endFn [as _endFn] (/Users/mandric/dev/medic-api/audit-proxy.js:63:10)
    at PassThroughExt._flush (/Users/mandric/dev/medic-api/node_modules/pass-stream/lib/pass-stream.js:47:39)
    at PassThroughExt.<anonymous> (/Users/mandric/dev/medic-api/node_modules/pass-stream/node_modules/readable-stream/lib/_stream_transform.js:131:12)
    at PassThroughExt.g (events.js:180:16)
    at PassThroughExt.emit (events.js:117:20)
    at finishMaybe (/Users/mandric/dev/medic-api/node_modules/pass-stream/node_modules/readable-stream/lib/_stream_writable.js:332:12)
    at endWritable (/Users/mandric/dev/medic-api/node_modules/pass-stream/node_modules/readable-stream/lib/_stream_writable.js:339:3)
    at PassThroughExt.Writable.end (/Users/mandric/dev/medic-api/node_modules/pass-stream/node_modules/readable-stream/lib/_stream_writable.js:326:5)
    at IncomingMessage.onend (_stream_readable.js:485:10)
    at IncomingMessage.g (events.js:180:16)
```
![screen shot 2015-09-29 at 11 21 56 am](https://cloud.githubusercontent.com/assets/25641/10166886/82eac696-669c-11e5-9d58-703af4b247ae.png)

**Comment by mandric** [comment]
I missed the `npm install` step here after switching branches.
