### ISSUE TITLE
Add place form never loads

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1431]
On lg.dev as a restricted user go to Contacts > Add Family. The spinner just keeps spinning and this error is logged

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:28:25257
    at i (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:3:30399)
    at https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:3:30571
    at n.a.$get.n.$eval (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:4:6168)
    at n.a.$get.n.$digest (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:4:4599)
    at n.a.$get.n.$apply (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:4:6435)
    at https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:4:13776
    at e (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:2:21064)
    at https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/dependencies.js:2:22493
```

1. Work out why it's not loading - configuration or code?
2. Improve error reporting - stop the spinner and display an error.

**Comment by garethbowen** [comment]
Changes:

1. Moved the promise `catch` one level up so a wider range of errors will be caught and reported
2. Removed race condition by waiting on on the schema promise before continuing with init
3. Patched "different root nodes" issue by generating null instance data if empty object passed in (eg: creating a new contact).

**Comment by alxndrsn** [comment]
Looks good bar a couple of comments on https://github.com/medic/medic-webapp/commit/1b0d99187afe5f1e8558cba563fb0d124354eae8

**Comment by abbyad** [comment]
It is working now, moving to Ready.
