### ISSUE TITLE
[medic-android]  security/permission exception when saving url

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1436]
When trying to save the URL for an unbranded build of the medic-android app I got the following exception in my console and an error message "no database found" on the input field.

Model: SAMSUNG-SGH-1747
Android version: 4.4.2
Kernel version: 3.4.0-1514807
SE for Android status Enforcing SEPF_SAMSUNG-SGH-1747_4.4.2_0032

Stacktrace:

```
I/InputReader(  706): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.9550 ] when=81750216498000
I/InputDispatcher(  706): Delivering touch to: action: 0x4, toolType: 1
I/InputDispatcher(  706): Delivering touch to: action: 0x0, toolType: 1
I/InputReader(  706): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=81750292738000
I/InputDispatcher(  706): Delivering touch to: action: 0x1, toolType: 1
W/ActivityManager(  706): Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
E/DatabaseUtils(  706): Writing exception to parcel
E/DatabaseUtils(  706): java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
E/DatabaseUtils(  706):     at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:15031)
E/DatabaseUtils(  706):     at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:2488)
E/DatabaseUtils(  706):     at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:688)
E/DatabaseUtils(  706):     at android.content.ContentProvider$Transport.call(ContentProvider.java:325)
E/DatabaseUtils(  706):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:275)
E/DatabaseUtils(  706):     at android.os.Binder.execTransact(Binder.java:404)
E/DatabaseUtils(  706):     at dalvik.system.NativeStart.run(Native Method)
```

**Comment by mandric** [comment]
The branded builds seem to work normally though.

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by garethbowen** [comment]
I haven't come across this and nobody has complained in the last 18 months. It could be specific to this phone or android version. As the unbranded app is just for developers at this point I'm going to close this issue and we can reopen if it happens again.
