### ISSUE TITLE
Cannot add or edit persons

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1571]
Using the "Add person" from a family, or the edit button while on a person results in a `error.loading.form`:

```
Error: Different root nodes
    at i.mergeXml (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:41:23363)
    at i.init (https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:41:22523)
...
```

Although the add person form is custom, the edit form is the default form so it doesn't look to be related to configuration.

Tested on build 2347.

**Comment by abbyad** [comment]
Fixed this in the meantime by adding `inputs` to the `data` root node.

```
        <data id="person" version="2015-11-11">
          <inputs>
            <user>
              <facility_id/>
            </user>
          </inputs>
          <person>
```

Leaving open since this resolves the add persons form, but not the root issue.

The fields are not yet populated on the edit form, will open a new issue for that if it is not a configuration issue.

**Comment by abbyad** [comment]
Works well. @garethbowen, you can move to ready once passes Code Review.
