### ISSUE TITLE
Exporting logs doesn't work

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1574]
Go to https://lg.app.medicmobile.org/medic/_design/medic/_rewrite/#/configuration/export and click the Server Logs export.

I get this error on screen:

```
Server error: Log export exited with non-zero status 1
```

And this error in the api log on the server:

```
2015-11-16T00:13:06.106Z - info: 127.0.0.1 - admin [16/Nov/2015:00:13:06 +0000] "GET /api/v1/export/logs?format=zip&locale=en HTTP/1.0" - - "https://lg.app.medicmobile.org/medic/_design/medic/_rewrite/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0"
 
2015-11-16T00:13:06.239Z - error: Server error: 
 
2015-11-16T00:13:06.239Z - info:   detail: Error: Log export exited with non-zero status 1
    at ChildProcess.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/export-data.js:234:27)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
```

**Comment by browndav** [comment]
I've patched this on both lg.app and lg.dev, and it tests out okay now. The issue: our last release of hosted images happened a few days before a log export bug was fixed; the current images are lacking the `sudo` configuration required for the log export to run (among other things). Lots of items for the tech debt list.

**Comment by browndav** [comment]
Verified fixes are in git.
