### ISSUE TITLE
Sentinel: fetch failed, deleted

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1999]
On the LG v0.6 instance, I'm seeing the following messages appear repeatedly in gardener's `medic-sentinel` logs:

```
==> medic_medic_medic-sentinel.log <==
2016-03-02T20:15:42.784Z - error: 2016-03-02T20:15:42.784Z - error: backlog: fetch failed for f622ef6fea94ffbc12f5ea486db12d63 () Error: deleted
    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:1036:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:963:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

2016-03-02T20:15:43.291Z - error: /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                                   ^
Error: Callback was already called.
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/async/lib/async.js:43:36
    at null._onTimeout (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/underscore/underscore.js:768:19)
    at Timer.listOnTimeout (timers.js:110:15)
```

IMO we should look at this and at least patch the bug to avoid log spam, even if it doesn't restore any specific functionality yet.

@mandric: Speculatively assigned to you; let me know if you can't take this on this week.

**Comment by garethbowen** [comment]
The error was due to the callback in async.forEachSeries being called multiple times when a failure occurred. This patch fixes the log spam. I think the error itself is the script behaving as expected and now that it's handled sentinel should startup gracefully.

**Comment by mandric** [comment]
👍
