### ISSUE TITLE
Following an update from build 2468 to 2872, two `medic-api` processes are running

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2000]
When updating a testing clone of `lg.app` from build 2468 to build 2872, `medic-api` appears to be launched a second concurrent time, producing the following repeated log output:

```
==> /srv/storage/gardener/logs/medic_medic_medic-api.log <==
2016-03-02T22:53:56.130Z - error: events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Server.listen (net.js:1240:5)
    at EventEmitter.listen (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/application.js:617:24)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server.js:484:7
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/config.js:103:7
    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/lib/nano.js:217:16)
    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:199:22)
    at Request.emit (events.js:110:17)
```

I've ruled out the possibility that this is an issue with the clone process and/or shell-based process supervision; it only occurs after Garden's `medic-webapp` `Update` button is clicked.

The API itself continues to respond to web requests normally during this period, but migrations do not seem to run. This leads me to believe that the process spewing `EADDRINUSE` messages is the new version of the module, and the process responding to requests from the web is the old version of the module.

I suspect this is a bug in gardener's process supervision, but don't have enough evidence yet to say for sure. I propose that we perform additional analysis during and after this week's field test site update, and then file a more specific issue over at garden20/gardener if needed once we identify the root cause.

**Comment by garethbowen** [comment]
This hasn't happened since. Closing until it happens again.
