### ISSUE TITLE
Exception when requesting changes without a filter param

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2004]
If you request the changes feed without also providing a filter param, api crashes.

```
::1 - - [03/Mar/2016:10:52:41 +0000] "GET /medic/_changes HTTP/1.1" - - "http://localhost:5988/medic/_design/medic/_rewrite/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/48.0.2564.116 Chrome/48.0.2564.116 Safari/537.36"
UNCAUGHT EXCEPTION!
{ [TypeError: Cannot read property 'split' of undefined]
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
Server error: 
  detail: TypeError: Cannot read property 'split' of undefined
    at filterIsDocByPlace (/home/gareth/src/medic/medic-api/handlers/changes.js:7:33)
    at /home/gareth/src/medic/medic-api/handlers/changes.js:25:13
    at /home/gareth/src/medic/medic-api/auth.js:108:7
    at IncomingMessage.<anonymous> (/home/gareth/src/medic/medic-api/auth.js:27:7)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickDomainCallback (node.js:430:17)
```

**Comment by SCdF** [comment]
LGTM
