### ISSUE TITLE
Gardener crashing on startup after a clean reboot

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2068]
The following message appeared in gardener's logs after a clean reboot; I've hand-verified that the proper credentials are supplied to gardener and on to CouchDB:

```
path.js:422
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:422:13)
    at /srv/software/gardener/v1.1.0/lib/processes.js:537:33
    at /srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:124:9)
    at start_forever (/srv/software/gardener/v1.1.0/lib/processes.js:530:11)
    at fn (/srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:641:34)
    at Immediate._onImmediate (/srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

The CouchDB logs only say this:

```
==> /srv/storage/medic-core/couchdb/logs/couch.log <==
[Thu, 10 Mar 2016 23:49:24 GMT] [info] [<0.1989.0>] 127.0.0.1 - - GET / 200
```

This is blocking use of `lg-testing` currently. Figure out what's causing this (look in CouchDB to see if there's any weird truncation or missing files), fix it, and patch anything upstream if a bug is found.

**Comment by browndav** [comment]
Heisenbug is heisenbug. Haven't seen this in a while; closing until we see it again. We'll have a shot at reproducing it as part of #2127.

**Comment by browndav** [comment]
Reopening this, as we've seen it reoccur in other circumstances.

**Comment by garethbowen** [comment]
Closing as ancient as we're moving off Gardener.
