### ISSUE TITLE
.4 analytics page crashes `develop` API

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2352]
Using demo.app's `medic` and `_users` db, with the latest `develop` medic-api, the api will crash when you go to the ANC analytics page. The latest `master` will work though. 
```
UNCAUGHT EXCEPTION!
{ [TypeError: Cannot read property 'patient_id' of undefined]
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
Server error: 
  detail: TypeError: Cannot read property 'patient_id' of undefined
    at /Users/estellecomment/dev/medic/medic-webapp-3/api/controllers/utils.js:86:28
    at /Users/estellecomment/dev/medic/medic-webapp-3/api/node_modules/underscore/underscore.js:182:24
    at Array.filter (native)
    at Function._.filter._.select (/Users/estellecomment/dev/medic/medic-webapp-3/api/node_modules/underscore/underscore.js:172:65)
    at Function._.reject (/Users/estellecomment/dev/medic/medic-webapp-3/api/node_modules/underscore/underscore.js:181:14)
    at uniquePerPatientId (/Users/estellecomment/dev/medic/medic-webapp-3/api/controllers/utils.js:85:12)
    at /Users/estellecomment/dev/medic/medic-webapp-3/api/controllers/utils.js:149:24
    at /Users/estellecomment/dev/medic/medic-webapp-3/api/controllers/utils.js:34:5
    at /Users/estellecomment/dev/medic/medic-webapp-3/api/db.js:71:7
    at Request._callback (/Users/estellecomment/dev/medic/medic-webapp-3/api/node_modules/nano/lib/nano.js:217:16)
undefined
```

**Comment by estellecomment** [comment]
That was before the migrations had run though, so it could be a non-issue. Stay tuned.

**Comment by estellecomment** [comment]
Yup, non-issue
