### ISSUE TITLE
column "xyz" of relation "abc" does not exist when writing report data to database

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2438]
e.g.:

```
error: column "patient_dob" of relation "formview_assessment_2015-11-02" does not exist
    at Connection.parseE (/Users/scdf/Code/Medic/medic-analytics/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/scdf/Code/Medic/medic-analytics/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/scdf/Code/Medic/medic-analytics/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)
```

This only occurs when you import a database in batches. This does *not* mean it's not important: unless you delete everything and regenerate you're always importing in different batches over time.

What it *does* suggest is that it's something to do with forms having different data in them even though the version is the same. This could be for two reasons:
 - The data captured has changed but the version hasn't
 - The way we're defining a field to be stored is not consistent across documents (for example, if a field is empty it's not presented to us)

Either way, if we're going to keep the xml extraction we need to deal with this somehow.

**Comment by SCdF** [comment]
This will be fixed by #2432
