### ISSUE TITLE
Cannot start API – broken migration: extract-user-settings

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2455]
On starting API (on `develop`), it crashes with the following error:

```
Medic API listening on port 5988
DDoc extraction completed successfully
Translations merged successfully
Running migration "extract-user-settings"...
/Users/user/workspaces/medic/api/migrations/extract-user-settings.js:28
        return callback(new Error('Cannot create lowercase username ' + lowercase + ', user already exists.'));
                                                                        ^

ReferenceError: lowercase is not defined
    at /Users/user/workspaces/medic/api/migrations/extract-user-settings.js:28:73
    at Request._callback (/Users/user/workspaces/medic/api/node_modules/nano/lib/nano.js:217:16)
    at Request.self.callback (/Users/user/workspaces/medic/api/node_modules/request/request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/user/workspaces/medic/api/node_modules/request/request.js:1067:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/Users/user/workspaces/medic/api/node_modules/request/request.js:988:12)
    at emitNone (events.js:85:20)
```

This is caused by reference to the non-existent variable `lowercase` at https://github.com/medic/medic-api/blob/develop/migrations/extract-user-settings.js#L28.  Presumably this should actually refer to `lowercaseId`.

**Comment by alxndrsn** [comment]
Potential fix in PR

**Comment by estellecomment** [comment]
Thanks!
