### ISSUE TITLE
Error when starting medic-api on a newly pushed medic-webapp

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2508]
```
Error loading translations - starting up anyway { Error: missing
    at Request._callback (/Users/scdf/Code/Medic/medic-api/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/Users/scdf/Code/Medic/medic-api/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/scdf/Code/Medic/medic-api/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/scdf/Code/Medic/medic-api/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
  name: 'Error',
  error: 'not_found',
  reason: 'missing',
  scope: 'couch',
  statusCode: 404,
  request:
   { method: 'GET',
     headers:
      { 'content-type': 'application/json',
        accept: 'application/json' },
     uri: 'http://XXXXXX:XXXXXX@localhost:5984/medic04/_design/medic-client/_view/doc_by_type',
     qs: { key: '["translations",true]', include_docs: true } },
  headers:
   { date: 'Thu, 14 Jul 2016 09:41:28 GMT',
     'content-type': 'application/json',
     'cache-control': 'must-revalidate',
     statusCode: 404,
     uri: 'http://XXXXXX:XXXXXX@localhost:5984/medic04/_design/medic-client/_view/doc_by_type' },
  errid: 'non_200',
  description: 'couch returned 404' }
```

If I kill `medic-api` and boot it again, I don't get the error.

I can then somehow trigger it showing again (I haven't worked it out, it's not just a `grunt dev`)

@garethbowen is this expected? Asking you because of the translation stuff you moved recently.

**Comment by garethbowen** [comment]
It's probably an ordering bug. `config.load` happens before `translations.run` in `medic-api/server.js` which I think is why you're getting the 404.

**Comment by SCdF** [comment]
Choice
