### ISSUE TITLE
Errors starting sentinel with DB name other than 'medic'

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2513]
I followed the instructions on #2460, with some modifications to keep my old DB:
 - Changed `.kansorc` to point to a `medic04` DB
 - Created said DB in couchdb
 - `npm install && grunt dev` to push our app up
 - Ran api with the correct couch url

On running sentinel against the correct couch url I get the following:
```
scdf at SCdF in ~/Code/Medic/medic-sentinel on master
$ TEST_ENV=1 COUCH_URL=http://admin:pass@localhost:5984/medic04 node server.js
2016-07-18T14:00:33.800Z - info: Error getting last_valid_seq Error: missing
    at Request._callback (/Users/scdf/Code/Medic/medic-sentinel/node_modules/nano/lib/nano.js:234:15)
    at Request.self.callback (/Users/scdf/Code/Medic/medic-sentinel/node_modules/request/request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/scdf/Code/Medic/medic-sentinel/node_modules/request/request.js:1035:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/scdf/Code/Medic/medic-sentinel/node_modules/request/request.js:962:12)
    at emitNone (events.js:91:20)
2016-07-18T14:00:33.801Z - error: Error loading config:  Error: missing
    at Request._callback (/Users/scdf/Code/Medic/medic-sentinel/node_modules/nano/lib/nano.js:234:15)
    at Request.self.callback (/Users/scdf/Code/Medic/medic-sentinel/node_modules/request/request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/scdf/Code/Medic/medic-sentinel/node_modules/request/request.js:1035:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/scdf/Code/Medic/medic-sentinel/node_modules/request/request.js:962:12)
    at emitNone (events.js:91:20)
```

Note this does not happen if I run the same code against my 2.x DB. Unsure if this is a sentinel bug yet or an issue with my environment.

**Comment by SCdF** [comment]
Looks to be a setup thing? I don't have the `_design/kujua-sentinel` DDOC installed for some reason.

**Comment by SCdF** [comment]
It's a bug with sentinel where it only supports the db being called `medic`

**Comment by garethbowen** [comment]
IMO we have hardcoded ddoc names but variable db names. Hardcoded db names are a bug and need to be fixed.

**Comment by garethbowen** [comment]
One example of variable db names is in e2e testing where we create a db called medic-test. Currently e2e testing doesn't start up sentinel but api and webapp seem to work fine.

**Comment by SCdF** [comment]
Quick review for you @mandric
