### ISSUE TITLE
Bad error when not authed for SMS api

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2540]
`$ curl localhost:5988/api/sms`
```
Server error: 
{
  "message": "Cannot read property 'redirect' of undefined",
  "stack": "TypeError: Cannot read property 'redirect' of undefined
    at Object.module.exports.notLoggedIn (\/Users\/user\/workspaces\/medic\/api\/server-utils.js:76:8)
    at Object.module.exports.error (\/Users\/user\/workspaces\/medic\/api\/server-utils.js:46:29)
    at \/Users\/user\/workspaces\/medic\/api\/server.js:199:26
    at \/Users\/user\/workspaces\/medic\/api\/auth.js:98:16
    at \/Users\/user\/workspaces\/medic\/api\/auth.js:81:7
    at Request._callback (\/Users\/user\/workspaces\/medic\/api\/auth.js:19:5)
    at Request.self.callback (\/Users\/user\/workspaces\/medic\/api\/node_modules\/request\/request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (\/Users\/user\/workspaces\/medic\/api\/node_modules\/request\/request.js:1067:10)",
  "domain": {
    "domain": null,
    "_events": {
      
    },
    "_eventsCount": 1,
    "members": [
      
    ]
  },
  "domainThrown": true
}
```

**Comment by alxndrsn** [comment]
This seems to crash API

**Comment by alxndrsn** [comment]
```
TypeError: Cannot read property 'redirect' of undefined
  at Object.module.exports.notLoggedIn (/Users/user/workspaces/medic/api/server-utils.js:76:8)
  at Object.module.exports.error (/Users/user/workspaces/medic/api/server-utils.js:46:29)
  at /Users/user/workspaces/medic/api/server.js:199:26
  at /Users/user/workspaces/medic/api/auth.js:98:16\n at /Users/user/workspaces/medic/api/auth.js:81:7
  at Request._callback (/Users/user/workspaces/medic/api/auth.js:19:5)
  at Request.self.callback (/Users/user/workspaces/medic/api/node_modules/request/request.js:200:22)
  at emitTwo (events.js:100:13)
  at Request.emit (events.js:185:7)
  at Request.<anonymous> (/Users/user/workspaces/medic/api/node_modules/request/request.js:1067:10)
```

**Comment by alxndrsn** [comment]
Fixed :¬)
