### ISSUE TITLE
Document conflict on starting sentinel

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2542]
Steps:
 - Killed sentinel
 - Sent in an invalid form SMS (ie just 'P')
 - Started sentinel again

```
2016-07-22T11:31:25.626Z - error: error saving changes on doc 5601e25b8a333337f168beedb2045eb9 seq 108: {"message":"Document update conflict.","stack":"Error: Document update conflict.
    at Request._callback (/Users/scdf/Code/Medic/medic-sentinel/node_modules/nano/lib/nano.js:234:15)
    at Request.self.callback (/Users/scdf/Code/Medic/medic-sentinel/node_modules/request/request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/scdf/Code/Medic/medic-sentinel/node_modules/request/request.js:1035:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/scdf/Code/Medic/medic-sentinel/node_modules/request/request.js:962:12)
    at emitNone (events.js:91:20)","name":"Error","error":"conflict","reason":"Document update conflict.","scope":"couch","statusCode":409,"request":
    {"method":"POST","headers":{"content-type":"application/json","accept":"application/json"},"uri":"http://admin:pass@localhost:5984/medic04",
    "body": <snip>
    "headers":{"date":"Fri, 22 Jul 2016 11:31:25 GMT","content-type":"application/json","cache-control":"must-revalidate","statusCode":409,"uri":"http://admin:pass@localhost:5984/medic04"},"errid":"non_200","description":"couch returned 409"}
2016-07-22T11:31:38.064Z - info: backlog: processing complete, 0 failures
```

Snipped body is:
```json
{
  "_id": "5601e25b8a333337f168beedb2045eb9",
  "_rev": "2-b248ca3703369c9b073af912beacdcad",
  "type": "data_record",
  "from": "+447765902019",
  "errors": [{
    "code": "sys.facility_not_found",
    "message": "sys.facility_not_found"
  }],
  "tasks": [{
    "messages": [{
      "to": "+447765902019",
      "message": "SMS message received; it will be reviewed shortly. If you were trying to submit a text form, please enter a correct form code and try again.",
      "uuid": "02b4181f-27c4-4c3b-ad08-d5527f178d6d"
    }],
    "state": "pending",
    "state_history": [{
      "state": "pending",
      "timestamp": "2016-07-22T11:31:25.190Z"
    }]
  }],
  "fields": {},
  "reported_date": 1469187052322,
  "sms_message": {
    "message": "I love boglins!",
    "from": "+447765902019",
    "type": "sms_message",
    "form": "I",
    "locale": "en"
  },
  "read": ["admin"],
  "transitions": {
    "default_responses": {
      "last_rev": 3,
      "seq": 108,
      "ok": true
    }
  }
}
```

Current state of the document in the DB is:

```json
{
   "_id": "5601e25b8a333337f168beedb2045eb9",
   "_rev": "3-380724e40954700460989cbbff5b4342",
   "type": "data_record",
   "from": "+447765902019",
   "errors": [
       {
           "code": "sys.facility_not_found",
           "message": "sys.facility_not_found"
       }
   ],
   "tasks": [
       {
           "messages": [
               {
                   "to": "+447765902019",
                   "message": "SMS message received; it will be reviewed shortly. If you were trying to submit a text form, please enter a correct form code and try again.",
                   "uuid": "7c67479d-780f-4166-aaa8-004752d70d55"
               }
           ],
           "state": "pending",
           "state_history": [
               {
                   "state": "pending",
                   "timestamp": "2016-07-22T11:31:25.138Z"
               }
           ]
       }
   ],
   "fields": {
   },
   "reported_date": 1469187052322,
   "sms_message": {
       "message": "I love boglins!",
       "from": "+447765902019",
       "type": "sms_message",
       "form": "I",
       "locale": "en"
   },
   "read": [
       "admin"
   ],
   "transitions": {
       "default_responses": {
           "last_rev": 3,
           "seq": 108,
           "ok": true
       }
   }
}
```

**Comment by SCdF** [comment]
Gonna wait until #2521 is done, it's a large refactor and may potentially fix this

**Comment by SCdF** [comment]
Looks like #2521 fixed this!

**Comment by SCdF** [comment]
Actually looks like #2521 has broken transition functionality, so maybe this isn't actually fixed at all.

**Comment by SCdF** [comment]
Looks like #2521 has fixed this for real!
