### ISSUE TITLE
unit tests are flakey locally

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2543]
Sometimes when I run `grunt karma:unit` all the tests pass.

Sometimes I get the following failures:
```
  UserLanguageModalCtrl controller
    ✓ displays the enabled languages
    ✓ changes language on user selection
    ✓ dismisses the modal on user cancel
    ✓ resets the language on user cancel
    ✓ triggers saving on user submit
    ✗ displays the processing mode modal while saving
	Error: Uncaught AssertionError: expected undefined to equal [ Array(2) ] (node_modules/chai/chai.js:206)

    ✓ displays the processing mode modal while saving
	Error: Uncaught AssertionError: expected undefined to equal [ Array(2) ] (node_modules/chai/chai.js:206)

  ✗ "after each" hook for "displays error when saving error"
	TypeError: Cannot read property '$injector' of null
	    at Function.module.$$cleanup (node_modules/angular-mocks/angular-mocks.js:2890:31)
	    at Context.module.$$afterEach (node_modules/angular-mocks/angular-mocks.js:2885:14)


  UserLanguageModalCtrl controller
    ✗ "before each" hook
	TypeError: Cannot read property 'call' of undefined


Chrome 52.0.2743 (Mac OS X 10.11.5): Executed 51 of 503 (3 FAILED) (1.186 secs / NaN secs)
TOTAL: 3 FAILED, 48 SUCCESS


1) displays the processing mode modal while saving
     UserLanguageModalCtrl controller
     Error: Uncaught AssertionError: expected undefined to equal [ Array(2) ] (node_modules/chai/chai.js:206)

2) "after each" hook for "displays error when saving error"

     TypeError: Cannot read property '$injector' of null
    at Function.module.$$cleanup (node_modules/angular-mocks/angular-mocks.js:2890:31)
    at Context.module.$$afterEach (node_modules/angular-mocks/angular-mocks.js:2885:14)

3) "before each" hook
     UserLanguageModalCtrl controller
     TypeError: Cannot read property 'call' of undefined
```

**Comment by SCdF** [comment]
There is a chance this was entirely my environment being incorrectly configured, but the flakiness is still surprising (you'd think it would either work or not work). Gonna keep this around for a bit and see if I get it again, or close it in a couple of weeks.

**Comment by SCdF** [comment]
Nope, it's a real thing, just got it again, this time for a full `grunt test`. Same tests failing.

**Comment by SCdF** [comment]
It's not just me! This occurred on TravisCI as well: https://travis-ci.org/medic/medic-webapp/jobs/148819836

![image](https://cloud.githubusercontent.com/assets/583851/17289103/10c4ae08-57d0-11e6-8f60-7f792284ce65.png)

**Comment by estellecomment** [comment]
I'm something like this locally, and weird things are happening on Travis too. 
Don't know if it's the same.

**Comment by estellecomment** [comment]
Hmm mine look different : 
```
TOTAL: 9 FAILED, 494 SUCCESS


1) builds admin conversation
     ContactConversation service
     TypeError: Cannot read property 'then' of undefined
    at Context.<anonymous> (tests/karma/unit/services/contact-conversation.js:28:33)

2) builds admin conversation with skip
     ContactConversation service
     TypeError: Cannot read property 'then' of undefined
    at Context.<anonymous> (tests/karma/unit/services/contact-conversation.js:38:44)

3) returns errors from db query
     ContactConversation service
     TypeError: Cannot read property 'then' of undefined
    at Context.<anonymous> (tests/karma/unit/services/contact-conversation.js:46:7)

4) sets ajax timeout
     DB service get function
     AssertionError: expected undefined to equal 'worker'
    at Context.<anonymous> (tests/karma/unit/services/db.js:84:50)

5) returns all clinics when no user district
     Facility service
     TypeError: Cannot read property 'then' of undefined
    at get (static/dist/inbox.js:171308:13)
    at static/dist/inbox.js:54075:13
    at async.forEachOf.async.eachOf (static/dist/inbox.js:53590:13)
    at _parallel (static/dist/inbox.js:54074:9)
    at Object.async.parallel (static/dist/inbox.js:54088:9)
    at static/dist/inbox.js:171332:13
    at Context.<anonymous> (tests/karma/unit/services/facility.js:131:12)

6) creates unfiltered contacts request for no filter
     GenerateSearchRequests service
     AssertionError: expected { Object (view, ordered) } to deeply equal { Object (ordered, view) }
    at Assertion.assertEqual (node_modules/chai/chai.js:774:19)
    at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/chai.js:4192:25)
    at Context.<anonymous> (tests/karma/unit/services/generate-search-requests.js:151:36)

7) builds admin list
     MessageContact service
     TypeError: Cannot read property 'then' of undefined
    at Context.<anonymous> (tests/karma/unit/services/message-contact.js:28:23)

8) returns errors from db query
     MessageContact service
     TypeError: Cannot read property 'then' of undefined
    at Context.<anonymous> (tests/karma/unit/services/message-contact.js:36:7)

9) excludes targets for which the expression fails
     TargetGenerator service
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by garethbowen** [comment]
Deleted the offending test.

**Comment by ngaruko** [comment]
No need to AT this one? Any objection?

**Comment by SCdF** [comment]
@ngaruko correct no need, this is internal dev stuff
