### ISSUE TITLE
extract-person-contacts migration fails

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2586]
On upgrading a clone of demo.app.medicmobile.org to 2.x, migration fails as follows:

```
2016-07-28T15:22:45.218Z - error: Migration "extract-person-contacts" failed with: {"message":"Parent b00cd83d-397e-0e8a-98fb250f42765e4a of facility eeb17d6d-5dde-c2c0-3083f0bd4dd21c39 not found.","stack":"Error: Parent b00cd83d-397e-0e8a-98fb250f42765e4a of facility eeb17d6d-5dde-c2c0-3083f0bd4dd21c39 not found.\n    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/migrations/extract-person-contacts.js:214:27\n    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/lib/nano.js:241:7)\n    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:187:22)\n    at Request.emit (events.js:98:17)\n    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:1044:10)\n    at Request.emit (events.js:95:17)\n    at IncomingMessage.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:965:12)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:943:16\n    at process._tickDomainCallback (node.js:463:13)"}
```

1. it would be nice if the migration could deal nicely with this problem
2. it would be nice if either (a) the server did not come back up if the migrations do not complete successfully, or (b) there is some clearer way to know that migrations failed to complete - this was detected by strange behaviours in webapp, followed by trawling log files.

**Comment by alxndrsn** [comment]
Through Futon, I deleted the `parent` property which was causing trouble.  I now get the following error:

```
2016-07-28T15:47:07.114Z - error: Migration "extract-person-contacts" failed with: {"message":"Failed to update contact on facility eeb17d6d-5dde-c2c0-3df0f0b8987ac49a{\n  \"code\": 400,\n  \"message\": \"Place eeb17d6d-5dde-c2c0-3df0f0b8987ac49a is missing a \\\"parent\\\" property.\"\n}","stack":"Error: Failed to update contact on facility eeb17d6d-5dde-c2c0-3df0f0b8987ac49a{\n  \"code\": 400,\n  \"message\": \"Place eeb17d6d-5dde-c2c0-3df0f0b8987ac49a is missing a \\\"parent\\\" property.\"\n}\n    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/migrations/extract-person-contacts.js:106:27\n    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/places.js:218:7\n    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/lib/async.js:726:13\n    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/lib/async.js:52:16\n    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/lib/async.js:264:21\n    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/lib/async.js:44:16\n    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/lib/async.js:723:17\n    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/lib/async.js:167:37\n    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/places.js:205:18\n    at err (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/places.js:45:12)"}
```

**Comment by alxndrsn** [comment]
This seems to be fixable by adding a `parent` field with value `null` to any facilities which this error is shown for.
So far I have done this for 7 contacts, manually with futon.

**Comment by alxndrsn** [comment]
Having "fixed" all those contacts, I now see the following error:

```2016-07-28T15:59:55.481Z - info: Running migration "extract-person-contacts"...

2016-07-28T15:59:58.053Z - error:

2016-07-28T15:59:58.056Z - error: TypeError: Cannot read property 'type' of null
    at Object.validatePlace [as _validatePlace] (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/places.js:73:48)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/places.js:203:12
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/lib/async.js:718:13
    at iterate (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/lib/async.js:262:13)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/lib/async.js:274:29
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/lib/async.js:44:16
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/lib/async.js:723:17
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/lib/async.js:167:37
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/places.js:187:11
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/people.js:104:7

2016-07-28T15:59:59.720Z - info: DDoc extraction completed successfully

2016-07-28T15:59:59.876Z - info: Medic API listening on port 5988```

**Comment by alxndrsn** [comment]
Oh no, I haven't fixed them all.

**Comment by alxndrsn** [comment]
From the doc linked from #2400:
> Note : upon error, extract-person-contact.js migration can leave data in a broken state : it can lose contacts.
I will work to fix this migration so that it does not break contacts.

**Comment by estellecomment** [comment]
@alxndrsn I went through a similar process for ChristianAid2 : the docs are not always standard-format (we don't have a standard) and some are just broken (e.g referencing unknown parents).

I made it break when it hits problems because I think it's a good time to be fixing the data. I could make it auto-fix, instead of breaking and fixing by hand, but I don't know if the breaks are common, if they're the same in all instances, if they're automatable (some require humans)... So seemed like less trouble.

For fixing the parent fields, I made a premigration script for CA2, that replaces the bad parent _id with the good ones (don't know why parents had changed ids, maybe deleted and recreated...)
https://github.com/medic/medic-projects/blob/master/christian-aid-2/premigration_christianaid2.js

**Comment by alxndrsn** [comment]
> e.g referencing unknown parents

What is correct behaviour in this case?

**Comment by estellecomment** [comment]
Depends. In the CA2 case, the parent was the same as an existing facility, except with a different _id. So I just changed the _id. But if the bad parent has been deleted for instance, then you should remove the parent field altogether. You could try automating the first case, but don't know how easy it would be or how often it would be happening.

**Comment by alxndrsn** [comment]
> You could try automating the first case

I only see one case; what's the second one?

> the parent was the same as an existing facility, except with a different _id

How did you identify that they were the same facility?  Just check for matching names?

**Comment by estellecomment** [comment]
Yes, by matching name.
The second case is where the parent was deleted completely, so you can't find it at all and should replace with null.

**Comment by SCdF** [comment]
@alxndrsn made some notes on the PR, apart from that GTG. I see the ticket is still in active work, not sure what that means in this context

**Comment by alxndrsn** [comment]
@SCdF yeah still a fair bit of work to do on the ticket itself - just wanted to get the test framework merged before getting too deep into specific tests, and fixes for the migration.

**Comment by alxndrsn** [comment]
PRs at https://github.com/medic/medic-api/pull/92 and https://github.com/medic/medic-webapp/pull/2614

**Comment by SCdF** [comment]
@alxndrsn PRs look fine, but the api one has Travis failures that look reasonably important

**Comment by alxndrsn** [comment]
Fixed, will merge.
