### ISSUE TITLE
Cannot create a user in a place without a parent

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2601]
Copying the example from https://github.com/medic/medic-api/blob/master/API_v1.md#get-apiv1users:

```
$ curl -X POST http://admin:pass@localhost:5988/api/v1/users --data '{ "password": "secret", "username": "mary", "type": "district-manager", "place": { "name": "Marys Area", "type": "health_center", "parent": "d14e1c3d557761320b13a77e7806e8f8" }, "contact": { "name": "Mary Anyango", "phone": "+2868917046" } }'
curl -H 'Content-Type: application/json; charset=utf-8' -X POST http://admin:pass@localhost:5988/api/v1/users --data '{ "password": "secret", "username": "mary", "type": "district-manager", "place": { "name": "Marys Area", "type": "health_center", "parent": "d14e1c3d557761320b13a77e7806e8f8" }, "contact": { "name": "Mary Anyango", "phone": "+2868917046" } }'

Failed to find place.
```

Removing the `place.parent` field:

```
$ curl -H 'Content-Type: application/json; charset=utf-8' -X POST http://admin:pass@localhost:5988/api/v1/users --data '{ "password": "secret", "username": "mary", "type": "district-manager", "place": { "name": "Marys Area", "type": "health_center" }, "contact": { "name": "Mary Anyango", "phone": "+2868917046" } }'

Place  is missing a "parent" property.
```

Adding a `null` value for `place.parent`:

```
$ curl -H 'Content-Type: application/json; charset=utf-8' -X POST http://admin:pass@localhost:5988/api/v1/users --data '{ "password": "secret", "username": "mary", "type": "district-manager", "place": { "parent":null, "name": "Marys Area", "type": "health_center" }, "contact": { "name": "Mary Anyango", "phone": "+2868917046" } }'

Server error: {"message":"Can't set headers after they are sent.","stack":"Error: Can't set headers after they are sent.\n    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)\n    at ServerResponse.writeHead (_http_server.js:180:21)\n    at respond (/Users/user/workspaces/medic/api/server-utils.js:23:7)\n    at Object.module.exports.serverError (/Users/user/workspaces/medic/api/server-utils.js:84:5)\n    at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:67:17)\n    at emitOne (events.js:90:13)\n    at Domain.emit (events.js:182:7)\n    at emitError (domain.js:66:24)\n    at Domain.errorHandler [as _errorHandler] (domain.js:126:16)\n    at process._fatalException (node.js:233:33)","domain":{"domain":null,"_events":{},"_eventsCount":1,"members":[]},"domainThrown":true}
```

**Comment by garethbowen** [comment]
Response 1 is correct. Response 3 is covered by #2602. I'm not sure if response 2 is correct or not - the validation was clearly added intentionally. Is this a sensible use case?

**Comment by alxndrsn** [comment]
> Is this a sensible use case?

I think so - how else would you create a program-wide administrator account?

**Comment by mandric** [comment]
A program-wide admin account should use type `national_admin` or `district_admin` no?

**Comment by mandric** [comment]
The minimum hierarchy is 3 levels, `district_admin` does not require a parent, but `health_center` and `clinic` does.

**Comment by nice-snek** [comment]
hi frand @estellecomment, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by estellecomment** [comment]
The example works with a `district_hospital` that doesn't have a parent. 
We expect `health_center`s to have a parent, so that seems like the right behavior to me. 
Closing.
