### ISSUE TITLE
Can crash API with call to /api/v1/users

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2602]
It's possible to crash `medic-api` by POSTING to `/api/v1/users`:

Client:
```
$ curl -H 'Content-Type: application/json; charset=utf-8' -X POST http://admin:pass@localhost:5988/api/v1/users --data '{ "password": "secret", "username": "mary", "type": "district-manager", "place": { "parent":null, "name": "Marys Area", "type": "health_center" }, "contact": { "name": "Mary Anyango", "phone": "+2868917046" } }'

Server error: {"message":"Can't set headers after they are sent.","stack":"Error: Can't set headers after they are sent.\n    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)\n    at ServerResponse.writeHead (_http_server.js:180:21)\n    at respond (/Users/user/workspaces/medic/api/server-utils.js:23:7)\n    at Object.module.exports.serverError (/Users/user/workspaces/medic/api/server-utils.js:84:5)\n    at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:67:17)\n    at emitOne (events.js:90:13)\n    at Domain.emit (events.js:182:7)\n    at emitError (domain.js:66:24)\n    at Domain.errorHandler [as _errorHandler] (domain.js:126:16)\n    at process._fatalException (node.js:233:33)","domain":{"domain":null,"_events":{},"_eventsCount":1,"members":[]},"domainThrown":true}
```

This crashes API with the following message:

```
UNCAUGHT EXCEPTION!
TypeError: Cannot read property 'type' of null
    at Object.validatePlace [as _validatePlace] (/Users/user/workspaces/medic/api/controllers/places.js:76:55)
    at Object.createPlace [as _createPlace] (/Users/user/workspaces/medic/api/controllers/places.js:94:8)
    at Object.createPlaces (/Users/user/workspaces/medic/api/controllers/places.js:146:10)
    at Object.getOrCreatePlace (/Users/user/workspaces/medic/api/controllers/places.js:240:10)
    at createPlace (/Users/user/workspaces/medic/api/controllers/users.js:230:10)
    at fn (/Users/user/workspaces/medic/api/node_modules/async/lib/async.js:746:34)
    at /Users/user/workspaces/medic/api/node_modules/async/lib/async.js:1213:16
    at /Users/user/workspaces/medic/api/node_modules/async/lib/async.js:166:37
    at /Users/user/workspaces/medic/api/node_modules/async/lib/async.js:706:43
    at /Users/user/workspaces/medic/api/node_modules/async/lib/async.js:167:37
Server error:
 { [TypeError: Cannot read property 'type' of null]
  domain:
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
UNCAUGHT EXCEPTION!
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.writeHead (_http_server.js:180:21)
    at respond (/Users/user/workspaces/medic/api/server-utils.js:23:7)
    at Object.module.exports.serverError (/Users/user/workspaces/medic/api/server-utils.js:84:5)
    at Domain.<anonymous> (/Users/user/workspaces/medic/api/server.js:67:17)
    at emitOne (events.js:90:13)
    at Domain.emit (events.js:182:7)
    at emitError (domain.js:66:24)
    at Domain.errorHandler [as _errorHandler] (domain.js:126:16)
    at process._fatalException (node.js:233:33)
Server error:
 { [Error: Can't set headers after they are sent.]
  domain:
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
undefined
```

**Comment by alxndrsn** [comment]
Related to #2601

**Comment by garethbowen** [comment]
### Code review

[Commit 1](https://github.com/medic/medic-api/commit/41decac8ebcb2114f85493708717ea6645fb442c): Server utils is already printing out the error message so we don't need to do this twice
[Commit 2](https://github.com/medic/medic-api/commit/ce2c1d694585b49c041696aac16cfe33581b5065): The response should definitely not contain a stack trace or other information that could expose information about the app when an unexpected error occurs.
[Commit 3](https://github.com/medic/medic-api/commit/3f0c3c9448d23f261a6f33d3eb08c329dc2df828): Fix the issue by broadening the `undefined` check to include `null`
