### ISSUE TITLE
Underscore prefixed fields fail JSON submission to "reports" api

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2605]
@henokgetachew reported getting a 500 when submitting a form using medic-collect.

From the API logs:

```
2016-08-03T22:41:51.602Z - error: Server error: Error: Bad special document member: __version__
    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/node_modules/request/request.js:187:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:107:17)
    at IncomingMessage.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/node_modules/request/request.js:965:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
```

This was found to be caused by the form having a field named `__version__`. This is a couchdb error caused by having a `_` prefixed property at the root of the document.

Firstly all submitted fields should end up in a `fields` property and therefore not at the root of the document so this shouldn't happen. Try to reproduce then fix.

Secondly fix the [API documentation](https://github.com/medic/medic-api/blob/master/API_v1.md#json-properties) which incorrectly states

> ... any properties beginning with _ (underscore) will be ignored.

**Comment by nice-snek** [comment]
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by mandric** [comment]
I think this is a valid bug.

**Comment by garethbowen** [comment]
@wtekeu I've merged the PR, thanks!

I think the key is this was submitted by our android app medic-collect. When you were trying to reproduce the issue did you use medic-collect or in-app xforms?

**Comment by wtekeu** [comment]
I have modified the document xml form attachment and submitted a form using the webapp so I believe this is in-app xforms, right?

**Comment by garethbowen** [comment]
Right. The bug was about filling the form in in [medic-collect](https://play.google.com/store/apps/details?id=org.medicmobile.collect.android.demo)

This is a completely separate app which has a rich UI but submits the forms via SMS instead of HTTP. It's a bit hard to test without actually sending an SMS and having a medic-gateway set up to receive the SMS and forward it on to API via HTTP.

@henokgetachew Is there a simple way to mock medic-collect so we can test this issue without setting up collect and gateway?
