### ISSUE TITLE
Submitting a report with an invalid ref id crashes sentinel

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2636]
When filling in a scheduled form I entered a bogus ref id which resulted in this error:

```
/medic-sentinel/transitions/update_clinics.js:70
                if (clinic.contact && clinic.contact._id) {
                          ^

TypeError: Cannot read property 'contact' of undefined
    at /medic-sentinel/transitions/update_clinics.js:70:27
    at Request._callback (/medic-sentinel/node_modules/nano/lib/nano.js:217:16)
    at Request.self.callback (/medic-sentinel/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/medic-sentinel/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/medic-sentinel/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
```

It looks like we blindly trust the ref id we're given.

**Comment by garethbowen** [comment]
AT: Submit a report with a clinic refid that doesn't match any existing clinic and ensure that sentinel doesn't crash.
