### ISSUE TITLE
disable-erlang-support migration fails if erlang support is already disabled

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2649]
```
Fatal error running database migrations Migration "disable-erlang-support" failed with: {"message":"unknown_config_value","stack":"Error: unknown_config_value\n    at Request._callback (/Users/estellecomment/dev/medic/medic-webapp-1/api/node_modules/nano/lib/nano.js:248:15)\n    at Request.self.callback (/Users/estellecomment/dev/medic/medic-webapp-1/api/node_modules/request/request.js:187:22)\n    at emitTwo (events.js:87:13)\n    at Request.emit (events.js:172:7)\n    at Request.<anonymous> (/Users/estellecomment/dev/medic/medic-webapp-1/api/node_modules/request/request.js:1044:10)\n    at emitOne (events.js:77:13)\n    at Request.emit (events.js:169:7)\n    at IncomingMessage.<anonymous> (/Users/estellecomment/dev/medic/medic-webapp-1/api/node_modules/request/request.js:965:12)\n    at emitNone (events.js:72:20)","name":"Error","error":"not_found","reason":"unknown_config_value","scope":"couch","statusCode":404,"request":{"method":"DELETE","headers":{"content-type":"application/json","accept":"application/json"},"uri":"http://XXXXXX:XXXXXX@localhost:5984/_config/native_query_servers/erlang"},"headers":{"date":"Fri, 19 Aug 2016 09:05:15 GMT","content-type":"application/json","cache-control":"must-revalidate","statusCode":404,"uri":"http://XXXXXX:XXXXXX@localhost:5984/_config/native_query_servers/erlang"},"errid":"non_200","description":"couch returned 404"}
```

**Comment by SCdF** [comment]
LGTM. Not closing because you're still assigned, though I did move it off code review.

**Comment by ngaruko** [comment]
Does this have a way to AT @estellecomment

**Comment by estellecomment** [comment]
@ngaruko 
Yes, run the migration, check that erlang support is disabled, then run the migration again, and check it doesn't crash. 
Step 1 : figure out how to run migrations :)

**Comment by estellecomment** [comment]
@ngaruko 
Yes, run the migration, check that erlang support is disabled, then run the migration again, and check it doesn't crash. 
Step 1 : figure out how to run migrations :)
