### ISSUE TITLE
medic-api integration tests (that run in medic-webapp) are flaky

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2722]
In our continuing series…

![image](http://www.mcdonalds.co.za/sites/default/files/productThumbnail/mcd-food-desserts-ice-cream-cone-flake.png)

So the api integration tests seem flaky. Here is a typical failure:

![image](https://cloud.githubusercontent.com/assets/583851/18354461/9589d714-75dd-11e6-9002-275c14d4b76a.png)

Investigate!

**Comment by SCdF** [comment]
Upped the timeout to 10s: https://github.com/medic/medic-api/commit/daad350ece5d7004f32915cfcea800f95a33cb87

**Comment by SCdF** [comment]
@alxndrsn please review my "code"

**Comment by alxndrsn** [comment]
This https://github.com/medic/medic-webapp/commit/2a828ea39dae1df3fb9d748cd4dac31ecc6cf308 ?

**Comment by SCdF** [comment]
Well, that which causes us to have this: https://github.com/medic/medic-api/commit/daad350ece5d7004f32915cfcea800f95a33cb87

**Comment by estellecomment** [comment]
It's back!

```
Running "exec:test_api_integration" (exec) task
Running "mochaTest:integration" (mochaTest) task
  extract-person-contacts migration
Updating docs: _design/medic-client,appcache
    ✓ should create a new Person from facility.contact (2446ms)
    ✓ should not break if parent of contact not found (289ms)
  remove-empty-parents migration
    1) should not affect well-defined parents
    ✓ should delete parents which are null (8014ms)
    ✓ should delete parents which have no properties (269ms)
  migrations integration test framework
    2) should be able to match docs without a fixed ID
    ✓ should be able to match docs with or without a fixed ID (9914ms)
    ✓ should handle a simple migration (275ms)
    no-op
      ✓ should leave an empty db empty (216ms)
      ✓ should leave a full db full (285ms)
  8 passing (42s)
  2 failing
  1) remove-empty-parents migration should not affect well-defined parents:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
  
  2) migrations integration test framework should be able to match docs without a fixed ID:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
  
Warning: Task "mochaTest:integration" failed. Use --force to continue.
```

**Comment by estellecomment** [comment]
More of these magic conflicts...
```
Running "exec:test_api_integration" (exec) task
Running "mochaTest:integration" (mochaTest) task
  extract-person-contacts migration
Updating docs: _design/medic-client,appcache
    1) should create a new Person from facility.contact
    2) should not break if parent of contact not found
  remove-empty-parents migration
    3) should not affect well-defined parents
    4) should delete parents which are null
    5) should delete parents which have no properties
  migrations integration test framework
    6) should be able to match docs without a fixed ID
    7) should be able to match docs with or without a fixed ID
Updating docs: _design/medic-client
    8) should handle a simple migration
    9) should handle a simple migration
    no-op
  0 passing (11s)
  9 failing
  1) extract-person-contacts migration should create a new Person from facility.contact:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
  
  2) extract-person-contacts migration should not break if parent of contact not found:
     Failed to delete parent on facility abc - {
  "message": "Document update conflict.",
  "stack": "Error: Document update conflict.\n  at Request._callback (/home/travis/build/medic/medic-webapp/api/node_modules/nano/lib/nano.js:248:15)\n  at Request.self.callback (/home/travis/build/medic/medic-webapp/api/node_modules/request/request.js:187:22)\n  at emitTwo (events.js:106:13)\n  at Request.emit (events.js:191:7)\n  at Request.<anonymous> (/home/travis/build/medic/medic-webapp/api/node_modules/request/request.js:1048:10)\n  at emitOne (events.js:96:13)\n  at Request.emit (events.js:188:7)\n  at IncomingMessage.<anonymous> (/home/travis/build/medic/medic-webapp/api/node_modules/request/request.js:969:12)\n  at emitNone (events.js:91:20)\n  at IncomingMessage.emit (events.js:185:7)\n  at endReadableNT (_stream_readable.js:975:12)\n  at _combinedTickCallback (internal/process/next_tick.js:74:11)\n  at process._tickDomainCallback (internal/process/next_tick.js:122:9)\n",
  "name": "Error",
  "error": "conflict",
  "reason": "Document update conflict.",
  "scope": "couch",
  "statusCode": 409,
  "request": {
    "method": "POST",
    "headers": {
      "content-type": "application/json",
      "accept": "application/json"
    },
    "uri": "http://XXXXXX:XXXXXX@localhost:5984/medic_api_integration_tests__medic",
    "body": "{\"_id\":\"abc\",\"_rev\":\"1-b3f381bd143fb6c6eaef0365cf178002\",\"type\":\"health_center\",\"name\":\"Homa Bay Health\"}"
  },
  "headers": {
    "date": "Fri, 30 Sep 2016 13:09:24 GMT",
    "content-type": "application/json",
    "cache-control": "must-revalidate",
    "statusCode": 409,
    "uri": "http://XXXXXX:XXXXXX@localhost:5984/medic_api_integration_tests__medic"
  },
  "errid": "non_200",
  "description": "couch returned 409"
}
  Error: Failed to delete parent on facility abc - {
    "message": "Document update conflict.",
    "name": "Error",
    "error": "conflict",
    "reason": "Document update conflict.",
    "scope": "couch",
    "statusCode": 409,
    "request": {
      "method": "POST",
      "headers": {
        "content-type": "application/json",
        "accept": "application/json"
      },
      "uri": "http://XXXXXX:XXXXXX@localhost:5984/medic_api_integration_tests__medic",
      "body": "{\"_id\":\"abc\",\"_rev\":\"1-b3f381bd143fb6c6eaef0365cf178002\",\"type\":\"health_center\",\"name\":\"Homa Bay Health\"}"
    },
    "headers": {
      "date": "Fri, 30 Sep 2016 13:09:24 GMT",
      "content-type": "application/json",
      "cache-control": "must-revalidate",
      "statusCode": 409,
      "uri": "http://XXXXXX:XXXXXX@localhost:5984/medic_api_integration_tests__medic"
    },
    "errid": "non_200",
    "description": "couch returned 409"
  }
    at migrations/extract-person-contacts.js:238:25
    at Request._callback (node_modules/nano/lib/nano.js:241:7)
    at Request.self.callback (node_modules/request/request.js:187:22)
    at Request.<anonymous> (node_modules/request/request.js:1048:10)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  
  3) remove-empty-parents migration should not affect well-defined parents:
     Uncaught Error: Database contents not as expected: 
	Expected doc not found in the db: {"_id":"abc","type":"district_hospital","name":"myfacility","contact":{"_id":{},"_rev":{},"type":"person","name":"Alice","phone":"+123","reported_date":{},"parent":{"_id":"abc","_rev":{},"type":"district_hospital","name":"myfacility"}}};
	Expected doc not found in the db: {"name":"Alice","type":"person","phone":"+123","reported_date":{},"parent":{"_id":"abc","_rev":{},"type":"district_hospital","name":"myfacility"}}
    at matchDbs (tests/integration/migrations/utils.js:119:11)
    at tests/integration/migrations/utils.js:70:7
    at Request._callback (node_modules/nano/lib/nano.js:217:16)
    at Request.self.callback (node_modules/request/request.js:187:22)
    at Request.<anonymous> (node_modules/request/request.js:1048:10)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  
  4) remove-empty-parents migration should delete parents which are null:
     Error: The database could not be created, the file already exists.
    at Request._callback (node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (node_modules/request/request.js:187:22)
    at Request.<anonymous> (node_modules/request/request.js:1048:10)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  
  5) remove-empty-parents migration should delete parents which have no properties:
     Error: missing
    at Request._callback (node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (node_modules/request/request.js:187:22)
    at Request.<anonymous> (node_modules/request/request.js:1048:10)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  
  6) migrations integration test framework should be able to match docs without a fixed ID:
     Error: Document update conflict.
    at Request._callback (node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (node_modules/request/request.js:187:22)
    at Request.<anonymous> (node_modules/request/request.js:1048:10)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  
  7) migrations integration test framework should be able to match docs with or without a fixed ID:
     Error: The database could not be created, the file already exists.
    at Request._callback (node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (node_modules/request/request.js:187:22)
    at Request.<anonymous> (node_modules/request/request.js:1048:10)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  
  8) migrations integration test framework should handle a simple migration:
     Error: no_db_file
    at Request._callback (node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (node_modules/request/request.js:187:22)
    at Request.<anonymous> (node_modules/request/request.js:1048:10)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  
  9) migrations integration test framework should handle a simple migration:
     Error: no_db_file
    at Request._callback (node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (node_modules/request/request.js:187:22)
    at Request.<anonymous> (node_modules/request/request.js:1048:10)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  
Warning: Task "mochaTest:integration" failed. Use --force to continue.
Aborted due to warnings.
>> Exited with code: 3.
>> Error executing child process: Error: Command failed: cd api && grunt test_integration
Warning: Task "exec:test_api_integration" failed. Use --force to continue.
Aborted due to warnings.
```

**Comment by SCdF** [comment]
@alxndrsn interested in your take on this, the first (ie only valid) issue looks to be the conflicts you were talking about awhile ago. I can look into it if you don't have time, but it sounds like you probably know what's going on here.

**Comment by alxndrsn** [comment]
I suspect the conflicts are caused by the first test timing out, and then after that the cleanup isn't being handled properly.  Which makes all the subsequent tests fail.

**Comment by estellecomment** [comment]
```
Running "exec:test_api_integration" (exec) task
Running "mochaTest:integration" (mochaTest) task
  extract-person-contacts migration
Updating docs: _design/medic-client,appcache
    ✓ should create a new Person from facility.contact (640ms)
    ✓ should not break if parent of contact not found (273ms)
  remove-empty-parents migration
    ✓ should not affect well-defined parents (310ms)
    ✓ should delete parents which are null (197ms)
    1) should delete parents which have no properties
  migrations integration test framework
    ✓ should be able to match docs without a fixed ID (8778ms)
    ✓ should be able to match docs with or without a fixed ID (464ms)
    ✓ should handle a simple migration (505ms)
    no-op
      ✓ should leave an empty db empty (5141ms)
      ✓ should leave a full db full (348ms)
  9 passing (27s)
  1 failing
  1) remove-empty-parents migration should delete parents which have no properties:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
  
Warning: Task "mochaTest:integration" failed. Use --force to continue.
```

**Comment by SCdF** [comment]
I'm going to close this… I haven't seen anything like this for awhile, I think we fixed it / travis got faster computers / something.
