### ISSUE TITLE
couch2pg not sync'ing all records

### ISSUE THREAD

**Issue by michaelkohn** [medic/medic-webapp#2773]
Have an issue where the number of records in the medic database in Couch does not match the number of records in the couchdb table in PostgreSQL though the 'Update seq' in Couch matches the 'couchdb_progress.seq' value in PostgreSQL.

There have been a number of timeout errors which may have contributed

Error: ETIMEDOUT
    at null._onTimeout (/var/adapter/{redacted}/medic-analytics/node_modules/pouchdb/node_modules/request/request.js:772:15)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

And also a situation where the connection was terminated

events.js:72
        throw er; // Unhandled 'error' event
              ^
error: terminating connection due to administrator command
    at Connection.parseE (/var/adapter/{redacted}/medic-analytics/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/var/adapter/{redacted}/medic-analytics/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/var/adapter/{redacted}/medic-analytics/node_modules/pg/lib/connection.js:105:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)

(cc: @SCdF @Enock1990 @ngamita @derickl)

Attached screenshot shows seq off by one but record count off by almost 1,500.  I've also seen it where the seq match exactly but the record counts are still off.

It would be helpful to get a list of UUID's and timestamps from the medic DB in Couch to compare to couchdb in PostgreSQL to see which ones are missing and look to see if they correlate with the time any of the execution problems we've seen with the adapter.

<img width="1213" alt="screen shot 2016-09-21 at 9 55 25 pm" src="https://cloud.githubusercontent.com/assets/10096985/18735330/b621a154-809c-11e6-9c9a-0a159b05ae84.png">

**Comment by SCdF** [comment]
Chucking this in the sprint because, depending on what documents its missing, it could be breaking important functionality.

**Comment by SCdF** [comment]
OK, so without logs there isn't really much we can do about this one.

@michaelkohn: here are my suggestions:
 - For now, if you reset the seq value in pgsql to 0, it will resync from the beginning
 - Couch2PG should not be run from tmux. It should be run from a service. There are instructions on how to install it as an upstart service (which is the easiest way to get it running on our existing pgsql server) in the readme.
 - If you can't run it as a service you should be redirecting its output into a log file: i.e. `nodejs whatever.js >> /var/log/couch2pg.log`. Note `>>` instead of `>`, as >> appends as opposed to overwriting

In the future if this happens again (and I'm sure it will) there will hopefully be useful things in the logs.

**Comment by browndav** [comment]
I suspect we should provide some support re: setting things up to run from upstart.
