### ISSUE TITLE
Flaky unit test : ReportsCtrl

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2798]
We may be cleaning it up too fast or something. This happened locally.

```
  ReportsCtrl controller
    ✓ set up controller
    ✓ verifies the given report
    ✓ when selecting a report, it sets the phone number in the actionbar
  ✗ "after each" hook
	Error: Uncaught AssertionError: expected 0 to equal 1 (node_modules/chai/chai.js:206)

  ✗ "after each" hook
	TypeError: Cannot read property '$injector' of null
	    at Function.module.$$cleanup (node_modules/angular-mocks/angular-mocks.js:2897:31)
	    at Context.module.$$afterEach (node_modules/angular-mocks/angular-mocks.js:2892:14)

  ✗ "after each" hook for "loads form when task has one action and no fields"
	TypeError: Cannot read property '$injector' of null
	    at Function.module.$$cleanup (node_modules/angular-mocks/angular-mocks.js:2897:31)
	    at Context.module.$$afterEach (node_modules/angular-mocks/angular-mocks.js:2892:14)

  ✗ "before each" hook
	TypeError: Cannot read property 'currentRetry' of undefined


Chrome 53.0.2785 (Mac OS X 10.10.5): Executed 78 of 566 (4 FAILED) (6.943 secs / 1.442 secs)
TOTAL: 4 FAILED, 74 SUCCESS


1) "after each" hook
     
     Error: Uncaught AssertionError: expected 0 to equal 1 (node_modules/chai/chai.js:206)

2) "after each" hook
     
     TypeError: Cannot read property '$injector' of null
    at Function.module.$$cleanup (node_modules/angular-mocks/angular-mocks.js:2897:31)
    at Context.module.$$afterEach (node_modules/angular-mocks/angular-mocks.js:2892:14)

3) "after each" hook for "loads form when task has one action and no fields"
     
     TypeError: Cannot read property '$injector' of null
    at Function.module.$$cleanup (node_modules/angular-mocks/angular-mocks.js:2897:31)
    at Context.module.$$afterEach (node_modules/angular-mocks/angular-mocks.js:2892:14)

4) "before each" hook
     
     TypeError: Cannot read property 'currentRetry' of undefined

```

**Comment by SCdF** [comment]
@estellecomment have you seen this on travis?

**Comment by estellecomment** [comment]
Yeah, i think the first time i saw it was on Travis. I'll update this if I see it again.

**Comment by garethbowen** [comment]
Also the TasksContentCtrl...

```
  TasksContentCtrl
    ✓ loads form when task has one action and no fields
    ✓ does not load form when task has more than one action
  ✗ "after each" hook
	AssertionError: expected 0 to equal 1 (:0)
  TasksContentCtrl
    ✗ "before each" hook: workFn
	fn is undefined
```

https://travis-ci.org/medic/medic-webapp/jobs/169339791

**Comment by garethbowen** [comment]
The reports one was just plain broken - the setTimeout was running after the test completed because it wasn't using the done function. When I fixed that it was failing on a real error.

I made an attempt at the Tasks ones but I'm not confident I got to the bottom of those.

**Comment by garethbowen** [comment]
Closed by accident.

**Comment by estellecomment** [comment]
LGTM, thanks!
I'm closing this, we'll reopen if it shows up again...
