### ISSUE TITLE
Error when completing a task on demo.dev.medicmobile.org

### ISSUE THREAD

**Issue by derickl** [medic/medic-webapp#2851]
On the final step, clicking on submit shows the following error page.

![screen shot 2016-10-24 at 14 41 13](https://cloud.githubusercontent.com/assets/83162/19644370/f525dfa4-99f7-11e6-90ab-0245448c9622.png)

Here is the associated console log:

```
inbox.js:9 Error getting tasks TypeError: Cannot set property 'areTasksEnabled' of null
    at https://demo.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:60:24465
    at https://demo.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:66:4863
    at https://demo.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:65:21843
    at Array.forEach (native)
    at x (https://demo.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:65:21823)
    at constructor.<anonymous> (https://demo.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:65:21912)
    at constructor.d.emit (https://demo.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:29:29436)
    at d (https://demo.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:30:3980)
    at https://demo.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:30:4393
    at emitTask (eval at s (https://demo.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:1:1), <anonymous>:5:2752)
```

**Comment by abbyad** [comment]
We have seen this error often during our internal training session.

The config includes permissions for `can_view_tasks` and `can_view_tasks_tab`. We should open corresponding issue in `medic-webapp`.

**Comment by garethbowen** [comment]
PR: https://github.com/medic/medic-webapp/pull/2858

**Comment by SCdF** [comment]
Choice!
