### ISSUE TITLE
Sentinel looking for non-existent view

### ISSUE THREAD

**Issue by derickl** [medic/medic-webapp#3098]
Here's a log extract on an instance running `2.8.5`

```
2017-02-02T13:17:20.943Z - error: 2017-02-02T13:17:20.942Z - error: error saving changes on doc 8DD09F67-D06B-3783-9F32-D579FB8CA09A seq 138239: {"message":"missing_named_view","stack":"Error: missing_named_view\n    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/nano/lib/nano.js:248:15)\n    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:186:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:1081:10)\n    at Request.emit (events.js:107:17)\n    at IncomingMessage.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:1001:12)\n    at IncomingMessage.g (events.js:199:16)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16","name":"Error","error":"not_found","reason":"missing_named_view","scope":"couch","statusCode":404,"request":{"method":"POST","headers":{"content-type":"application/json","accept":"application/json"},"uri":"http://XXXXXX:XXXXXX@localhost:5984/medic/_design/medic/_view/audit_records_by_doc","qs":{"include_docs":true},"body":"{\"keys\":[[\"8DD09F67-D06B-3783-9F32-D579FB8CA09A\"]]}"},"headers":{"date":"Thu, 02 Feb 2017 13:17:20 GMT","content-type":"application/json","cache-control":"must-revalidate","statusCode":404,"uri":"http://XXXXXX:XXXXXX@localhost:5984/medic/_design/medic/_view/audit_records_by_doc"},"errid":"non_200","description":"couch returned 404"}
```

cc @SCdF

**Comment by SCdF** [comment]
This was fixed in this commit: https://github.com/medic/medic-sentinel/commit/622d55f24dfde27aa53d6ff22686e0dc9d253793, and was released in 2.9.0 of medic-webapp. There is no 2.8.x release that contains this fix currently.
