### ISSUE TITLE
Uncaught exception triggers 500 response for subsequent requests

### ISSUE THREAD

**Issue by derickl** [medic/medic-webapp#3099]
Here is a log excerpt from an instance running `2.8.5`

```
2017-02-02T12:57:50.786Z - info: 127.0.0.1 - - [02/Feb/2017:12:57:50 +0000] "GET /medic/ HTTP/1.0" - - "https://*********.medicmobile.org/medic/_design/medic/_rewrite/" "Mozilla/5.0 (Linux; Android 5.1

2017-02-02T12:58:11.326Z - info: 127.0.0.1 - - [02/Feb/2017:12:58:11 +0000] "POST /medic/_changes?style=all_docs&feed=longpoll&heartbeat=10000&filter=_doc_ids&since=365104&limit=100 HTTP/1.0" - - "https:/

2017-02-02T12:59:27.540Z - error: UNCAUGHT EXCEPTION!

2017-02-02T12:59:27.542Z - error: TypeError: Cannot read property 'filter' of undefined
    at prepareResponse (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/handlers/changes.js:136:36)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/handlers/changes.js:168:7
    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/lib/nano.js:217:16)
    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:186:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:1081:10)
    at Request.emit (events.js:107:17)
    at IncomingMessage.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:1001:
    at IncomingMessage.g (events.js:199:16)
    at IncomingMessage.emit (events.js:129:20)

2017-02-02T12:59:27.544Z - error: Server error: { [TypeError: Cannot read property 'filter' of undefined]
  domain:
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }

2017-02-02T12:59:27.546Z - error: UNCAUGHT EXCEPTION!

2017-02-02T12:59:27.551Z - error: Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.res.writeHead (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server.js:509:9)
    at Object.module.exports.serverError (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server-utils.js:35:9)
    at Domain.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server.js:66:17)
    at Domain.emit (events.js:107:17)
```

cc @SCdF

**Comment by SCdF** [comment]
The offending code is [in master](https://github.com/medic/medic-api/blob/master/handlers/changes.js#L142-L148) and [in 2.8.5](https://github.com/medic/medic-api/blob/2a9ffbd/handlers/changes.js#L134:L140):
```js
var prepareResponse = function(feed, changes) {
  // filter out records the user isn't allowed to see
  changes.results = changes.results.filter(function(change) {
    return change.deleted || _.contains(feed.validatedIds, change.id);
  });
  feed.res.write(JSON.stringify(changes));
};
```

It is surprising to me that `results` could ever be empty since both versions don't call `prepareResponse` if there is an error. It may just be that if there are no results for some reason it doesn't return an empty array for results.

**Comment by SCdF** [comment]
@derickl can you advice as to the severity of this? Would you want a 2.8.6 released to address this issue, or are you happy waiting until the next main release (likely 2.10)?

**Comment by SCdF** [comment]
@derickl can I get some more information on this one please? Can you explain what is happening in more detail:
 - Do you see this exception sometimes, or all the time?
 - Are you doing something to trigger the exception (eg are you hitting a url?)
 - Are there are any other issues on the server?
 - Does this cause notable problems in the app functioning, or is it just a weird exception you get sometimes?

**Dev detail**: this is weird, I don't know how you'd get into a situation where you have no error but also no results array. Curling for the most current change or an non-existent change in the future still gets you an empty results array. We could just put a check here, but I wonder if this is indicative of something worse going on that we should be fixing.

**Comment by derickl** [comment]
@SCdF 2.8.6 would be appreciated to resolve this. Might be a couple of weeks before LG is trained (and migrated) on 2.9+ .

In terms of details as to the event: I just saw the 500 on #downtime, logged in to the instance, tailed the logs and that particular expert was recurring quite often.

**Comment by SCdF** [comment]
@derickl did you try restarting api? There is no reason that I can see that this would be happening based on reading the code, and I'd rather not just blindly put a check in there so it doesn't crash, because it could be hiding a larger problem. Also, which server is this?

**Comment by derickl** [comment]
@SCdF restarting medic-core resolved the 500. 

`lg.app`

**Comment by SCdF** [comment]
@garethbowen would like your opinion on this. I added the commit above to `master`, we could cherrypick that into a 2.8.6 but I mean, I'm not sure what it will show us. If @derickl restarted api and everything started working again I'm wondering it was a weird couchdb state or something?

**Comment by garethbowen** [comment]
@SCdF It's about all we can do... maybe add server side logging? As far as I can tell this is shouldn't happen, and I worry it might cause a client to stop syncing, but there's no point crashing the service.

I don't think it needs backporting unless we find it happening again. @derickl Have you caught this happening again?

**Comment by SCdF** [comment]
@garethbowen so FWIW the change I made will crash the service, and the 503 will be logged. Should we instead change it to logging an error specifically, but then continuing on with the request (ie treat it as if there were an empty `results` array)?

**Comment by garethbowen** [comment]
@SCdF Really? I thought by bypassing the `prepareResponse` call you were bypassing the code that threw the uncaught exception. The way I read this is it'll just write the response and continue on.

**Comment by SCdF** [comment]
@garethbowen right yeah totally. The response though, is a 503. So it's "crashing" in the sense that it's not returning a 200.

**Comment by SCdF** [comment]
OK @derickl I'm going to close this now. We've added logging that will filter down into later releases. If you've been finding this happening a lot less us know and we can spin off a release just with this logging in it.

**Comment by derickl** [comment]
@garethbowen I personally haven't caught it before. Maybe someone else has in the past.

@SCdF I'll keep an eye out for it and reach out in case it recurs.

Thanks guys.
