### ISSUE TITLE
Medic OS: Services sometimes don't terminate properly after upgrade

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#3191]
I'm occasionally seeing duplicate service processes following a full system upgrade. For CouchDB, this looks something like this:

```
[Fri, 03 Mar 2017 02:45:29 GMT] [error] [<0.247.0>] {error_report,<0.31.0>,
                     {<0.247.0>,crash_report,
                      [[{initial_call,
                         {couch_index_updater,init,['Argument__1']}},
                        {pid,<0.247.0>},
                        {registered_name,[]},
                        {error_info,
                         {exit,unknown_info,
                          [{gen_server,terminate,7,
                            [{file,"gen_server.erl"},{line,804}]},
                           {proc_lib,init_p_do_apply,3,
                            [{file,"proc_lib.erl"},{line,237}]}]}},
                        {ancestors,[<0.243.0>,<0.242.0>]},
                        {messages,[]},
                        {links,[]},
                        {dictionary,[]},
                        {trap_exit,true},
                        {status,running},
                        {heap_size,376},
                        {stack_size,27},
                        {reductions,153}],
                       []]}}
```

A post-upgrade reboot appears to make the problem go away. This shouldn't happen. Figure out why it's happening and fix it.

**Comment by browndav** [comment]
Quick note: this recovers after a reboot, and may not be critical to fix right now. Do some more upgrades, and wait and see.

**Comment by browndav** [comment]
We're also seeing something similar with Gardener that _should_ be fixed by https://github.com/medic/medic-os/commit/2f7cc51eb8805a838543bd0ad34e29ff8f1d4f7c:

```
2017-03-22T15:14:56.746Z - error: events.js:85                                                                                                                                                                      
      throw er; // Unhandled 'error' event                                                                                                                                                                          
            ^                                                                                                                                                                                                       
Error: listen EADDRINUSE                                                                                                                                                                                            
    at exports._errnoException (util.js:746:11)                                                                                                                                                                     
    at Server._listen2 (net.js:1129:14)                                                                                                                                                                             
    at listen (net.js:1155:10)                                                                                                                                                                                      
    at Server.listen (net.js:1240:5)                                                                                                                                                                                
    at EventEmitter.listen (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/application.js:618:24)      
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server.js:335:7                                                           
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/config.js:26:7                                                            
    at IncomingMessage.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/felix-couchdb/lib/couchdb.js:242
    at IncomingMessage.emit (events.js:129:20)                                                                                                                                                                      
    at _stream_readable.js:908:16              
```

**Comment by browndav** [comment]
This duplicates #3274; code review being done there. Closing.
