### ISSUE TITLE
Cannot start API with couch 2

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3225]
Looks like the `extract-user-settings` migration is looking for the `_users` db, which doesn't exist on couchdb2.

```Fatal error initialising medic-api Migration "extract-user-settings" failed with: {"message":"Database does not exist.","stack":"Error: Database does not exist.
    at Request._callback (/Users/user/workspaces/medic/api/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/Users/user/workspaces/medic/api/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (/Users/user/workspaces/medic/api/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
    at IncomingMessage.<anonymous> (/Users/user/workspaces/medic/api/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)","name":"Error","error":"not_found","reason":"Database does not exist.","scope":"couch","statusCode":404,"request":{"method":"GET","headers":{"content-type":"application/json","accept":"application/json"},"uri":"http://XXXXXX:XXXXXX@localhost:5984/_users/_all_docs","qs":{"include_docs":true}},"headers":{"cache-control":"must-revalidate","connection":"close","content-type":"application/json","date":"Tue, 14 Mar 2017 02:15:03 GMT","x-couch-request-id":"8c6e78a365","x-couchdb-body-time":"0","statusCode":404,"uri":"http://XXXXXX:XXXXXX@localhost:5984/_users/_all_docs"},"errid":"non_200","description":"couch returned 404"}```

**Comment by SCdF** [comment]
@alxndrsn what makes you think the `_users` DB doesn't exist in CouchDB 2.0?

I have it in mine:
![image](https://cloud.githubusercontent.com/assets/583851/23892642/5dc78120-0893-11e7-8757-8250c70f8817.png)
Though I admit I may have migrated it over manually (I don't remember).
I can't find in the 2.0 documentation or in any migration documentation that `_users` is no longer used? Where are username and password credentials stored now?

**Comment by SCdF** [comment]
@alxndrsn https://groups.google.com/forum/#!topic/couchdb-user-archive/oWMbIAYs8wI

Looks like you have to setup CouchDB 2.0 "properly" for `_users` to be created. I'm going to close this, feel free to reopen if I made a mistake.

**Comment by alxndrsn** [comment]
> what makes you think the _users DB doesn't exist in CouchDB 2.0?

The error message quoted in the OP: `Database does not exist.`

I'll take a look at the link, thanks.
