### ISSUE TITLE
API does not check if COUCH_NODE_NAME is set at startup

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3226]
If you forget to set the `COUCH_NODE_NAME` env var, the following cryptic error is received:
```
Fatal error initialising medic-api Migration "enable-erlang-support" failed with: {"message":"undefined is down","stack":"Error: undefined is down
    at Request._callback (/Users/user/workspaces/medic/api/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/Users/user/workspaces/medic/api/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (/Users/user/workspaces/medic/api/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
    at IncomingMessage.<anonymous> (/Users/user/workspaces/medic/api/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)","name":"Error","error":"nodedown","reason":"undefined is down","scope":"couch","statusCode":412,"request":{"method":"PUT","headers":{"content-type":"application/json","accept":"application/json"},"uri":"http://XXXXXX:XXXXXX@localhost:5984/_node/undefined/_config/native_query_servers/erlang","body":"\"{couch_native_process, start_link, []}\""},"headers":{"cache-control":"must-revalidate","connection":"close","content-type":"application/json","date":"Tue, 14 Mar 2017 02:24:32 GMT","x-couch-request-id":"68a1de6686","x-couchdb-body-time":"0","statusCode":412,"uri":"http://XXXXXX:XXXXXX@localhost:5984/_node/undefined/_config/native_query_servers/erlang"},"errid":"non_200","description":"couch returned 412"}
```
...and `medic-api` fails to start.

**Comment by SCdF** [comment]
@alxndrsn can we default it? On local / single installs it should be the same everywhere I believe

**Comment by SCdF** [comment]
(putting this in the sprint because it sounds like it would break standard 2.x deploys)

**Comment by SCdF** [comment]
So this is certainly one downside of squashing. Looks like the commit that added this is actually `c8c0654a0339cf05a14ed4e2a020f81b9e189eb5`, which no longer exists on GitHub because it got squashed away:
```
$ git show c8c0654a0339cf05a14ed4e2a020f81b9e189eb5
commit c8c0654a0339cf05a14ed4e2a020f81b9e189eb5
Author: Alex Anderson <anderson@medicmobile.org>
Date:   Wed Nov 30 16:11:28 2016 +0100

    Use COUCH_NODE_NAME env var instead of hard-coded couch node name

    Issue: medic/medic-webapp#2933

diff --git a/migrations/disable-erlang-support.js b/migrations/disable-erlang-support.js
index 83dd592..aa7d0d4 100644
--- a/migrations/disable-erlang-support.js
+++ b/migrations/disable-erlang-support.js
@@ -7,7 +7,7 @@ module.exports = {
     db.request({
       db: '_node',
       method: 'DELETE',
-      path: 'couchdb@localhost/_config/native_query_servers/erlang',
+      path: process.env.COUCH_NODE_NAME + '/_config/native_query_servers/erlang',
     }, function(err) {
       if (err && err.error === 'not_found') {
         console.log('Erlang support is already disabled.');
diff --git a/migrations/enable-erlang-support.js b/migrations/enable-erlang-support.js
index 820696e..91d81df 100644
--- a/migrations/enable-erlang-support.js
+++ b/migrations/enable-erlang-support.js
@@ -7,7 +7,7 @@ module.exports = {
     db.request({
       db: '_node',
       method: 'PUT',
-      path: 'couchdb@localhost/_config/native_query_servers/erlang',
+      path: process.env.COUCH_NODE_NAME + '/_config/native_query_servers/erlang',
       body: '{couch_native_process, start_link, []}'
     }, function(err) {
       callback(err);
diff --git a/migrations/extract-user-settings-roles.js b/migrations/extract-user-settings-roles.js
index 78590a1..2148cf5 100644
--- a/migrations/extract-user-settings-roles.js
+++ b/migrations/extract-user-settings-roles.js
@@ -34,7 +34,7 @@ var getAdmins = function(callback) {
       protocol: db.settings.protocol,
       hostname: db.settings.host,
       port: db.settings.port,
-      pathname: '_node/couchdb@localhost/_config/admins'
+      pathname: '_node/' + process.env.COUCH_NODE_NAME + '/_config/admins'
     }),
     auth: {
       user: db.settings.username,
```

@alxndrsn do you recall while you created the `COUCH_NODE_NAME` env var? Would it be crazy to default it in server.js to what you replaced?

**Comment by alxndrsn** [comment]
Defaulting it might be ok, but you'll notice pretty quickly that the node name on docker is different to that on your local machine ;¬)

**Comment by SCdF** [comment]
Should not have assigned this to myself sorry-- I was 100% not working on it.

**Comment by SCdF** [comment]
PR: https://github.com/medic/medic-api/pull/130

**Comment by SCdF** [comment]
Hey @alxndrsn please take a look at the attached PR. NB: there are two commits in it, one is just for ES6 stuff.

**Comment by SCdF** [comment]
Actually this has managed to break api in a way that the tests wouldn't pick up until we ran medic-webapp's.

**Comment by SCdF** [comment]
Fixed it, feel free to take a look @alxndrsn

**Comment by SCdF** [comment]
OK I lied. Hold off Alex, I'm going revert these ES6 changes and prepare a PR just for this change. There is clearly something going on with a lack of equivalence between:

```js
foo((a, b) => {
  bar(a, b)
});
```
And
```
foo(bar)
```

Even though I can't understand why.

**Comment by SCdF** [comment]
OK @alxndrsn you're up. I cut out most of the refactor to just be the code I'd already written that I was adding.

**Comment by alxndrsn** [comment]
Over to you, @SCdF

**Comment by SCdF** [comment]
Fixed issues, merged.
