### ISSUE TITLE
Submitting feedback no longer works

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3273]
To reproduce:

1. Log in as a restricted user
1. Go to Hamburger menu > Report bug
2. Type anything
3. Hit submit

Stacktrace:

```
Error submitting modal DOMException: Failed to execute 'postMessage' on 'Worker': An object could not be cloned.
    at sendMessage (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:174085:12)
    at PouchDB$3.<anonymous> (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:174266:5)
    at PouchDB$3.<anonymous> (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:174509:21)
    at PouchDB$3.<anonymous> (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:174884:16)
    at http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:174916:14
    at PouchDB$3.<anonymous> (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:174904:19)
    at PouchDB$3.<anonymous> (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:174884:16)
    at PouchDB$3.<anonymous> (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:864:27)
    at PouchDB$3.<anonymous> (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:161865:19)
    at processQueue (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:36829:37)
```

**Comment by garethbowen** [comment]
Code review please @mandric
