### ISSUE TITLE
add-national_admin-role migration does not work in couchdb 1

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3331]
Log from my local install:

```
Running migration "add-national_admin-role"...
/home/gareth/src/medic/medic-api/migrations/add-national_admin-role.js:14
    if (!result.admins.roles.includes(role)) {
                      ^

TypeError: Cannot read property 'roles' of undefined
    at db.request (/home/gareth/src/medic/medic-api/migrations/add-national_admin-role.js:14:23)
    at Request._callback (/home/gareth/src/medic/medic-api/node_modules/nano/lib/nano.js:217:16)
    at Request.self.callback (/home/gareth/src/medic/medic-api/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/gareth/src/medic/medic-api/node_modules/request/request.js:1126:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/gareth/src/medic/medic-api/node_modules/request/request.js:1046:12)
    at IncomingMessage.g (events.js:286:16)

```

**Comment by SCdF** [comment]
Weird that travis didn't fail… I presumed it would cover the running of that migration on CouchDB 1.0.

**Comment by garethbowen** [comment]
It looks like the API dependency hasn't been bumped so the e2e tests aren't yet running this migration.

**Comment by SCdF** [comment]
Man it would be great if we could get consensus on whether or not we could merge repos…

**Comment by SCdF** [comment]
PR: https://github.com/medic/medic-api/pull/137

@garethbowen take me home, country road

**Comment by sglangevin** [comment]
Is there anything to AT here? cc @ngaruko
