### ISSUE TITLE
namespace-form-fields migration causing Express toString fail

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3371]
```
2017-04-11T21:39:22.961Z - error: buffer.js:495                                                          
    throw new Error('"toString()" failed');
    ^                                                                                                    

Error: "toString()" failed                                                                               
    at Buffer.toString (buffer.js:495:11)
    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL1
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)                                                                    
    at IncomingMessage.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L2
    at IncomingMessage.g (events.js:291:16)                                                              
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)                                                            
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)                                       
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Most likely because the migration queries all `data_records` without batching.

**Comment by estellecomment** [comment]
https://github.com/medic/medic-api/pull/142

**Comment by estellecomment** [comment]
Fixed tests, @SCdF can you review?

**Comment by SCdF** [comment]
Back to you @estellecomment

**Comment by estellecomment** [comment]
pong

**Comment by SCdF** [comment]
For future reference, real PR link is: https://github.com/medic/medic-api/pull/143

Back to you @estellecomment

**Comment by sglangevin** [comment]
Anything to AT here? cc @ngaruko

**Comment by ngaruko** [comment]
Any clue on how to AT this @estellecomment ?

**Comment by estellecomment** [comment]
Migration should run, including on large data sets (but with all the migrating we've been doing recently, that's probably fine)
For the error reporting, you'd have to make bulk-edit fail on the db... We're probably fine with the unit test.
Moving to Ready.
