### ISSUE TITLE
Gardener Bug in Startup Log

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#3481]
The following error appears repeatedly in gardener startup logs.

```
/srv/software/gardener/v1.1.0/lib/utils.js:20                                                                                            
    return (module_name.indexOf(suffix, module_name.length - suffix.length) !=                                                           
                       ^                                                                                                                 
TypeError: Cannot read property 'indexOf' of undefined                                                                                   
    at Object.exports.is_tgz (/srv/software/gardener/v1.1.0/lib/utils.js:20:24)                                                          
    at is_remote_package (/srv/software/gardener/v1.1.0/lib/processes.js:169:49)                                                         
    at /srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:570:21                                                    
    at /srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:249:17                                                    
    at /srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:125:13                                                    
    at Array.forEach (native)                                                                                                            
    at _each (/srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:46:24)                                             
    at async.each (/srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:124:9)                                        
    at _asyncMap (/srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:248:13)                                        
    at Object.map (/srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:219:23)  
```
This is an older version of gardener.  However, looking at the code, the bug is still in there.

**Comment by henokgetachew** [comment]
Pull request filed to gardener's repo here: https://github.com/garden20/gardener/pull/32.  Can someone with access please have a look? @garethbowen @mandric

**Comment by garethbowen** [comment]
@mandric This is assigned to you and I was mentioned too. I have no idea how this can happen but the patch seems fine to me. How do we even release gardener?

**Comment by mandric** [comment]
Merged and published 1.1.4 on npm.

**Comment by ngaruko** [comment]
Do we need to AT this @henokgetachew ?

**Comment by henokgetachew** [comment]
I'm not sure what caused the error in the first place @ngaruko so, I don't know how we can do AT as well.

**Comment by ngaruko** [comment]
closing this. Will reopen if it happens again
