### ISSUE TITLE
Migration failure in extract-person-contacts

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#3519]
During a production upgrade, we encountered the following migration failure that caused us to decide to roll back the update:

```
2017-05-21T03:05:35.457Z - error: Fatal error initialising medic-api Migration
"extract-person-contacts" faed with: {"message":"Failed to update parent on facility
f1e902ed-cc8e-0e26-cf7a70467542db67 - {\n  \"code\ 400,\n  \"message\": \"Health Center
131e0071-c537-36ad-8cf721f17a50f17b should have \\\"district_hospital\" parent
type.\"\n}","stack":"Error: Failed to update parent on facility
f1e902ed-cc8e-0e26-cf7a70467542db -
{\n  \"code\": 400,\n  \"message\": \"Health Center 131e0071-c537-36ad-8cf721f17a50f17b
should have \\\"strict_hospital\\\" parent type.\"\n}\n    at 
/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDOTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/migrations/extract-person-contacts.js:2:29\n    at 
/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvVkaWMtYXBp/node_modules/medic-api/controllers/places.js:220:7\n    at 
/srv/storage/gardener/data/working_diaHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/asc/dist/async.js:3838:9\n    at 
/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljLkZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/dist/async.js:421:16\n    at iteratCallback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWaWMtYXBp/node_modules/medic-api/node_modules/async/dist/async.js:924:17)\n    at 
/srv/storage/gardener/dataorking_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/nodeodules/async/dist/async.js:906:16\n    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTL21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/dist/async.js:3835:13\n  at 
/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtBp/node_modules/medic-api/controllers/places.js:207:18\n    at err (/srv/storage/gardener/data/working_dir/R0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/placejs:45:12)\n    at validatePlace (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGl19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/places.js:77:14)"}
```
To do:

- [ ] Examine facility data to determine correctness
- [ ] If facility data is clearly incorrect, correct it and retest the migration
- [ ] If facility data appears correct, refer to dev team and make use of preserved clone instance for reproduction/debugging

**Comment by garethbowen** [comment]
I'm closing this as it's most likely a data integrity issue. If I'm right, create a medic-projects issue to solve it. If it's actually a bug, then reopen this with more details.

cc @bishwas-medic @browndav

**Comment by bishwas-medic** [comment]
@garethbowen @browndav can you please let me know which project this was? I will look into it and file issue in medic-projects if needed

**Comment by sglangevin** [comment]
@bishwas-medic this was a project in Africa and I've already taken it up with @ngamita to get the facilities table fixed so we don't run into this again.
