### ISSUE TITLE
Requesting forms should respond with 4xx on client error

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3569]
If you request a form that doesn't exist you get a 500 response and an ugly stack trace in the api log. For example:

```
curl -vvvv -H "x-openrosa-version: 1" http://gareth:SUPERSECRETPASSWORD@localhost:5988/api/v1/forms/missing.xml
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5988 (#0)
* Server auth using Basic with user 'gareth'
> GET /api/v1/forms/missing.xml HTTP/1.1
> Host: localhost:5988
> Authorization: Basic Z2FyZXRoOnBhc3M=
> User-Agent: curl/7.47.0
> Accept: */*
> x-openrosa-version: 1
> 
< HTTP/1.1 500 Internal Server Error
< X-Powered-By: Express
< Content-Type: text/plain
< Date: Wed, 21 Jun 2017 23:32:09 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
```

And the API log says...

```
Server error:
 Error: Form not found: missing (xml)
    at /home/gareth/src/medic/medic-api/controllers/forms.js:107:25
    at Request._callback (/home/gareth/src/medic/medic-api/node_modules/nano/lib/nano.js:217:16)
    at Request.self.callback (/home/gareth/src/medic/medic-api/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/gareth/src/medic/medic-api/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/gareth/src/medic/medic-api/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
```

This is misleading and annoying. Respond with a 404 if it's missing and a 400 if it's a bad request.

**Comment by garethbowen** [comment]
Code review please @mandric
