### ISSUE TITLE
Flakey tests

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3689]
https://travis-ci.org/medic/medic-webapp/jobs/255518226 failed with:

```
Failures:
1) Add new district tests :  should open new place form
  Message:
    Failed: unknown error: Element <a ui-sref="contacts.detail" id="contacts-tab" class="contacts-tab selected" ng-class="{'selected': currentTab === 'contacts'}" mm-auth="can_view_contacts,can_view_contacts_tab" href="#/contacts/">...</a> is not clickable at point (638, 34). Other element would receive the click: <div class="modal-header">...</div>
      (Session info: chrome=59.0.3071.115)
      (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.4.0-83-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 22 milliseconds
    Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
    System info: host: 'testing-gce-92855987-e2a5-405b-b7a6-6a7b6fbee3dd', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-83-generic', java.version: '1.8.0_131'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac), userDataDir=/tmp/.org.chromium.Chromium.dLRFEx}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.115, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
    Session ID: 0c354def1b7b46230d9e7897dc068509
  Stack:
    WebDriverError: unknown error: Element <a ui-sref="contacts.detail" id="contacts-tab" class="contacts-tab selected" ng-class="{'selected': currentTab === 'contacts'}" mm-auth="can_view_contacts,can_view_contacts_tab" href="#/contacts/">...</a> is not clickable at point (638, 34). Other element would receive the click: <div class="modal-header">...</div>
      (Session info: chrome=59.0.3071.115)
      (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.4.0-83-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 22 milliseconds
    Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
    System info: host: 'testing-gce-92855987-e2a5-405b-b7a6-6a7b6fbee3dd', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-83-generic', java.version: '1.8.0_131'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac), userDataDir=/tmp/.org.chromium.Chromium.dLRFEx}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.115, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
    Session ID: 0c354def1b7b46230d9e7897dc068509
        at WebDriverError (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/error.js:27:5)
        at Object.checkLegacyResponse (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/error.js:639:15)
        at parseHttpResponse (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/http/index.js:538:13)
        at client_.send.then.response (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/http/index.js:472:11)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2820:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From: Task: WebElement.click()
        at WebDriver.schedule (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:377:17)
        at WebElement.schedule_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:1744:25)
        at WebElement.click (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:1845:17)
        at actionFn (/home/travis/build/medic/medic-webapp/node_modules/protractor/built/element.js:101:44)
        at Array.map (native)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/element.js:463:80
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2775:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)Error
        at ElementArrayFinder.applyAction_ (/home/travis/build/medic/medic-webapp/node_modules/protractor/built/element.js:461:27)
        at ElementArrayFinder._this.(anonymous function) [as click] (/home/travis/build/medic/medic-webapp/node_modules/protractor/built/element.js:103:30)
        at ElementFinder.(anonymous function) [as click] (/home/travis/build/medic/medic-webapp/node_modules/protractor/built/element.js:829:22)
        at Object.goToPeople (/home/travis/build/medic/medic-webapp/tests/protractor/page-objects/common/common.po.js:31:18)
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/create-new-district.specs.js:6:20)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2820:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From: Task: Run it("should open new place form") in control flow
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:79:14)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:16:5
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2775:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From asynchronous test: 
    Error
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/create-new-district.specs.js:5:3)
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/create-new-district.specs.js:4:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (/home/travis/build/medic/medic-webapp/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at /home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:71:5
        at Array.forEach (native)
        at Jasmine.loadSpecs (/home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:70:18)
        at Jasmine.execute (/home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:154:8)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/frameworks/jasmine.js:129:15
        at Function.promise (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:682:9)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/frameworks/jasmine.js:101:14
        at _fulfilled (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:796:13)
        at /home/travis/build/medic/medic-webapp/node_modules/q/q.js:604:44
        at runSingle (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:137:13)
        at flush (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:125:13)
        at _combinedTickCallback (internal/process/next_tick.js:73:7)
        at process._tickCallback (internal/process/next_tick.js:104:9)

2) Submit Delivery Report open delivery form
  Message:
    Failed: unknown error: Element <a ui-sref="reports.detail" id="reports-tab" class="reports-tab" ng-class="{'selected': currentTab === 'reports'}" mm-auth="can_view_reports,can_view_reports_tab" href="#/reports/">...</a> is not clickable at point (554, 34). Other element would receive the click: <div class="modal-header">...</div>
      (Session info: chrome=59.0.3071.115)
      (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.4.0-83-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 116 milliseconds
    Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
    System info: host: 'testing-gce-92855987-e2a5-405b-b7a6-6a7b6fbee3dd', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-83-generic', java.version: '1.8.0_131'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac), userDataDir=/tmp/.org.chromium.Chromium.dLRFEx}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.115, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
    Session ID: 0c354def1b7b46230d9e7897dc068509
  Stack:
    WebDriverError: unknown error: Element <a ui-sref="reports.detail" id="reports-tab" class="reports-tab" ng-class="{'selected': currentTab === 'reports'}" mm-auth="can_view_reports,can_view_reports_tab" href="#/reports/">...</a> is not clickable at point (554, 34). Other element would receive the click: <div class="modal-header">...</div>
      (Session info: chrome=59.0.3071.115)
      (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.4.0-83-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 116 milliseconds
    Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
    System info: host: 'testing-gce-92855987-e2a5-405b-b7a6-6a7b6fbee3dd', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-83-generic', java.version: '1.8.0_131'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac), userDataDir=/tmp/.org.chromium.Chromium.dLRFEx}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.115, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
    Session ID: 0c354def1b7b46230d9e7897dc068509
        at WebDriverError (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/error.js:27:5)
        at Object.checkLegacyResponse (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/error.js:639:15)
        at parseHttpResponse (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/http/index.js:538:13)
        at client_.send.then.response (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/http/index.js:472:11)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2820:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From: Task: WebElement.click()
        at WebDriver.schedule (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:377:17)
        at WebElement.schedule_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:1744:25)
        at WebElement.click (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:1845:17)
        at actionFn (/home/travis/build/medic/medic-webapp/node_modules/protractor/built/element.js:101:44)
        at Array.map (native)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/element.js:463:80
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2775:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)Error
        at ElementArrayFinder.applyAction_ (/home/travis/build/medic/medic-webapp/node_modules/protractor/built/element.js:461:27)
        at ElementArrayFinder._this.(anonymous function) [as click] (/home/travis/build/medic/medic-webapp/node_modules/protractor/built/element.js:103:30)
        at ElementFinder.(anonymous function) [as click] (/home/travis/build/medic/medic-webapp/node_modules/protractor/built/element.js:829:22)
        at Object.goToReports (/home/travis/build/medic/medic-webapp/tests/protractor/page-objects/common/common.po.js:36:17)
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/forms/submit-delivery-form.specs.js:75:12)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2820:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From: Task: Run it("open delivery form") in control flow
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:79:14)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:16:5
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2775:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From asynchronous test: 
    Error
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/forms/submit-delivery-form.specs.js:74:3)
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/forms/submit-delivery-form.specs.js:6:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (/home/travis/build/medic/medic-webapp/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at /home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:71:5
        at Array.forEach (native)
        at Jasmine.loadSpecs (/home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:70:18)
        at Jasmine.execute (/home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:154:8)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/frameworks/jasmine.js:129:15
        at Function.promise (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:682:9)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/frameworks/jasmine.js:101:14
        at _fulfilled (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:796:13)
        at /home/travis/build/medic/medic-webapp/node_modules/q/q.js:604:44
        at runSingle (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:137:13)
        at flush (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:125:13)
        at _combinedTickCallback (internal/process/next_tick.js:73:7)
        at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by estellecomment** [comment]
Reviewed most expertly by @SCdF. 
https://www.youtube.com/watch?v=kfVsfOSbJY0 

Over-optimistically closing issue.

**Comment by estellecomment** [comment]
It's back!

Clicking the contacts-tab is hitting a modal. Don't see why a modal should be there. Adding a refresh of the page to clean up old modals.

**Comment by estellecomment** [comment]
@garethbowen please review https://github.com/medic/medic-webapp/pull/3702
