### ISSUE TITLE
Test flake : "sms-gateway api - api returns list of pending WO messages" - "stale element reference:"

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3739]
Full log : [travis_258576063.txt](https://github.com/medic/medic-webapp/files/1183320/travis_258576063.txt)
```
Failures:
1) sms-gateway api - api returns list of pending WO messages - returns list and updates state
  Message:
[31m    Failed: stale element reference: element is not attached to the page document
      (Session info: headless chrome=60.0.3112.78)
      (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Linux 4.4.0-83-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 101 milliseconds
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
    Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
    System info: host: 'testing-gce-cf771b23-3e52-481f-95b2-f927eb07e136', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-83-generic', java.version: '1.8.0_131'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8), userDataDir=/tmp/.org.chromium.Chromium.3Sq7ii}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=60.0.3112.78, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
    Session ID: ce70a67d91e9366aeb1e632067a3f1e9[0m
  Stack:
    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=60.0.3112.78)
      (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Linux 4.4.0-83-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 101 milliseconds
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
    Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
    System info: host: 'testing-gce-cf771b23-3e52-481f-95b2-f927eb07e136', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-83-generic', java.version: '1.8.0_131'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8), userDataDir=/tmp/.org.chromium.Chromium.3Sq7ii}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=60.0.3112.78, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
    Session ID: ce70a67d91e9366aeb1e632067a3f1e9
        at WebDriverError (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/error.js:27:5)
        at StaleElementReferenceError (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/error.js:227:5)
        at Object.checkLegacyResponse (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/error.js:505:15)
        at parseHttpResponse (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/http.js:509:13)
        at doSend.then.response (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/http.js:440:13)
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From: Task: WebElement.click()
        at thenableWebDriverProxy.schedule (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
        at WebElement.schedule_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:1921:25)
        at WebElement.click (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:2002:17)
        at actionFn (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:94:34)
        at Array.map (native)
        at actionResults.getWebElements.then (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:484:67)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)Error
        at ElementArrayFinder.applyAction_ (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:482:23)
        at ElementArrayFinder.(anonymous function) [as click] (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:96:21)
        at ElementFinder.(anonymous function) [as click] (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:873:14)
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/sms-gateway.js:288:68)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From: Task: Run it("- returns list and updates state") in control flow
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:94:19)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:64:48
        at ControlFlow.emit (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/events.js:62:21)
        at ControlFlow.shutdown_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2565:10)
        at shutdownTask_.MicroTask (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2490:53)
        at MicroTask.asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2619:9)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From asynchronous test: 
    Error
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/sms-gateway.js:253:5)
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/sms-gateway.js:225:3)
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/sms-gateway.js:123:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (/home/travis/build/medic/medic-webapp/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at /home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:93:5
        at Array.forEach (native)
        at Jasmine.loadSpecs (/home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:92:18)
        at Jasmine.execute (/home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:197:8)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/frameworks/jasmine.js:132:15
        at Function.promise (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:682:9)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/frameworks/jasmine.js:104:14
        at _fulfilled (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:796:13)
        at /home/travis/build/medic/medic-webapp/node_modules/q/q.js:604:44
        at runSingle (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:137:13)
        at flush (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:125:13)
        at _combinedTickCallback (internal/process/next_tick.js:73:7)
        at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by ngaruko** [comment]
Re: #3996
