### ISSUE TITLE
Test flake : "sms-gateway api - gateway submits new WT sms messages" : "No element found using locator"

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3744]
```
Failures:
1) sms-gateway api - gateway submits new WT sms messages - shows content
  Message:
[31m    Failed: No element found using locator: By(css selector, #message-header .name)[0m
  Stack:
    NoSuchElementError: No element found using locator: By(css selector, #message-header .name)
        at elementArrayFinder.getWebElements.then (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:851:17)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)Error
        at ElementArrayFinder.applyAction_ (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:482:23)
        at ElementArrayFinder.(anonymous function).args [as getText] (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:96:21)
        at ElementFinder.(anonymous function).args [as getText] (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:873:14)
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/sms-gateway.js:170:55)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
    From: Task: Run it("- shows content") in control flow
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:94:19)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:64:48
        at ControlFlow.emit (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/events.js:62:21)
        at ControlFlow.shutdown_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2565:10)
        at shutdownTask_.MicroTask (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2490:53)
        at MicroTask.asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2619:9)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
    From asynchronous test: 
    Error
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/sms-gateway.js:153:5)
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/sms-gateway.js:140:3)
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/sms-gateway.js:123:1)
        at Module._compile (module.js:569:30)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (/home/travis/build/medic/medic-webapp/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
        at tryModuleLoad (module.js:466:12)
        at Function.Module._load (module.js:458:3)
        at Module.require (module.js:513:17)
        at require (internal/module.js:11:18)
        at /home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:93:5
        at Array.forEach (native)
        at Jasmine.loadSpecs (/home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:92:18)
        at Jasmine.execute (/home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:197:8)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/frameworks/jasmine.js:132:15
        at Function.promise (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:682:9)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/frameworks/jasmine.js:104:14
        at _fulfilled (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:796:13)
        at /home/travis/build/medic/medic-webapp/node_modules/q/q.js:604:44
        at runSingle (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:137:13)
        at flush (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:125:13)
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at process._tickCallback (internal/process/next_tick.js:180:9)
```
[travis_.txt](https://github.com/medic/medic-webapp/files/1190473/travis_.txt)

**Comment by ngaruko** [comment]
re: #3996

**Comment by garethbowen** [comment]
Nothing to see here...
