### ISSUE TITLE
data.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3770]
The `/api/v1/records` API is broken and always returns a 500 error with the following stack:

```
2017-08-10T01:24:06.791Z - error: UNCAUGHT EXCEPTION!
Server error:
 { TypeError: data.hasOwnProperty is not a function
    at Object.createByForm (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/record-utils.js:34:13)
    at Object.create (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/records.js:6:26)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server.js:403:13
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/auth.js:120:11
    at checkDistrict (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/auth.js:44:12)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/auth.js:116:9
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/auth.js:91:7
    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/auth.js:19:5)
    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
```

This is caused by the fact that the given data is parsed from the request body and [isn't a real object](https://github.com/expressjs/express/issues/3264) so it doesn't have the `hasOwnProperty` function.

This was reported here: https://github.com/medic/medic-projects/issues/2626

This will need to be backported to 2.12.x and 2.13.x and a new 2.12 service pack released to get medic-collect working again.

**Comment by garethbowen** [comment]
Introduced by https://github.com/medic/medic-projects/issues/2480

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
Merged into master, 2.12.x and 2.13.x, and created a 2.12.4-beta.1 release: https://travis-ci.org/medic/medic-webapp/builds/262993429

**Comment by SCdF** [comment]
Beta has been release.

**Comment by ngaruko** [comment]
LGTM.
![image](https://user-images.githubusercontent.com/6979995/29599146-e4800940-8821-11e7-967b-d2ec0f7e6fe8.png)
