### ISSUE TITLE
User meta database creation fails if user has invalid characters

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3778]
In #2418 we decided to store read status docs in a user specific database so we wrote a migration to create the databases and all the docs. Unfortunately some existing usernames have characters that are invalid for database names which causes the migration to fail, for example, 9 users on lg-kenya have a trailing "." which causes the following exception:

```
2017-08-14T23:26:55.220Z - error: Migration extract-read-status failed
 
2017-08-14T23:26:55.220Z - error: Fatal error initialising medic-api
 
2017-08-14T23:26:55.225Z - error: { Error: Name: 'XXXXX.-meta'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter.
    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
  name: 'Error',
  error: 'illegal_database_name',
  reason: 'Name: \'XXXXX.-meta\'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter.',
  scope: 'couch',
  statusCode: 400,
  request: 
   { method: 'GET',
     headers: 
      { 'content-type': 'application/json',
        accept: 'application/json' },
     uri: 'http://XXXXXX:XXXXXX@localhost:5984/XXXXX.-meta' },
  headers: 
   { date: 'Mon, 14 Aug 2017 23:26:55 GMT',
     'content-type': 'application/json',
     'cache-control': 'must-revalidate',
     statusCode: 400,
     uri: 'http://XXXXXX:XXXXXX@localhost:5984XXXXX.-meta' },
  errid: 'non_200',
  description: 'couch returned 400' }
```

Migrating users off their username is difficult so explore changing the migration code to escape the username if it violates the database naming rules:

> Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter.

Check if this also applies to the local pouchdb database and reuse the escaping code so the replication still works.

Consider adding validation to the user creation UI and API to enforce these rules so new users will work as expected.

**Comment by garethbowen** [comment]
Relevant [couchdb documentation](https://wiki.apache.org/couchdb/HTTP_database_API#Naming_and_Addressing).

**Comment by garethbowen** [comment]
Code review please @alxndrsn (api and webapp).

The api submodule needs to be bumped and both PRs backported to `2.13.x`.

**Comment by garethbowen** [comment]
@alxndrsn Can you have another look? I've made some changes made and some comments in the PRs.

**Comment by alxndrsn** [comment]
LGTM

**Comment by sglangevin** [comment]
I tested the upgrade again yesterday on the server that had this issue and initially it was 502ing for a while, but it's back up as of today, so that's good news. I then tested the upgrade from v2.12.x to v2.13.0-beta.5 and could not reproduce this error on any of the devices (including the Y4, where I originally got the error). Moving to ready!
