### ISSUE TITLE
Add new person protractor test fails a lot

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3816]
Like this:

```
Expected 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/55b28809-27f0-4a76-acd5-7c51ddbf1e62' to equal 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/'
```

from

```
Failures:
1) Add new person tests :  should add new person
  Message:
�[31m    Expected 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/55b28809-27f0-4a76-acd5-7c51ddbf1e62' to equal 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/'.�[0m
  Stack:
    Error: Failed expectation
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/add-new-person.js:17:35)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>

45 specs, 1 failure
```

A long list of examples can be seen at https://github.com/medic/medic-webapp/pull/3803

**Comment by garethbowen** [comment]
I've removed the offending assertion. The first run passed, we'll have to monitor it over time.
