### ISSUE TITLE
regular e2e test failure: Expected 'R' to be 'Registration'.

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3822]
This test fails often:

```
Failures:
1) registration transition submits new sms messages shows content
  Message:
�[31m    Expected 'R' to be 'Registration'.�[0m
  Stack:
    Error: Failed expectation
        at checkItemSummary (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/registration-by-sms.js:222:84)
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/registration-by-sms.js:250:7)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

45 specs, 1 failure
```

**Comment by garethbowen** [comment]
Merged and passing - will have to wait to see if it starts failing again...
