### ISSUE TITLE
Gardener/API bug with latest alpha

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#3823]
This is the last error that's shown on medic API:
```
2017-08-23T20:54:45.550Z - error: module.js:471
    throw err;
    ^
                                        
Error: Cannot find module 'buffer-shims'                  
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17) 
    at require (internal/module.js:20:19)                                                                                              
    at Object.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/
    at Module._compile (module.js:570:32)              
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)  
    at tryModuleLoad (module.js:446:12)       
    at Function.Module._load (module.js:438:3)
```

Gardener is not trying to restart API because it is itself failing to start up with the following error message.

```
TypeError: Path must be a string. Received undefined                                                                                     
    at assertPath (path.js:7:11)             
    at Object.resolve (path.js:1146:7)                                        
    at /srv/software/gardener/v1.1.1/lib/processes.js:557:33
    at /srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:209:22)
    at start_forever (/srv/software/gardener/v1.1.1/lib/processes.js:549:11)         
    at fn (/srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:746:34)
    at /srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:1213:16
    at /srv/software/medic-core/v1.6.1/x64/lib/node_modules/async/lib/async.js:166:37
path.js:7                                                                                   
    throw new TypeError('Path must be a string. Received ' + inspect(path));                     
    ^
```
Possible explanation could be that the gardener failure is causing required modules by medic API not become installed and therefore the whole thing is failing.

**Comment by henokgetachew** [comment]
Gardener didn't create medic-api in the working_dir even after it was renamed.  
The error that says `Path must be a string` seems like it was caused because of the renaming of the medic-api working_dir folder.  Gardener looks for an exact path for medic-api that it expects to find and if that path doesn't resolve, it throws that error.  That looks like a bug on the side of gardener because it's supposed to create the folder and reconfigure the app if it doesn't find it in that location.

**Comment by henokgetachew** [comment]
Couldn't reproduce this.  Wiping it and installing a new for a fix.
