### ISSUE TITLE
Flakey test: registration transition submits new sms messages shows content

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3842]
This one keeps cropping up so it's worth looking in to...

```
Failures:
1) registration transition submits new sms messages shows content
  Message:
[31m    Failed: Wait timed out after 10004ms[0m
  Stack:
    TimeoutError: Wait timed out after 10004ms
        at WebDriverError (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/error.js:27:5)
        at TimeoutError (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/error.js:238:5)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2107:17
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From: Task: <anonymous wait>
        at scheduleWait (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2094:20)
        at ControlFlow.wait (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2408:12)
        at thenableWebDriverProxy.wait (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:943:29)
        at run (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/browser.ts:66:27)
        at ProtractorBrowser.to.(anonymous function) [as wait] (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/browser.ts:74:12)
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/registration-by-sms.js:242:15)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From: Task: Run it("shows content") in control flow
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:94:19)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:64:48
        at ControlFlow.emit (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/events.js:62:21)
        at ControlFlow.shutdown_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2565:10)
        at shutdownTask_.MicroTask (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2490:53)
        at MicroTask.asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2619:9)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From asynchronous test: 
    Error
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/registration-by-sms.js:240:5)
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/registration-by-sms.js:198:3)
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/registration-by-sms.js:4:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (/home/travis/build/medic/medic-webapp/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at /home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:93:5
        at Array.forEach (native)
        at Jasmine.loadSpecs (/home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:92:18)
        at Jasmine.execute (/home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:197:8)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/frameworks/jasmine.js:132:15
        at Function.promise (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:682:9)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/frameworks/jasmine.js:104:14
        at _fulfilled (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:796:13)
        at /home/travis/build/medic/medic-webapp/node_modules/q/q.js:604:44
        at runSingle (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:137:13)
        at flush (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:125:13)
        at _combinedTickCallback (internal/process/next_tick.js:73:7)
        at process._tickCallback (internal/process/next_tick.js:104:9)

45 specs, 1 failure
Finished in 99.966 seconds
```

**Comment by garethbowen** [comment]
I've had a bit of a look at this and I can't get it to fail but manually inserting timeouts. I think there may be a race condition if the transition config is loaded after the message is received. If this happens again try and grab the entire build log because there is other logging (sentinel, webdriver, etc) that will help debug this issue.

**Comment by garethbowen** [comment]
I don't have a lot of confidence that that PR will fix the issue so I'll leave this around for a while...

**Comment by garethbowen** [comment]
It's still happening. I still can't get it to occur locally. There's quite a lot going on before that line (wait for sentinel transitions to run, wait for the changes feed to fire, wait for search to complete) so it's _possible_ it's taking longer than 10 seconds occasionally. Also because it's an async operation it's not too bad if it takes a little longer than 10 seconds to complete. So I've increased the timeout to 30 seconds and we'll see if that solves it...

**Comment by garethbowen** [comment]
Still failing with 30s wait. No idea why...

**Comment by ngaruko** [comment]
Re: #3996
