### ISSUE TITLE
Sentinel transitions bug: Registrations

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#3843]
Sentinel crashes when there is an issue with the configuration of the registration.  I think the correct behavior should be to mark the error in the logs or on the doc itself as an error.  Even better would have been to validate this before saving the registration config.
```
2017-08-30T09:16:03.821Z - error: /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/transitions/registration.js:364
                options.params.forEach(function(name) {                                
                               ^

TypeError: options.params.forEach is not a function
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/transitions/registration.js:364:32
    at getRegistrations (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/transitions/registration.js:25:16)
    at Object.assignSchedule (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/transitions/registration.js:357:9)
    at assign_schedule (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/transitions/registration.js:314:28)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/transitions/registration.js:268:29
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/async/dist/async.js:3853:24
    at replenish (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/async/dist/async.js:946:17)       
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/async/dist/async.js:950:9
    at eachOfLimit (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/async/dist/async.js:975:24)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/async/dist/async.js:980:16
```

**Comment by sglangevin** [comment]
I'm fairly certain this was done intentionally. cc @garethbowen

**Comment by sglangevin** [comment]
There is some discussion on #3585 and #3668

**Comment by henokgetachew** [comment]
Yeah I see that there's ongoing work on this. Marking this as a duplicate of the other issues.

**Comment by garethbowen** [comment]
Actually this one is a bug in the code - the validation appears to not be checking fully. I'll improve the validation.

**Comment by garethbowen** [comment]
Review please @SCdF

**Comment by SCdF** [comment]
LGTM, merged.

**Comment by ngaruko** [comment]
Shall we leave this with you to test @henokgetachew ?

**Comment by sglangevin** [comment]
Yes, let's assign @henokgetachew since he filed the issue.

**Comment by henokgetachew** [comment]
@bishwas-medic do you still have the config that was causing the issue with the registrations in srh-gorkha?

**Comment by bishwas-medic** [comment]
@henokgetachew not really. But you can try creating one by opening and saving the settings from the Advanced Configurations. This error was caused by a trigger that was added to one of the Registration reports by the config page automatically.

**Comment by henokgetachew** [comment]
The problem hasn't come again after this so I'm closing this and removing from AT.
