### ISSUE TITLE
Errant refactor broke sentinel 

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3857]
```
/Users/scdf/Code/Medic/medic-sentinel/transitions/accept_patient_reports.js:168
            id: doc.fields && doc.fields.patient_id
                   ^

TypeError: Cannot read property 'fields' of undefined
    at Object.handleReport (/Users/scdf/Code/Medic/medic-sentinel/transitions/accept_patient_reports.js:168:20)
    at clear_schedule (/Users/scdf/Code/Medic/medic-sentinel/transitions/registration.js:326:28)
    at series.push.cb (/Users/scdf/Code/Medic/medic-sentinel/transitions/registration.js:269:19)
    at /Users/scdf/Code/Medic/medic-sentinel/node_modules/async/dist/async.js:3830:24
    at replenish (/Users/scdf/Code/Medic/medic-sentinel/node_modules/async/dist/async.js:946:17)
    at iterateeCallback (/Users/scdf/Code/Medic/medic-sentinel/node_modules/async/dist/async.js:931:17)
```

This is caused by: https://github.com/medic/medic-sentinel/pull/163

This only affects master. We need to fix the noted issue and look for any others.

**Comment by SCdF** [comment]
(anyone can pick this up, but I'll look at it after I've looked at 2.13.0-beta issues, since they are more important)

**Comment by SCdF** [comment]
This also caused a bug the https://github.com/medic/medic-sentinel/pull/167 Pr will fix, where we're sometimes mapping registrations out of their wrapped docs and sometimes not.

**Comment by SCdF** [comment]
@garethbowen sink your teeth into the delicious PR above!

**Comment by SCdF** [comment]
Merged.

**Comment by SCdF** [comment]
For AT: this is similar and related to https://github.com/medic/medic-webapp/issues/3824 and can be dealt with simultaneously.

**Comment by sglangevin** [comment]
Assigning to @ngaruko for AT.
