### ISSUE TITLE
Configuration Wizard Error

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3872]
Steps to reproduce:
1. Deployed the app using horticularist
2. opened app in browser
3. Prompted to do configuration (same as skipping this and opening the wizard later)
4. On step 2 (Identify care coordinators), select one of the option
5. Nothing happens >>>
 Error in console:
```
inbox.js:3 Uncaught TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at console.o.console.(anonymous function) [as log] (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:3:2070195)
    at HTMLAnchorElement.d (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1999010)
    at HTMLElement.dispatch (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:3:979557)
    at HTMLElement.m.handle (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:3:977568)
o.console.(anonymous function) @ inbox.js:3
d @ inbox.js:3
dispatch @ inbox.js:3
m.handle @ inbox.js:3
inbox.js:3 Initiating changes watch
```

![image](https://user-images.githubusercontent.com/6979995/30089206-7ed64d78-92ff-11e7-9b9b-a4bff67c9975.png)

Same happens when a language is selected.

**Comment by garethbowen** [comment]
Code review please @estellecomment

**Comment by estellecomment** [comment]
cool.

**Comment by ngaruko** [comment]
Seems to work now. However `language selection` is not saved and on opening the wizard again, there previous selection does not show. Is this expected @garethbowen @estellecomment 
![image](https://user-images.githubusercontent.com/6979995/30302822-d548bac6-97b7-11e7-86dc-438ab3a7dc99.png)

**Comment by garethbowen** [comment]
Another code review please @estellecomment . Unrelated issue but came up in the AT of this one.

**Comment by garethbowen** [comment]
Such a quick turnaround! Nice one @ngaruko
