### ISSUE TITLE
Android wrapper 0.3.6 crashes on Android 5+ after settings are filled

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3878]
The location dialog is not triggered on first run if the settings dialog is accessed.

**Comment by alxndrsn** [comment]
```
09-07 12:04:56.970 12227 12227 E AndroidRuntime: FATAL EXCEPTION: main
09-07 12:04:56.970 12227 12227 E AndroidRuntime: Process: org.medicmobile.webapp.mobile, PID: 12227
09-07 12:04:56.970 12227 12227 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.medicmobile.webapp.mobile/org.medicmobile.webapp.mobile.EmbeddedBrowserActivity}: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7406)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: Caused by: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1621)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1574)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:712)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:908)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:469)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at org.medicmobile.webapp.mobile.EmbeddedBrowserActivity.enableLocationUpdates(EmbeddedBrowserActivity.java:265)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at org.medicmobile.webapp.mobile.EmbeddedBrowserActivity.onCreate(EmbeddedBrowserActivity.java:85)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6904)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
09-07 12:04:56.970 12227 12227 E AndroidRuntime: 	... 9 more
```
