### ISSUE TITLE
Migration extract-person-contacts broken

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#4031]
The server details are shared on slack if further investigation is required.
Migration from Version 0.4 to Version 2.13
Error:
```
2017-11-10T12:18:21.578Z - error: Failed to restore contact on facility 42fbf87e-9857-8ad1-071fc2f9e15ac6b9, contact: {"name":"Redacted ","phone":"+251920---","type":"person","reported_date":1510316301222}
Migration extract-person-contacts failed
Fatal error initialising medic-api
Error: Failed to update contact on facility 42fbf87e-9857-8ad1-071fc2f9e15ac6b9: {
  "code": 400,
  "message": "Place 42fbf87e-9857-8ad1-071fc2f9e15ac6b9 is missing a \"parent\" property."
}
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/migrations/extract-person-contacts.js:109:20
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/migrations/extract-person-contacts.js:123:7
    at async.series.err (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/places.js:276:7)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/dist/async.js:3838:9
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/dist/async.js:421:16
    at iterateeCallback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/dist/async.js:924:17)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/dist/async.js:906:16
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/async/dist/async.js:3835:13
    at self._validatePlace.err (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/places.js:263:18)
    at err (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/places.js:99:12)
```

However, the document when requested from the original server is:
```
curl https://user:pass@amref-ethiopia.app.medicmobile.org/medic/42fbf87e-9857-8ad1-071fc2f9e15ac6b9 | jq
{
  "_id": "42fbf87e-9857-8ad1-071fc2f9e15ac6b9",
  "_rev": "433-068bcc2c2bbd7babd166f410959f3b2f",
  "type": "clinic",
  "name": "Redacted ",
  "contact": {
    "name": "Redacted ",
    "phone": "+25192----"
  },
  "parent": {
    "_id": "42fbf87e-9857-8ad1-071fc2f9e15a5e26",
    "_rev": "15-0f2d0e53d04251e7171a51b76c881dbb",
    "type": "health_center",
    "name": "Redacted",
    "contact": {
      "name": "Redacted",
      "phone": "+25192----"
    },
    "parent": {
      "_id": "eec1f64b-b093-0a25-f0bd72d7f6d68010",
      "_rev": "3-c2fd98be72a3ff7ececf452c67f68f5a",
      "type": "district_hospital",
      "name": "Redacted",
      "parent": {},
      "contact": {
        "name": "Redacted",
        "phone": "+25198-----"
      }
    }
  },
  "sent_forms": {
    "ANCR": "2015-12-12T11:00:18.886Z",
    "F": "2015-08-06T11:08:45.000Z"
  }
}
```
Let's request the parent object to confirm that it's an actual document in the database.
```
 henok$ curl https://user:pass@amref-ethiopia.app.medicmobile.org/medic/eec1f64b-b093-0a25-f0bd72d7f6d68010 | jq
{
  "_id": "eec1f64b-b093-0a25-f0bd72d7f6d68010",
  "_rev": "3-c2fd98be72a3ff7ececf452c67f68f5a",
  "type": "district_hospital",
  "name": "Redacted",
  "parent": {},
  "contact": {
    "name": "Redacted",
    "phone": "+25198-----"
  }
}
```

**Comment by SCdF** [comment]
This has been broken by lineage, as you suspected @henokgetachew. Working out how to fix our inputs prior to validation, or perhaps just drop the validation (it's not clear if it's that important, i.e. does it actually catch anything or is just for good feels?)

**Comment by SCdF** [comment]
Please take a look at the PR @garethbowen . If you're cool with it I'll deal with merging and back porting.

Once that's done @henokgetachew what kind of build do you want to test your clone? a 2.13 patch?

**Comment by henokgetachew** [comment]
Yup, a 2.13 patch would be great.

**Comment by garethbowen** [comment]
@SCdF If we're doing a 2.13.x release we should consider including #4033

**Comment by garethbowen** [comment]
Looking good - back to you!

**Comment by SCdF** [comment]
Cheers!

I'll backport this as #4033 to 2.13 and release a new patch

**Comment by SCdF** [comment]
Merged to master, backported to 2.13 along with #4033, *and* backported to 2.14 as well

**Comment by SCdF** [comment]
@henokgetachew once 2.13.1 is available please give this another crack on your clone

**Comment by henokgetachew** [comment]
I have confirmed that this one works.
