### ISSUE TITLE
Migration move-sentinel-metadata has a race condition that can cause api to not boot

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4054]
The sentinel metadata doc is used to record what sequence sentinel has processed. After each change has been successfully processed the sequence is updated.

When api starts up it runs the `move-sentinel-metadata` migration which takes the existing doc with id `sentinel-meta-data` and moves it to a new local doc with id `_local/sentinel-meta-data`.

When sentinel starts up it looks for the `_local/sentinel-meta-data` doc and if it doesn't exist it assumes it's a new install and creates one starting at 0. If this happens before the api migration has run then the migration gets constant 409s trying to create the new doc with the same id. This causes api to go into a continuous restart loop, and forces sentinel to start processing from sequence 0 again.

```
2017-11-20T20:06:38.560Z - error: Migration move-sentinel-metadata failed
2017-11-20T20:06:38.560Z - error: Fatal error initialising medic-api
2017-11-20T20:06:38.565Z - error: { Error: Document update conflict.
    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
  name: 'Error',
  error: 'conflict',
  reason: 'Document update conflict.',
  scope: 'couch',
  statusCode: 409,
  request: 
   { method: 'POST',
     headers: 
      { 'content-type': 'application/json',
        accept: 'application/json' },
     uri: 'http://XXXXXX:XXXXXX@localhost:5984/medic',
     body: '{"_id":"_local/sentinel-meta-data","processed_seq":121614}' },
  headers: 
   { date: 'Mon, 20 Nov 2017 20:06:38 GMT',
     'content-type': 'application/json',
     'cache-control': 'must-revalidate',
     statusCode: 409,
     uri: 'http://XXXXXX:XXXXXX@localhost:5984/medic' },
  errid: 'non_200',
  description: 'couch returned 409' }
```

This is quite likely to occur if api has a bunch of other migrations to run first, or if (as in the case above) the api startup fails the first time.

This is required for `2.14.0`.

**Comment by garethbowen** [comment]
I think the bottom line is only one service should be in charge of creating and deleting these metadata docs. Initially I was thinking that service should be api but then sentinel would fail to start without some docs being created in the database and that feels unnecessarily coupled. Now I'm wondering if the api migration should be deleted in favour of sentinel managing all the creation, deletion, and updation of these docs.

**Comment by garethbowen** [comment]
@SCdF Any thoughts?

**Comment by SCdF** [comment]
Yep that seems fine. I think generally nothing should start unless api starts (to avoid other migration issues) but this is a fine mix for this specific issue

**Comment by SCdF** [comment]
@alxndrsn please review the above two PRs :-)

**Comment by SCdF** [comment]
(once you're done and I've concluded manual testing I'll merge into 2.14 and forward port to master)

**Comment by SCdF** [comment]
Merged to master.

**Comment by garethbowen** [comment]
Nice one, thanks!

**Comment by sglangevin** [comment]
I didn't run into this problem when upgrading from 2.14.0-beta.4 to 2.14.0-beta.5 or from 2.13.0 to 2.14.0-beta.5. Calling this AT-ed unless there are other scenarios we need to test.
