### ISSUE TITLE
Namespace form fields migration fails when it finds reports with form names not saved in the system

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#4059]
This is the error that comes up:
```
017-11-23T13:37:55.800Z - error: /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/migrations/namespace-form-fields.js:18
    var form = forms[doc.form];
                    ^

TypeError: Cannot read property 'DEAR' of undefined
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/migrations/namespace-form-fields.js:18:21
    at Array.forEach (native)
    at namespace (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/migrations/namespace-form-fields.js:14:8)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/migrations/namespace-form-fields.js:65:5
    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/lib/nano.js:217:16)
    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
```
The form:
![image](https://user-images.githubusercontent.com/3198821/33176450-2b8bdfee-d070-11e7-9fb6-814e726f57f6.png)

**Comment by garethbowen** [comment]
This error is saying the `forms` property is missing in the configuration. The strange thing is it's defined in the original server and missing in the cloned server. I think this migration is actually ok but a previous migration may have stuffed up the settings. Looking further...

**Comment by garethbowen** [comment]
Ok, crazy theory time...

@henokgetachew tells me that the gardener upgrade didn't go smoothly - it failed the first time through, after which he made some nginx changes, then restarted the upgrade. I think this meant that the `app_settings` from the previous ddoc didn't get copied into the new ddoc. Then api started up which sets the `app_settings` to the default values which don't have any configured `forms`. Then the migration ran and failed completely.

We could modify the migration to handle this more gracefully but it's handy in this case that it failed hard, otherwise the upgrade would have completed without actually performing the required migrations.

Henok is going to try an upgrade on a fresh clone to test the theory. If it's proven correct I propose we leave the code unchanged.

**Comment by henokgetachew** [comment]
This has been confirmed. I agree that the failure was handy.
