### ISSUE TITLE
add patient id validation to registration

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#416]
if a registration includes form field referencing another record we should validate whether the other record is found similar to ANCV.  We need this for immunization registration (IMMR) so a mother's registration can be submitted and the form validated properly.

**Comment by mandric** [comment]
While testing got a stacktrace in sentinel after adding an `exists` validation.  

```
2015-06-27T20:50:53.637Z - error: /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/db.js:27
 
2015-06-27T20:50:53.637Z - error:         var uri = path.join('/_fti/local', settings.db, '_design', settings.dd
 
2015-06-27T20:50:53.638Z - error:   
2015-06-27T20:50:53.638Z - error:                            
2015-06-27T20:50:53.638Z - error:                 ^
 
2015-06-27T20:50:53.645Z - error: ReferenceError: settings is not defined
    at Object.module.exports.fti (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/db.js:27:44)
    at _exists (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/lib/validation.js:16:8)
    at module.exports.extra_validations.exists (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/lib/validation.js:114:13)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/lib/validation.js:227:48
    at iterate (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/async/lib/async.js:134:13)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/async/lib/async.js:145:25
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/lib/validation.js:225:24
    at iterate (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/async/lib/async.js:134:13)
    at Object.async.eachSeries (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/async/lib/async.js:150:9)
    at Object.module.exports.validate (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/lib/validation.js:223:15)
 ```

**Comment by mandric** [comment]
Still not working, moving back to Active Work.
