### ISSUE TITLE
Reports about patients get `missing_named_view` error

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4326]
Reports about people have a `missing_named_view` error. It looks like we are referring to a view called `registered_patients` that doesn't exist.

![image](https://user-images.githubusercontent.com/789512/37830455-a064e912-2e78-11e8-9543-ed36bb032e8d.png)

```
2018-03-23T12:36:11.119Z - error: error: transition accept_patient_reports errored on doc 2515675d1644f1bd5f1ce794b3c8b8a5 seq 11813: {"message":"missing_named_view","stack":"Error: missing_named_view\n    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/nano/lib/nano.js:248:15)\n    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:188:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:1171:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:1091:12)\n    at IncomingMessage.g (events.js:291:16)","name":"Error","error":"not_found","reason":"missing_named_view","scope":"couch","statusCode":404,"request":{"method":"GET","headers":{"content-type":"application/json","accept":"application/json"},"uri":"http://XXXXXX:XXXXXX@localhost:5984/medic/_design/medic/_view/registered_patients","qs":{"include_docs":true,"key":"\"57186\""}},"headers":{"date":"Fri, 23 Mar 2018 12:36:11 GMT","content-type":"application/json","cache-control":"must-revalidate","statusCode":404,"uri":"http://XXXXXX:XXXXXX@localhost:5984/medic/_design/medic/_view/registered_patients"},"errid":"non_200","description":"couch returned 404"}
```

**Comment by abbyad** [comment]
This was also reported in AT for another issue here: https://github.com/medic/medic-webapp/issues/3959#issuecomment-375521050

**Comment by dianabarsan** [comment]
The missing view ("registered_patients" ) was moved from `medic` ddoc to `medic-client` ddoc in Nov 2017 (https://github.com/medic/medic-webapp/commit/f1ab8b867b8316c4c2126be40827a0fcfe840906#diff-28d3dab1d7aa81ffde8a4497a1814992), while the error message states that the view uri is `localhost:5984/medic/_design/medic/_view/registered_patients`. 

The stack trace also links to the legacy `medic-sentiel` repo (`/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/`).

**Comment by henokgetachew** [comment]
Alpha was indeed using outdated code.  I also confirmed that this was an issue both with beta.dev as well as standard.dev
I checked staging to make sure the right code is deployed there.  That was indeed the case.
I checked both alpha.dev and beta.dev to make sure the right code was deployed in the ddoc. That was also the case.
Therefore, this looks like a case of gardener not redeploying code correctly when ddoc gets updated.  How I fixed it was by running this on alpha
`sudo svc-down gardener && sudo rm -r /srv/storage/gardener/data/working_dir/* && sudo svc-up gardener`.  This makes gardener redeploy the code that's on the ddoc.  I'm not sure if this solves this issue but I think the next order of business is to check how many instances are affected as a result of this gardener issue. I can do that this week.

**Comment by henokgetachew** [comment]
A somewhat related issue is [here](https://github.com/medic/medic-webapp/issues/4275) - deals with the same issue with the node packages. However, we don't need to necessarily do it pre-upgrade and it's also a good idea to nuke everything in gardener's work_dir since this issue just confirmed that the same thing is happening with actual code from api and sentinel as well.  As a general practice, from now on, this is going to be a post-deployment/post-upgrade step.

```
sudo svc-down gardener && sudo rm -r /srv/storage/gardener/data/working_dir/* && sudo svc-up gardener
```

This makes sure gardener redeploys the latest code in the ddoc.

**Comment by garethbowen** [comment]
@abbyad Can I close this as Can't Reproduce? Or, duplicate?

**Comment by abbyad** [comment]
Have we formalized the `rm -r /srv/storage/gardener/data/working_dir/*` solution? The instance that I had the problem on was fixed, but not sure how we'll prevent this from happening again.

**Comment by garethbowen** [comment]
My understanding is we're using the `rm` solution for the beta testing for 2.15.0. 3.0.0 isn't affected (horti > gardener) so we're just going to muddle through till then. We can find a programmatic solution if that's not acceptable.

**Comment by abbyad** [comment]
I think that is fine. Will mark as `can't reproduce` but since that applies only to production instances will also mark as `deprioritized`
