### ISSUE TITLE
Flakey e2e test: Reports Summary Displays correct LHS and RHS summary Concerning reports using doc id

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4351]
```
Failures:
1) Reports Summary Displays correct LHS and RHS summary Concerning reports using doc id
  Message:
    Failed: Wait timed out after 10000ms
  Stack:
    TimeoutError: Wait timed out after 10000ms
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2107:17
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
    From: Task: <anonymous wait>
        at scheduleWait (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2094:20)
        at ControlFlow.wait (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2408:12)
        at thenableWebDriverProxy.wait (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:943:29)
        at run (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/browser.ts:66:27)
        at ProtractorBrowser.to.(anonymous function) [as wait] (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/browser.ts:74:12)
        at loadReport (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:247:13)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
    From: Task: Run it("Concerning reports using doc id") in control flow
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:94:19)
        at runCallback (timers.js:794:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)
    From asynchronous test: 
    Error
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:337:5)
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:298:3)
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:6:1)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (/home/travis/build/medic/medic-webapp/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at /home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:93:5
        at Array.forEach (<anonymous>)
        at Jasmine.loadSpecs (/home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:92:18)
        at Jasmine.execute (/home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:197:8)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/frameworks/jasmine.js:132:15
        at Function.promise (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:682:9)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/frameworks/jasmine.js:104:14
        at _fulfilled (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:796:13)
        at /home/travis/build/medic/medic-webapp/node_modules/q/q.js:604:44
        at runSingle (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:137:13)
        at flush (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:125:13)
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by ngaruko** [comment]
Fixed with https://github.com/medic/medic-webapp/pull/4570
