### ISSUE TITLE
Re-enable flakey e2e test: Settings API old api update with replace

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4361]
```
Failures:
1) Settings API old api update with replace
  Message:
    Expected 1 to be 2.
  Stack:
    Error: Failed expectation
        at utils.request.then.result (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/api/controllers/export-data-2.js:98:31)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
  Message:
    Expected [ '_id,form,patient_id,reported_date,from,contact.name,contact.parent.name,contact.parent.parent.name,contact.parent.parent.parent.name,bar,baz,foo,smang.smong,wd_array,wd_emptyString,wd_false,wd_naughtyArray,wd_naughtyString,wd_null,wd_zero' ] to equal [ '_id,form,patient_id,reported_date,from,contact.name,contact.parent.name,contact.parent.parent.name,contact.parent.parent.parent.name,bar,baz,foo,smang.smong', '"export-data-2-test-doc-3","b","abc125",1517616000000,,,,,,,"bazVal",,' ].
  Stack:
    Error: Failed expectation
        at utils.request.then.result (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/api/controllers/export-data-2.js:99:24)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ngaruko** [comment]
Fixed with https://github.com/medic/medic-webapp/pull/4570
