### ISSUE TITLE
Stabilise and re-enable e2e test

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4394]
```
Failures:
1) Reports Summary Displays correct LHS and RHS summary Concerning reports using unknown place_id
  Message:
    Failed: No element found using locator: By(css selector, #reports-list .unfiltered li .detail .lineage li:nth-child(1))
  Stack:
    NoSuchElementError: No element found using locator: By(css selector, #reports-list .unfiltered li .detail .lineage li:nth-child(1))
        at elementArrayFinder.getWebElements.then (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:851:17)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:182:7)Error
        at ElementArrayFinder.applyAction_ (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:482:23)
        at ElementArrayFinder.(anonymous function).args [as getText] (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:96:21)
        at ElementFinder.(anonymous function).args [as getText] (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:873:14)
        at getElementText (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:269:33)
        at element.getText.then (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:274:18)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
    From: Task: Run it("Concerning reports using unknown place_id") in control flow
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:94:19)
    From asynchronous test: 
    Error
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:535:5)
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:298:3)
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:6:1)
```

**Comment by ngaruko** [comment]
Fixed with https://github.com/medic/medic-webapp/pull/4570
