### ISSUE TITLE
Stabilise and re-enable flakey e2e tests: Reports Summary Displays correct LHS and RHS summary Concerning reports using patient_id

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4398]
```
Failures:
1) Reports Summary Displays correct LHS and RHS summary Concerning reports using patient_id
  Message:
    Failed: unknown error: Element <div class="summary">...</div> is not clickable at point (170, 170). Other element would receive the click: <div uib-modal-window="modal-window" class="modal fade ng-scope ng-isolate-scope in" role="dialog" index="0" animate="animate" ng-style="{'z-index': 1050 + $$topModalIndex*10, display: 'block'}" tabindex="-1" uib-modal-animation-class="fade" modal-in-class="in" modal-animation="true" style="z-index: 1050; display: block;">...</div>
      (Session info: headless chrome=65.0.3325.181)
      (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.4.0-101-generic x86_64)
  Stack:
    WebDriverError: unknown error: Element <div class="summary">...</div> is not clickable at point (170, 170). Other element would receive the click: <div uib-modal-window="modal-window" class="modal fade ng-scope ng-isolate-scope in" role="dialog" index="0" animate="animate" ng-style="{'z-index': 1050 + $$topModalIndex*10, display: 'block'}" tabindex="-1" uib-modal-animation-class="fade" modal-in-class="in" modal-animation="true" style="z-index: 1050; display: block;">...</div>
      (Session info: headless chrome=65.0.3325.181)
      (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.4.0-101-generic x86_64)
        at Object.checkLegacyResponse (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/error.js:505:15)
        at parseHttpResponse (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/http.js:509:13)
        at doSend.then.response (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/http.js:440:13)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:182:7)
    From: Task: WebElement.click()
        at thenableWebDriverProxy.schedule (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
        at WebElement.schedule_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:1921:25)
        at WebElement.click (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:2002:17)
        at actionFn (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:94:34)
        at Array.map (<anonymous>)
        at actionResults.getWebElements.then (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:484:67)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2813:27)Error
        at ElementArrayFinder.applyAction_ (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:482:23)
        at ElementArrayFinder.(anonymous function).args [as click] (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:96:21)
        at ElementFinder.(anonymous function).args [as click] (/home/travis/build/medic/medic-webapp/node_modules/protractor/lib/element.ts:873:14)
        at browser.wait.then (/home/travis/build/medic/medic-webapp/tests/protractor/helper.js:67:19)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
    From: Task: Run it("Concerning reports using patient_id") in control flow
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:94:19)
    From asynchronous test: 
    Error
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:299:5)
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:298:3)
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:6:1)
2) Reports Summary Displays correct LHS and RHS summary Concerning reports using patient name
  Message:
    Expected 'Maria Pecan' to be 'George'.
  Stack:
    Error: Failed expectation
        at saveReport.then.then.then (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:439:92)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:182:7)
  Message:
    Expected 'REF_REF' to be 'NAM_NAM'.
  Stack:
    Error: Failed expectation
        at saveReport.then.then.then (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:440:75)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:182:7)
  Message:
    Expected 'TAG Place' to be 'Bob Place'.
  Stack:
    Error: Failed expectation
        at expected.forEach (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:225:10)
        at Array.forEach (<anonymous>)
        at testListLineage (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:223:14)
        at saveReport.then.then.then (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:442:11)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
  Message:
    Expected 'Maria Pecan' to be 'George'.
  Stack:
    Error: Failed expectation
        at saveReport.then.then.then (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:445:83)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:182:7)
  Message:
    Expected 'REF_REF' to be 'NAM_NAM'.
  Stack:
    Error: Failed expectation
        at saveReport.then.then.then (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:446:83)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:182:7)
  Message:
    Expected 'TAG Place' to be 'Bob Place'.
  Stack:
    Error: Failed expectation
        at expected.forEach (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:232:10)
        at Array.forEach (<anonymous>)
        at testSummaryLineage (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:230:14)
        at saveReport.then.then.then (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/reports-subject.js:447:11)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
```

**Comment by ngaruko** [comment]
Fixed with https://github.com/medic/medic-webapp/pull/4570
