### ISSUE TITLE
The due_tasks schedule fails trying to build the template context

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4453]
When messages are ready to send we persist them on the doc so they won't change if the configuration is updated after they're sent. As part of this we [build the template context including the patient doc](https://github.com/medic/medic-webapp/blob/2.15.x/sentinel/schedule/due_tasks.js#L13). This code attempts to hydrate the patient using the shortcode but the lineage function expects a UUID. This fails when nano can't find the doc by id.

```
2018-04-19T21:37:14.567Z - error: error: Error running tasks: {"message":"missing","stack":"Error: missing
    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)","name":"Error","error":"not_found","reason":"missing","scope":"couch","statusCode":404,"request":{"method":"GET","headers":{"content-type":"application/json","accept":"application/json"},"uri":"http://XXXXXX:XXXXXX@localhost:5984/medic/87865"},"headers":{"date":"Thu, 19 Apr 2018 21:37:14 GMT","content-type":"application/json","cache-control":"must-revalidate","statusCode":404,"uri":"http://XXXXXX:XXXXXX@localhost:5984/medic/87865"},"errid":"non_200","description":"couch returned 404"}
```

Add code to resolve the patient UUID from the patient shortcode before hydration.

**Comment by abbyad** [comment]
In case someone else runs into this, the symptom seen is that scheduled messages stay as `scheduled`, never moving to `pending` even when they are due to be sent.

**Comment by garethbowen** [comment]
Code review please @rmhowe

**Comment by garethbowen** [comment]
Backported to `2.15.x`

**Comment by abbyad** [comment]
Testing this on `beta.dev` running `2.15.0-beta.10` and I can't see the error in the logs, but do see the symptom described in https://github.com/medic/medic-webapp/issues/4453#issuecomment-383096990 [[example report](https://beta.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/c82d544f4b8ed1a1c9db6d14803a0460)].

I do not see any logging that `due_tasks.js` is running. The last time I see the `info: checking schedule again in 5 minutes` in log is just before the update from beta 9 to beta 10. I restarted sentinel, but still don't see it running.

@henokgetachew are you able to check if sentinel is running properly on beta.dev? @garethbowen, if you prefer we can open a separate issue for the symptom.

**Comment by garethbowen** [comment]
@abbyad If you don't see "info: checking schedule again in 5 minutes" then it's a different issue from the one I "fixed". I can have another look.

**Comment by garethbowen** [comment]
I've fixed an issue with the backport. There was another issue where a patient was his own father causing an infinite loop which I fixed in data. #4476 also came up, but that's unrelated. Long story short, this is ready for AT again...

**Comment by abbyad** [comment]
I see this working well in `2.15.0-beta.11`. Here is [example doc](https://beta-old.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/dd32e2d08c7def675f5de6ab96022d9e):

![image](https://user-images.githubusercontent.com/789512/39435818-5e772e10-4c6a-11e8-8eca-b1f51df263ed.png)

![image](https://user-images.githubusercontent.com/789512/39435851-75184e06-4c6a-11e8-90c8-0f673ae4b2d8.png)

![image](https://user-images.githubusercontent.com/789512/39435879-8371f510-4c6a-11e8-963e-47dacc6a56c4.png)

Note that only one message gets marked as pending per group per 5 minute cycle. I think that is acceptable for our use cases, but worth noting. Will open a separate issue to deal with this at an appropriate time, or at least document the behaviour.
