### ISSUE TITLE
Horti crashes on subsequent upgrade

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#4800]
Each time an app (api or sentinel) is updated, horti creates a symlink to the previous running version (called `old`).
When doing multiple upgrades, this `old` symlink is not removed prior to attempting to write it again resulting in the following fatal error (which crashes horti):

```
  horti:debug Primary ddoc written +3s
Updating symlinks for changed apps… [ { name: 'medic-api',
    attachmentName: 'medic-api-0.1.0.tgz',
    digest: 'md5-wmKqGbAc5bAKugPtyXZdKQ==',
    deployPath: [Function: deployPath] } ]
********FATAL********
{ Error: EEXIST: file already exists, symlink '/home/user/.horticulturalist/deployments/medic-api/md5-vU2CqBOkCe+HMwOM3oCb+w==' -> '/home/user/.horticulturalist/deployments/medic-api/old'
    at Object.fs.symlinkSync (fs.js:1031:18)
    at Promise.all.changedApps.map.app (/usr/lib/node_modules/horticulturalist/src/install/deploySteps.js:112:14)
    at Array.map (<anonymous>)
    at updateSymlink (/usr/lib/node_modules/horticulturalist/src/install/deploySteps.js:105:36)
    at Promise.resolve.then.then (/usr/lib/node_modules/horticulturalist/src/install/deploySteps.js:153:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  errno: -17,
  code: 'EEXIST',
  syscall: 'symlink',
  path: '/home/user/.horticulturalist/deployments/medic-api/md5-vU2CqBOkCe+HMwOM3oCb+w==',
  dest: '/home/user/.horticulturalist/deployments/medic-api/old' }
```

**Comment by dianabarsan** [comment]
This is happening on `gamma.dev`, hindering the upgrade process:

```
[2018-09-18 13:08:14] Updating symlinks for changed apps… [ { name: 'medic-api',
[2018-09-18 13:08:14]     attachmentName: 'medic-api-0.1.0.tgz',
[2018-09-18 13:08:14]     digest: 'md5-fo+TD94akuzeuzwonWe4jA==',
[2018-09-18 13:08:14]     deployPath: [Function: deployPath] },
[2018-09-18 13:08:14]   { name: 'medic-sentinel',
[2018-09-18 13:08:14]     attachmentName: 'medic-sentinel-0.1.0.tgz',
[2018-09-18 13:08:14]     digest: 'md5-+VOtZFHYJ+fq+8yNzoLXVg==',
[2018-09-18 13:08:14]     deployPath: [Function: deployPath] } ]
********FATAL********
{ Error: EEXIST: file already exists, symlink '/srv/software/medic-api/md5-YDhTQXDzcE+hUZM1imfPA==' -> '/srv/software/medic-api/old'
    at Object.fs.symlinkSync (fs.js:1014:18)
    at Promise.all.changedApps.map.app (/srv/software/horticulturalist/node_modules/horticulturalist/src/install/deploySteps.js:112:14)
    at Array.map (<anonymous>)
    at updateSymlink (/srv/software/horticulturalist/node_modules/horticulturalist/src/install/deploySteps.js:105:36)
    at Promise.resolve.then.then (/srv/software/horticulturalist/node_modules/horticulturalist/src/install/deploySteps.js:153:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -17,
  code: 'EEXIST',
  syscall: 'symlink',
  path: '/srv/software/medic-api/md5-YDhTQXDzcE+hUZM1imfPA==',
  dest: '/srv/software/medic-api/old' }
[2018-09-18 13:08:17] Starting Horticulturalist 0.12.6 daemon in Medic OS mode
```

**Comment by garethbowen** [comment]
Let's get this fixed.

**Comment by ngaruko** [comment]
LGTM.
Tested on `gamma`, v3.X
