### ISSUE TITLE
Fix flakey test: Reports Summary Displays correct LHS and RHS summary Concerning reports using patient_id

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#5038]
We're getting a lot of this...

```
Failures:
1) Reports Summary Displays correct LHS and RHS summary Concerning reports using patient_id
  Message:
[31m    Failed: Wait timed out after 10002ms[0m
  Stack:
    TimeoutError: Wait timed out after 10002ms
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2201:17
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1376:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2927:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:668:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:189:7)
    From: Task: <anonymous wait>
        at scheduleWait (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2188:20)
        at ControlFlow.wait (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2517:12)
        at thenableWebDriverProxy.wait (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
        at run (/home/travis/build/medic/medic-webapp/node_modules/protractor/built/browser.js:59:33)
        at ProtractorBrowser.to.(anonymous function) [as wait] (/home/travis/build/medic/medic-webapp/node_modules/protractor/built/browser.js:67:16)
        at saveReport.then.then.then (/home/travis/build/medic/medic-webapp/tests/e2e/reports-subject.js:323:19)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1376:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2927:27)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:668:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:189:7)
    From: Task: Run it("Concerning reports using patient_id") in control flow
        at UserContext.<anonymous> (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:94:19)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:64:48
        at ControlFlow.emit (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/events.js:62:21)
        at ControlFlow.shutdown_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2674:10)
        at shutdownTask_.MicroTask (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2599:53)
        at MicroTask.asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2728:9)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:668:7
        at <anonymous>
    From asynchronous test: 
    Error
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/e2e/reports-subject.js:293:5)
        at Suite.describe (/home/travis/build/medic/medic-webapp/tests/e2e/reports-subject.js:292:3)
        at Object.<anonymous> (/home/travis/build/medic/medic-webapp/tests/e2e/reports-subject.js:6:1)
        at Module._compile (module.js:653:30)
        at Object.Module._extensions..js (module.js:664:10)
        at Module.load (/home/travis/build/medic/medic-webapp/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
        at tryModuleLoad (module.js:506:12)
        at Function.Module._load (module.js:498:3)
        at Module.require (module.js:597:17)
        at require (internal/module.js:11:18)
        at /home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:93:5
        at Array.forEach (<anonymous>)
        at Jasmine.loadSpecs (/home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:92:18)
        at Jasmine.execute (/home/travis/build/medic/medic-webapp/node_modules/jasmine/lib/jasmine.js:197:8)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/frameworks/jasmine.js:132:15
        at Function.promise (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:682:9)
        at /home/travis/build/medic/medic-webapp/node_modules/protractor/built/frameworks/jasmine.js:104:14
        at _fulfilled (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:796:13)
        at /home/travis/build/medic/medic-webapp/node_modules/q/q.js:604:44
        at runSingle (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:137:13)
        at flush (/home/travis/build/medic/medic-webapp/node_modules/q/q.js:125:13)
        at _combinedTickCallback (internal/process/next_tick.js:132:7)
        at process._tickCallback (internal/process/next_tick.js:181:9)

192 specs, 1 failure
```

Examples:

- https://travis-ci.org/medic/medic-webapp/builds/459991720?utm_source=slack&utm_medium=notification
- https://travis-ci.org/medic/medic-webapp/builds/459991974?utm_source=slack&utm_medium=notification
- https://travis-ci.org/medic/medic-webapp/builds/459994261?utm_source=slack&utm_medium=notification
- https://travis-ci.org/medic/medic-webapp/builds/459994403?utm_source=slack&utm_medium=notification

I just noticed in these builds it's always Node 8 that fails...

Possibly related to #4351

**Comment by garethbowen** [comment]
Merged!
