### ISSUE TITLE
DOMException crash leaves users stuck at loading spinner

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-webapp#5045]
```
"Possibly unhandled rejection: {"stack":"Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.\n at Error (native)\n  
at sn (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1652539)\n  
at St.t._get (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1663892)\n  
at St.<anonymous> (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1726611)\n  
at St.<anonymous> (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1623261)\n  
at St.<anonymous> (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:391745)\n  
at https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1622619\n  
at St.<anonymous> (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1622537)\n  
at St.get (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:391745)\n  
at St.get (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:14577)" 
```

https://github.com/medic/medic-projects/issues/4293

Repro steps, specific affected versions, underlying cause, and vector to fix this crash remain unknown.
There is an easy low-pain low-cost workaround (refreshing the browser).
The crux is identifying when the workaround should be applied as there is no UI indication when the crash occurs.

This issue is particularly bad in MoH-Siaya running 2.14.

A proposed mitigation is to register an OnError hook which watches for the crash, then prompts the user to refresh the page when it occurs.

**Comment by garethbowen** [comment]
I've scheduled this for 3.4.0 to get some attention - we may want to backport this to a previous version but we can decide that once we have a solution.

**Comment by garethbowen** [comment]
Possibly related: #4184

**Comment by garethbowen** [comment]
I've backported this to `3.3.x` to get it out a little sooner.

**Comment by newtewt** [comment]
@kennsippell  @garethbowen  any thoughts on AT for this. Seems like there isn't a way to force the app into the state to show the modal since we aren't 100% on reproducing the issue.

**Comment by kennsippell** [comment]
@newtewt That's correct, it is a hard error to nail down. But to simulate the experience you can copy/paste this into the DevTools console and you can test the experience.

```   const triggerPouchDbDOMException = () => { 
       let db = new window.PouchDB('test', { auto_compaction: true }); 
       const write = i => {
         db.put({ _id: i + 'a', bar: 'bar' }).then(() => {
           write(i + 1); 
         });
       };
       write(0); 
       db.destroy(); 
       db = new window.PouchDB('test', { auto_compaction: true }); 
   };
triggerPouchDbDOMException();```

**Comment by newtewt** [comment]
Cool looks good in browser and on phone.

**Comment by kennsippell** [comment]
This underlying issue continues to manifest as feedback document with following signature:

```
Uncaught (in promise): InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Error (native)
    at Tn (https://pih-malawi.app.medicmobile.org/main.js:1:1814303)
    at fr.W._getLocal (https://pih-malawi.app.medicmobile.org/main.js:1:1828308)
    at fr. (https://pih-malawi.app.medicmobile.org/main.js:1:1789893)
    at fr. (https://pih-malawi.app.medicmobile.org/main.js:1:1767638)
    at fr. (https://pih-malawi.app.medicmobile.org/main.js:1:1128625)
    at https://pih-malawi.app.medicmobile.org/main.js:1:1766941
    at new H (https://pih-malawi.app.medicmobile.org/polyfills-es5.js:1:119847)
    at fr. (https://pih-malawi.app.medicmobile.org/main.js:1:1766840)
    at fr.get (https://pih-malawi.app.medicmobile.org/main.js:1:1128625)
```

Rate appears to be about 1 crash/month for production PiH instance.

**Comment by kennsippell** [comment]
Moving this comment from private issue into public issue for reference
https://github.com/medic/medic-projects/issues/4293#issuecomment-440660198
@kennsippell on Nov 21, 2018

_TL; DR;  I don't know how to fix this. But if we just alert the user when it happens and prompt them to work around it (refresh the page), then Siaya will be a better place._


In focus groups and interviews this week, Moh-Siaya CHVs, CHAs, and and CFPs repeatedly listed "long loading" as the top issue impeding work on the Medic app.  
 
I believe "long loading" to be a combination of two issues which are hard for users to distinguish 1) general known performance problems causing high load times (#3208) and 2) an internal crash which results in an application hang (tracked by this issue).

App users cannot distinguish between the two issues because the crash and hang happen silently. It is my opinion that the frustration from intermittent hangs makes the performance issues seem more severe. 
 
## Bug Details
**Environment**  
* App 2.14.4, Android app 0.3.6, DDoc Version 300, Client DDoc Version 144 – Huawei Y541 
* Chrome 70 running MoH.dev App version 2.16.1 - Lenovo Laptop <Await specs from Simon Mbae>
* 3 additional repros tracked in [this spreadsheet](https://docs.google.com/spreadsheets/d/1pn5fuXpGnsxsG26KYKoUtkfG1_PxvEDj5xO-1yQwOO0)

**User Experience** - After the crash, all read and write operations from PouchDB silently fail. UI shows "loading..." icon.
**Repro Steps** - The issue is intermittent in nature, without clear repro steps. Both @smbuthia and @billwambua have gone to extensive lengths to reproduce. The repro steps are unclear. CHWs report that this can happen when loading any form (create family, create contact, new immunization record, etc.). 
**Audience** - This affects an unknown cohort of _offline users_ across diverse hardware classes (old phones, new phones, and laptops). 
**Impact** - I believe we should remove the Performance tag. Although users are complaining that the experience is "slow", this issue tracks a complete hang which prevents page load from ever completing.  (@derickl)
**Cause** - Still unknown. Some clues below. 
**Stack Traces** - The bug so far has three unique crash stacks occurring in PouchDB.get() and PouchDB.changes(). See below. 
**Work around** – Restarting the app or refreshing the Chrome window. So far, I have not encountered a case which was not fixed by this. I don't believe there is any need to clear cache or re-sync data, though that seems to be a common procedure here. 

## Analysis

Repro steps, specific version, underlying cause, and vector to fix this bug remain unknown. 
There is an easy low-pain low-cost workaround. 
The crux is identifying when the workaround should be applied. (The user needs to wait an hour until their frustration breaks them.)
If the user were alerted that the page is broken and will never load, instead of being shown the animated "loading spinner" the severity of this issue would be greatly reduced. 

## A Proposed Mitigation

Register an OnError hook which watches for "Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing" and prompts the user to refresh the page when it occurs. Bonus points: instrument how often this is happening and to whom?
 
# Investigation Details 
The issue affects a broad but unknown cohort of users at an unknown frequency, potentially up to all offline users within the project. 
At this time, all confirmed cases are within the moh-kenya-siaya project. 
The repro steps are unclear. CHWs report that this can happen when loading any form (create family, create contact, new immunization record, etc.). 
The bug so far has multiple unique crash stacks occurring in PouchDB.get() and PouchDB.changes(). 

**User Profile 1 – CHW** 
App 2.14.4 
Android app 0.3.6 
DDoc Version 300 
Client DDoc Version 144 
Gracead 
653 docs 
Android 4.4.2 
HUAWEI Y541-U02 
4CORE 1.2 GHz 
1GB RAM 
Linux 3.10.17 
 
``` 
"Possibly unhandled rejection: {"stack":"Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.\n at Error (native)\n  
at sn (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1652539)\n  
at St.t._get (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1663892)\n  
at St.<anonymous> (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1726611)\n  
at St.<anonymous> (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1623261)\n  
at St.<anonymous> (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:391745)\n  
at https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1622619\n  
at St.<anonymous> (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1622537)\n  
at St.get (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:391745)\n  
at St.get (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:14577)" 
``` 
and
```
"Possibly unhandled rejection: {"stack":"Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.\n at Error (native)\n  
at sn (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1652539)\n  
at bn (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1660760)\n  
at St.t._changes (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1665060)\n  
at ft.doChanges (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1722211)\n  
at https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1721454\n  
at Object.ye [as validate] (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1643733)\n  
at ft.validateChanges (https:1//moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1721412)\n  
at new ft (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1632597)\n  
at St.xt.changes (https://moh-kenya-siaya.app.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1728970)"}" 
```

**User Profile 2 – Laptop** 
This crash was reported on Simon Mbae's laptop at Medic Mobile Africa Regional Office while logged in as a CHW offline user. 
<Awaiting his scenario details and laptop specs> 
Windows 10, Chrome 70, moh-kenya-siaya.dev running App version 2.16.1. Offline user account.
 
``` 
inbox.js:3 Error generating contact view model DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
   at on (https://moh-kenya-siaya.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1673825)
   at St.t._get (https://moh-kenya-siaya.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1685199)
   at St.<anonymous> (https://moh-kenya-siaya.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1747393)
   at St.<anonymous> (https://moh-kenya-siaya.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1644639)
   at St.<anonymous> (https://moh-kenya-siaya.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:394757)
   at https://moh-kenya-siaya.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1643993
   at new Promise (<anonymous>)
   at St.<anonymous> (https://moh-kenya-siaya.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:1643909)
   at St.get (https://moh-kenya-siaya.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:394757)
   at St.get (https://moh-kenya-siaya.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/inbox.js:3:14632) Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
``` 

All stacks are fully within Pouch - There is no user code in this stack to give us a clue as to what we are doing to trigger this. 
`St` in the above is AbstractPouchDB object.  
`sn` is PouchDb's internal openTransactionSafely() 

pouchdb/pouchdb#3415 offers a few clues since several failure patterns are identified: 
• One sketchy [report](https://github.com/pouchdb/pouchdb/issues/3415#issuecomment-293000755) of live synchronization causing this intermittently with a bulkDocs call (possibly relevant)
• Using two pouchdb objects to access the same database (not relevant?)
• Calling PouchDB.remove() and accessing the removed doc without waiting for removal to complete (not relevant?) 
• Using the `new pouchdb().then()` interface (not relevant?) 
• Destroying a database, recreating it, and writing to it (not relevant?)

**Comment by garethbowen** [comment]
@kennsippell It looks like there's still improvements to be made here - would you mind creating a new issue with this info?

**Comment by kennsippell** [comment]
https://github.com/medic/cht-core/issues/8149
