### ISSUE TITLE
Cannot start API after changes to the translation messages format

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#5062]
The changes in https://github.com/medic/medic-webapp/commit/b6a98625727cc5e8a0fde77c9848bfe8235863e7 seem to expect a different format for the ddoc than existed in previous versions.  This format is fixed in a migration, but the migration would not be run until after api has already tried to read the translation configuration in `config.load()`.

The following error is seen at api startup:

```
15:18:01 api.1        |  2018-12-04 14:18:01 INFO: DDoc extraction completed successfully 
15:18:01 api.1        |  2018-12-04 14:18:01 INFO: Loading configuration… 
15:18:01 api.1        |  2018-12-04 14:18:01 INFO: Configuration loaded successfully 
15:18:01 api.1        |  2018-12-04 14:18:01 INFO: Merging translations… 
15:18:07 api.1        |  >> /home/user/workspace/medic/webapp/api/src/config.js:83
15:18:07 api.1        |  >>       const values = Object.assign(row.doc.generic, row.doc.custom || {});
15:18:07 api.1        |  >>                             ^
15:18:07 api.1        |  >> 
15:18:07 api.1        |  >> TypeError: Cannot convert undefined or null to object
15:18:07 api.1        |  >>     at Function.assign (<anonymous>)
15:18:07 api.1        |  >>     at result.rows.forEach.row (/home/user/workspace/medic/webapp/api/src/config.js:83:29)
15:18:07 api.1        |  >>     at Array.forEach (<anonymous>)
15:18:07 api.1        |  >>     at db.medic.query (/home/user/workspace/medic/webapp/api/src/config.js:82:17)
15:18:07 api.1        |  >>     at /home/user/workspace/medic/webapp/api/node_modules/pouchdb-mapreduce-utils/lib/index.js:52:9
15:18:07 api.1        |  >>     at _combinedTickCallback (internal/process/next_tick.js:131:7)
15:18:07 api.1        |  >>     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
15:18:07 api.1        |  [nodemon] app crashed - waiting for file changes before starting...
```

A potential fix for this appears to be:

```
--- a/api/src/config.js
+++ b/api/src/config.js
@@ -80,7 +80,7 @@ const loadTranslations = () => {
       return;
     }
     result.rows.forEach(row => {
-      const values = Object.assign(row.doc.generic, row.doc.custom || {});
+      const values = Object.assign(row.doc.generic || {}, row.doc.custom || {});
       translationCache[row.doc.code] = translationUtils.loadTranslations(values);
     });
   });
diff --git a/shared-libs/translation-utils/src/translation-utils.js b/shared-libs/translation-utils/src/translation-utils.js
index e4c9a9c83..558958eba 100644
--- a/shared-libs/translation-utils/src/translation-utils.js
+++ b/shared-libs/translation-utils/src/translation-utils.js
@@ -3,7 +3,7 @@ const KEY_REGEX = /\${([^}\r\n]*)}/g;
 module.exports = {
   loadTranslations: values => {
     Object.keys(values).forEach(key => {
-      values[key] = values[key].replace(KEY_REGEX, (match, key) => values[key] || ('${' + key + '}'));
+      values[key] = values[key] && values[key].replace(KEY_REGEX, (match, key) => values[key] || ('${' + key + '}'));
     });
     return values;
   }

```

However, it's not clear to me if this leaves API in a consistent state or not.

**Comment by garethbowen** [comment]
@wtekeu Please have a look at this when you get a chance.

**Comment by alxndrsn** [comment]
It doesn't look like this is fixed on latest `master` (7f53681075536362b5073a6850361b26762b0415):
```
15:19:25 api.1        |  2018-12-11 14:19:25 INFO: Merging translations… 
15:19:26 api.1        |  >> /home/user/workspace/medic/webapp/api/node_modules/@medic/translation-utils/src/translation-utils.js:6
15:19:26 api.1        |  >>       values[key] = values[key].replace(KEY_REGEX, (match, key) => values[key] || ('${' + key + '}'));
15:19:26 api.1        |  >>                                 ^
15:19:26 api.1        |  >> 
15:19:26 api.1        |  >> TypeError: Cannot read property 'replace' of null
15:19:26 api.1        |  >>     at Object.keys.forEach.key (/home/user/workspace/medic/webapp/api/node_modules/@medic/translation-utils/src/translation-utils.js:6:33)
15:19:26 api.1        |  >>     at Array.forEach (<anonymous>)
15:19:26 api.1        |  >>     at Object.loadTranslations (/home/user/workspace/medic/webapp/api/node_modules/@medic/translation-utils/src/translation-utils.js:5:25)
15:19:26 api.1        |  >>     at result.rows.forEach.row (/home/user/workspace/medic/webapp/api/src/config.js:86:57)
15:19:26 api.1        |  >>     at Array.forEach (<anonymous>)
15:19:26 api.1        |  >>     at db.medic.query (/home/user/workspace/medic/webapp/api/src/config.js:82:17)
15:19:26 api.1        |  >>     at /home/user/workspace/medic/webapp/api/node_modules/pouchdb-mapreduce-utils/lib/index.js:52:9
15:19:26 api.1        |  >>     at _combinedTickCallback (internal/process/next_tick.js:131:7)
15:19:26 api.1        |  >>     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by garethbowen** [comment]
Thanks @wtekeu that's fixed the library. Now I think we just need to bump the dependencies in the package-lock to 1.0.1, right?

**Comment by garethbowen** [comment]
Merged and ready for AT again. Thanks!

**Comment by ngaruko** [comment]
There are errors around translations that eventually crash the app. It might be either a result of this issue or #4599  . I am leaving both open for now while we investigate which one is the culprit @garethbowen 
![image](https://user-images.githubusercontent.com/6979995/49984389-5de2ef00-ff9a-11e8-97eb-a645f8888be8.png)

**Comment by ngaruko** [comment]
LGTM. The app does not crash as in previous versions. Closing this.
