### ISSUE TITLE
kanso push fails with minify flag

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#791]
Kanso push fails with minify, this causes the auto-push to market to fail during builds.

    kanso push --minify http://admin:123qwe@localhost:5984/medic

This appears to be a bug in node and/or uglifyjs. The push fails during an uglifyjs call on line 17 in packages/modules/build/attachment.js:

    return pro.gen_code(ast);   // compressed code here

A stack trace shows the last call within node:

Trace
    at Object.exports.error (/Users/mandric/local/lib/node_modules/kanso/lib/logger.js:106:13)
    at process.<anonymous> (/Users/mandric/local/lib/node_modules/kanso/lib/logger.js:140:13)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
Error: Maximum call stack size exceeded
Failed

Increasing the stack size works on my mac:

    node --stack_size=100000 ~/local/lib/node_modules/kanso/bin/kanso push --minify http://admin:123qwe@localhost:5984/medic

Noticed uglifyjs was pretty old in the modules package (1.2.2).  When I upgraded it to latest (2.4.16) I get a different error which also is related to node:

Trace
    at Object.exports.error (/Users/mandric/local/lib/node_modules/kanso/lib/logger.js:106:13)
    at process.<anonymous> (/Users/mandric/local/lib/node_modules/kanso/lib/logger.js:140:13)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
Error: ReferenceError: makePredicate is not defined
    at Object.<anonymous> (/Users/mandric/tmp/medic-webapp/packages/modules/node_modules/uglify-js/lib/parse.js:53:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mandric/tmp/medic-webapp/packages/modules/build/attachment.js:14:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
Failed

parse.js uses a makePredicate global which doesn’t exist in node 0.10?  Giving up for now since I think we can use the node stack_size flag as a workaround.

**Comment by garethbowen** [comment]
`makePredicate` is defined in https://github.com/mishoo/UglifyJS2/blob/master/lib/utils.js#L220 so I think we could get it to work, but I think the workaround you have is fine for now.

Once we move to angular completely we can call uglify directly from grunt before pushing to market.
