### ISSUE TITLE
500 error when searching with lots of parameters

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#836]
When requesting this URL...

```
http://localhost:5988/api/v1/fti/contacts?include_docs=true&index=contacts&limit=50&q=%7B%22$operands%22:%5B%7B%22type%22:%5B%22person%22,%22clinic%22,%22health_center%22,%22district_hospital%22%5D%7D,%7B%22clinic%22:%5B%22eeb17d6d-5dde-c2c0-8a899c4fe9db6ba9%22,%22eeb17d6d-5dde-c2c0-3df0f0b8987ac49a%22,%22eeb17d6d-5dde-c2c0-0dc9eaca81b09913%22,%22eeb17d6d-5dde-c2c0-ef85d050fbdd468e%22,%22eeb17d6d-5dde-c2c0-fefc7d02cf1e5bec%22,%22eeb17d6d-5dde-c2c0-724b904b3a68d812%22,%22eeb17d6d-5dde-c2c0-622433ddd9dbbd0f%22,%22eeb17d6d-5dde-c2c0-c4a0ab210dff308c%22,%22eeb17d6d-5dde-c2c0-9d573191f1c8654d%22,%22eeb17d6d-5dde-c2c0-e07e01e14de82f03%22,%22eeb17d6d-5dde-c2c0-823ae668cf49a1d8%22,%22eeb17d6d-5dde-c2c0-84dddf50bf45d66a%22,%22eeb17d6d-5dde-c2c0-594458ab2f54fc87%22,%22eeb17d6d-5dde-c2c0-a4fd2ca66f48f875%22,%22eeb17d6d-5dde-c2c0-7ff6e012a032d623%22,%22eeb17d6d-5dde-c2c0-48ac53f275043126%22,%22eeb17d6d-5dde-c2c0-90a0599e5db9ea63%22,%22eeb17d6d-5dde-c2c0-9bdc86d5b9cde853%22,%22eeb17d6d-5dde-c2c0-d5b11d7c38dad178%22,%22eeb17d6d-5dde-c2c0-e0a30a7d7343ccbd%22,%22eeb17d6d-5dde-c2c0-fe58e289aa1012ea%22,%22eeb17d6d-5dde-c2c0-2a02f9a2919e2672%22,%22eeb17d6d-5dde-c2c0-78a01a3eb3c621a3%22,%22eeb17d6d-5dde-c2c0-30ca5d9198f463d5%22,%22eeb17d6d-5dde-c2c0-f8d8f3521e8f1920%22,%22eeb17d6d-5dde-c2c0-32fba73f77cfe79c%22,%22eeb17d6d-5dde-c2c0-834859e2b3d57090%22,%22eeb17d6d-5dde-c2c0-6b8ff6a88a8f906e%22,%22eeb17d6d-5dde-c2c0-1fdaa057fbe30e52%22,%22eeb17d6d-5dde-c2c0-c7a7e21aa13371ae%22,%22eeb17d6d-5dde-c2c0-ec920dd5f0bfe0ad%22,%22eeb17d6d-5dde-c2c0-0eef596b61b3c2b5%22,%22eeb17d6d-5dde-c2c0-57625ebdfa670884%22,%22eeb17d6d-5dde-c2c0-9dbdfee90119e01e%22,%22eeb17d6d-5dde-c2c0-b98afefb3d972270%22,%22eeb17d6d-5dde-c2c0-147075e28dc8c3ee%22,%22eeb17d6d-5dde-c2c0-ffca8436171c9c46%22,%22eeb17d6d-5dde-c2c0-7de966dc2dc1dbdf%22,%22eeb17d6d-5dde-c2c0-7dd9799e6503e66d%22,%22eeb17d6d-5dde-c2c0-bc97f2c07f0c0c4b%22,%22eeb17d6d-5dde-c2c0-faeb16660c32dea2%22,%22eeb17d6d-5dde-c2c0-82ba0dbeea71b53b%22,%22eeb17d6d-5dde-c2c0-3540337fccd4421f%22,%22eeb17d6d-5dde-c2c0-32946e22d4118e20%22,%22eeb17d6d-5dde-c2c0-50752be729346bf5%22,%22eeb17d6d-5dde-c2c0-9775c43b49f96fd4%22,%22eeb17d6d-5dde-c2c0-7a93675cf15c9745%22,%22eeb17d6d-5dde-c2c0-8130ce51ca79daca%22,%22eeb17d6d-5dde-c2c0-37aeb5a7f8545762%22,%22eeb17d6d-5dde-c2c0-fbd07f4028bc4233%22,%22eeb17d6d-5dde-c2c0-482f11350360ef80%22,%22eeb17d6d-5dde-c2c0-d6ad35ed600e893a%22,%22eeb17d6d-5dde-c2c0-8cc65e8e694ef277%22,%22eeb17d6d-5dde-c2c0-20267acea7d760db%22,%22eeb17d6d-5dde-c2c0-1ce2732b8f2039b6%22,%22eeb17d6d-5dde-c2c0-1d287ae6fba05c25%22,%22eeb17d6d-5dde-c2c0-187fec6ec7bc3493%22,%22eeb17d6d-5dde-c2c0-44bd8ac9132072be%22,%22eeb17d6d-5dde-c2c0-b60c2ef8af212170%22,%22eeb17d6d-5dde-c2c0-ccf53729514d1ae8%22,%22eeb17d6d-5dde-c2c0-cced637d73961a07%22,%22eeb17d6d-5dde-c2c0-a56741c4e8ea1bb3%22,%22eeb17d6d-5dde-c2c0-ff2b365983be38b9%22,%22eeb17d6d-5dde-c2c0-2ecb7b280392fae8%22,%22eeb17d6d-5dde-c2c0-6f40c138c145c3f4%22,%22eeb17d6d-5dde-c2c0-8049b4903e2fb0a5%22,%22eeb17d6d-5dde-c2c0-be4c014ec3c9f9d7%22,%22eeb17d6d-5dde-c2c0-8aefed3ad9fbb039%22,%22b66c31a2-34c4-4a24-3ceaea47f7b49f99%22,%22dcc33d76-2554-8375-3b010f2452c59e17%22,%22eeb17d6d-5dde-c2c0-a0f2a91e2d232c51%22,%22eeb17d6d-5dde-c2c0-f5c5e2f4cbd4a1a0%22,%22eeb17d6d-5dde-c2c0-3050e81679ced9a7%22,%22eeb17d6d-5dde-c2c0-a910b46967d475c4%22,%22eeb17d6d-5dde-c2c0-946be1d1ab91a4d8%22,%22eeb17d6d-5dde-c2c0-7af8904ff2d2b598%22,%22eeb17d6d-5dde-c2c0-b86d15b08482231c%22,%22eeb17d6d-5dde-c2c0-4c27c0e61b0fa77e%22,%22eeb17d6d-5dde-c2c0-6e8490ae24b32468%22,%22eeb17d6d-5dde-c2c0-6178d6702c87602c%22,%22eeb17d6d-5dde-c2c0-c84f683639d72d13%22,%22eeb17d6d-5dde-c2c0-8571f62acc3d4246%22,%22eeb17d6d-5dde-c2c0-cf50a72390596c8c%22,%22eeb17d6d-5dde-c2c0-729ea80b81c26f76%22,%22eeb17d6d-5dde-c2c0-75deec46e9ac8972%22,%22eeb17d6d-5dde-c2c0-09681f91f200a487%22,%22eeb17d6d-5dde-c2c0-a6d54e1cebad8dca%22,%22eeb17d6d-5dde-c2c0-7fce637559568b14%22,%22eeb17d6d-5dde-c2c0-e493852590733457%22,%22eeb17d6d-5dde-c2c0-23f13cf2d5c377a7%22,%22eeb17d6d-5dde-c2c0-183a1e2943958f44%22,%22eeb17d6d-5dde-c2c0-3083f0bd4dd21c39%22,%22eeb17d6d-5dde-c2c0-72f331fe208c6274%22,%22eeb17d6d-5dde-c2c0-e6624290b7bf9fe2%22,%22eeb17d6d-5dde-c2c0-b724e98c011ca986%22,%22eeb17d6d-5dde-c2c0-a9a2884ea26918d3%22,%22eeb17d6d-5dde-c2c0-054362f08f1517d6%22,%22eeb17d6d-5dde-c2c0-1147975108065aa1%22,%22eeb17d6d-5dde-c2c0-75d064a9c603259d%22,%22eeb17d6d-5dde-c2c0-fe8ea153a770408a%22,%22eeb17d6d-5dde-c2c0-f54aa2701446c2d9%22,%22eeb17d6d-5dde-c2c0-22ee673834df125f%22,%22eeb17d6d-5dde-c2c0-419665dcd222da68%22,%22eeb17d6d-5dde-c2c0-1743b23ffbaaa03c%22,%22eeb17d6d-5dde-c2c0-48d80e8c2049f0f3%22,%22eeb17d6d-5dde-c2c0-69052ee717ea9fff%22,%22eeb17d6d-5dde-c2c0-fe008c2729d10384%22,%22eeb17d6d-5dde-c2c0-daeccac6260be38f%22,%22eeb17d6d-5dde-c2c0-9207c76ddd160a93%22,%22eeb17d6d-5dde-c2c0-16be14515b63c590%22,%22eeb17d6d-5dde-c2c0-78056a0452b6c119%22,%22eeb17d6d-5dde-c2c0-41ec08be0f974491%22,%22eeb17d6d-5dde-c2c0-62c4a1a0ca17d38b%22,%22eeb17d6d-5dde-c2c0-62c4a1a0ca17e342%22,%22eeb17d6d-5dde-c2c0-62c4a1a0ca17fd20%22,%223e8b2f0dab5ad76e3e1a0ccdf704d732%22,%22cdee4b097a421c2646e17b0d312f2c23%22,%22cdee4b097a421c2646e17b0d312f0922%22,%22cdee4b097a421c2646e17b0d311cdc76%22%5D%7D%5D%7D&sort=name_sorting
```
I get:

```
Server error: Error: Unspecified error
    at Request._callback (/home/gareth/src/medic/medic-api/node_modules/nano/lib/nano.js:222:15)
    at Request.self.callback (/home/gareth/src/medic/medic-api/node_modules/nano/node_modules/request/request.js:344:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/home/gareth/src/medic/medic-api/node_modules/nano/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/home/gareth/src/medic/medic-api/node_modules/nano/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)

```

**Comment by abbyad** [comment]
Confirming that this is resolved in 0.5.0-alpha.1236.
