### ISSUE TITLE
Failing Karma unit test: TrainingCardsComponent saveForm should do nothing if already saving

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#8439]
**Describe the issue**
A Webapp Training cards unit test is failing with:
```
FAILED TESTS:
  TrainingCardsComponent
    saveForm
      ✖ should do nothing if already saving
        Chrome Headless 115.0.5790.110 (Linux x86_64)
      AssertionError: expected false to be true

      + expected - actual

      -false
      +true
      
    at Context.apply (_karma_webpack_/webpack:/tests/karma/ts/modals/training-cards/training-cards.component.spec.ts:201:63)
    at Context.apply (_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:2030:30)
    at _ZoneDelegate.invoke (_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:372:26)
    at ProxyZoneSpec.onInvoke (_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:287:39)
    at _ZoneDelegate.invoke (_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:371:52)
    at Zone.run (_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:134:43)
    at Context.<anonymous> (_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:1046:33)
```
https://github.com/medic/cht-core/actions/runs/5793958088/job/15702633053#step:11:6527

**Describe the improvement you'd like**
Fix the test.

**Comment by latin-panda** [comment]
@Benmuiruri I'm having a hard time trying to reproduce this issue:
- I've tried running it local multiple times 
  - This test case only
  - This file only
  - Also, all unit tests 
- I haven't seen it failing in other people's PRs ([open PRs](https://github.com/medic/cht-core/pulls) and [past PRs from recent months](https://github.com/medic/cht-core/pulls?q=is%3Apr+is%3Aclosed)) 

It seems fixed, but I don't know what fixed it. No big changes in those files -- so maybe a side effect of something else?

Ben, can you please try it?

**Comment by Benmuiruri** [comment]
Trying now

**Comment by Benmuiruri** [comment]
I've tested in `master` and I have not been able to reproduce. 
- The test case passes 
- The test suite `describe.only('TrainingCardsComponent', () => {}` passes 
- The webapp unit tests pass `npm run unit-webapp`
- All unit tests pass `npm run unit`
