### ISSUE TITLE
Medic API: Crash on startup after update from alpha 1275 to alpha 1290

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#895]
I'm getting a crash on startup in `medic-api` after updating from 1275 to 1290. It has the effect of hanging the Garden update UI halfway through the NPM module restart phase.

Adding the following right above `translations.js:24` seems to fix the issue:

```
    if (!memo.translations) {
      memo.translations = [];
    }
```

Here's the crash and full backtrace:

```
2015-04-17T21:46:33.305Z - info: Medic API listening on port 5988
 
2015-04-17T21:46:33.498Z - error: /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/translations.js:24
    memo.translations.push(setting);
                     ^
TypeError: Cannot read property 'push' of undefined
    at merge (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/translations.js:24:22)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/translations.js:64:9
    at Array.forEach (native)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/translations.js:63:23
    at build (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/properties/lib/read.js:397:17)
    at Object.module.exports [as parse] (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/properties/lib/read.js:478:10)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/translations.js:59:16
    at fs.js:336:14
    at FSReqWrap.oncomplete (fs.js:99:15)
```

I thought about just committing the fix, but another set of eyes for a couple seconds wouldn't hurt.

**Comment by browndav** [comment]
Resolved as of `alpha.1332`, and probably way before then. Moving to ready.
