### ISSUE TITLE
medic-api fails on master and testing branches

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#918]
media-api at 8fdd79f3ef0203e260f4a3245652d901b8ad9549 fails to startup.

```
2015-05-03T22:35:40.374Z - error: util.js:556
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
2015-05-03T22:35:24.172Z - error: TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:556:43)
    at Object.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/http-proxy/lib/http-proxy/index.js:111:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:456:26)
```

**Comment by garethbowen** [comment]
The only advice I can see on this is you must be running an old version of node. What version are you running?

**Comment by browndav** [comment]
@mandric: We just resolved this by updating `http-proxy`, correct? If so, feel free to close and move to acceptance testing.

**Comment by mandric** [comment]
Yep fixed couple weeks ago. d061e2028d4c0e54e82db3dfee3012b185d2a7e5
