### ISSUE TITLE
Medic API: Don't crash when malformed JSON is sent

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#939]
We need to catch JSON parser errors, otherwise the client get unfriendly message and full stack traces, and we may very well crash with an unhandled exception (leading to 503s for other clients).

Issue duplicated from medic/medic-api#13, for inclusion in the next iteration.

```
$ curl -v -XPOST -H 'content-type:application/json' -d '{' 'http://127.0.0.1:5988/api/v1/records'
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 5988 (#0)
* Server auth using Basic with user 'admin'
> POST /api/v1/records HTTP/1.1
> User-Agent: curl/7.37.1
> Host: 127.0.0.1:5988
> Accept: */*
> content-type:application/json
> Content-Length: 1
> 
* upload completely sent off: 1 out of 1 bytes
< HTTP/1.1 400 Bad Request
< X-Powered-By: Express
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 641
< Date: Fri, 08 May 2015 13:10:50 GMT
< Connection: keep-alive
< 
SyntaxError: Unexpected end of input<br> &nbsp; &nbsp;at Object.parse (native)<br> &nbsp; &nbsp;at parse (/Users/mandric/dev/medic-api/node_modules/body-parser/lib/types/json.js:84:17)<br> &nbsp; &nbsp;at /Users/mandric/dev/medic-api/node_modules/body-parser/lib/read.js:102:18<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/Users/mandric/dev/medic-api/node_modules/body-parser/node_modules/raw-body/index.js:149:7)<br> &nbsp; &nbsp;at IncomingMessage.g (events.js:180:16)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:92:17)<br> &nbsp; &nbsp;at _stream_readable.js:929:16<br> &nbsp; &nbsp;at process._tickDomainCallback (node.js:463:13)
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by alxndrsn** [comment]
Is this fixed?  Was closed but scheduled, so a bit confusing.
